### ISSUE TITLE
Benthic items should show up when typing benth in the search frame

### ISSUE THREAD

**Issue by yoshimo** [Jaliborc/Bagnon#1013]
**Is your feature request related to a problem? Please describe.**
I am looking for benthic items in my bags and only the uncoverted tokens show up, not the items created

**Describe the solution you'd like**
Bagnon should also cover the tooltips in the search where the special green benthic tag is added (like warforged or the raid level)

**Comment by raysmith59** [comment]
For future purposes please consider doing this for the upcoming Corrupted gear as well.
