### ISSUE TITLE
Suggestion: Looking to have a corruption icon showing on corrupted gear

### ISSUE THREAD

**Issue by raysmith59** [Jaliborc/Bagnon#1167]
Bagnon may not be the ideal implementation since I'd also like the icon to show on equipped gear but at least an indicator in bags will help ensure I don't DE corrupt items.  Customizable location for the icon on the item frame would be welcome.

**Comment by gaveer** [comment]
Up Up

**Comment by Centias** [comment]
I'm still new to Github so I'm not sure how to link the pull request for my change to get the eye back on bag icons, since it's technically in the WildPants repository and not the Bagnon repository.

Regardless, for now I attached a zip folder with my changes to item.lua that you can drop into \Interface\AddOns\Bagnon\common\Wildpants\classes\ and you should have the eye back for bag icons. It may be possible to add it to the character sheet icons, but that's a bit beyond me at this point.

[item.zip](https://github.com/tullamods/Bagnon/files/4313223/item.zip)

**Comment by raysmith59** [comment]
Looks good to me (although the gear upgrade arrow overwrites it, I'd prefer the corrupt icon be the higher priority of the two) and I've since discovered that hovering over the corruption icon on the character frame highlights equipped corrupt pieces so that part isn't a huge priority.

**Comment by Centias** [comment]
Is the upgrade arrow built into Bagnon? It sounds like something from a different addon, like Pawn or Dugi. I don't have upgrade arrows showing up on my stuff.

**Comment by gaveer** [comment]
`4x ...face\Bagnon\common\Wildpants\classes\item.lua:254: Usage: IsCorruptedItem(itemID|"name"|"itemlink")
[string "=[C]:"]: in function 'IsCorruptedItem'
[string "@Bagnon\common\Wildpants\classes\item.lua"]:254: in function 'UpdateBorder'
[string "@Bagnon\common\Wildpants\classes\item.lua"]:191: in function <...face\Bagnon\common\Wildpants\classes\item.lua:185>
[string "=[C]:"]: ?
[string "=[C]:"]: in function 'Update'
[string "@Bagnon\common\Wildpants\classes\item.lua"]:40: in function <...face\Bagnon\common\Wildpants\classes\item.lua:34>
[string "=(tail call)"]: ?
[string "@Bagnon\common\Wildpants\classes\itemGroup.lua"]:124: in function 'func'
[string "@Bagnon\common\Wildpants\libs\MutexDelay-1.0\MutexDelay-1.0-2.lua"]:36: in function <...mon\Wildpants\libs\MutexDelay-1.0\MutexDelay-1.0.lua:30>`

**Comment by raysmith59** [comment]
I've always assumed it was either stock UI or Pawn but I'm mostly wondering if this icon can be set to the highest strata, that'll at least give it a fighting chance against the arrow.

**Comment by raysmith59** [comment]
I'm also getting the error gaveer sent but only when I try to view other character's bags, I haven't yet seen it when only viewing the active toon's bags.

**Comment by Centias** [comment]
> 
> 
> I'm also getting the error gaveer sent but only when I try to view other character's bags, I haven't yet seen it when only viewing the active toon's bags.

That error comes up when viewing another character's bags? That would explain why I've never had it come up. I only ever used BankItems for viewing the inventory of other characters. I'll have to test this later.

**Comment by Centias** [comment]
After some fiddling, I figured out the fix for the error when viewing another character's inventory.

[item.zip](https://github.com/tullamods/Bagnon/files/4327099/item.zip)

**Comment by gaveer** [comment]
Tested and work 100 %

**Comment by raysmith59** [comment]
Closing since corruption hasn't been a thing for a little while now.
