### ISSUE TITLE
in TBC beta - sorting infinite loop

### ISSUE THREAD

**Issue by laytya** [Jaliborc/Bagnon#1274]
if i press Sorting button - sorting never stop and wow rise reaction "This item not fit this bag"

here is fix:

In sorting.lua  - 170 line

condition need to append  "or (family == 9 and GetItemFamily(id) == 256)"

**Comment by kvakvs** [comment]
Happened to me when i had an item starting a quest, and it tried to sort it into key bag.

**Comment by erounsavall** [comment]
I have the same issue in tbc beta: infinite sorting loop (is trying to put things in keyring, can't, keeps trying). Only a /reload solves it. Bank sorting works fine. 

I tried adding the code as above and then the whole addon errors out. I'm not a coder and perhaps I'm appending incorrectly. What should the actual code be for line 170, or that section?

**Comment by laytya** [comment]
Function should looks like this (lines 168 - 174):
```
function Sort:FitsIn(id, family)
  return
    family == 0 or
    (Addon.IsRetail and bit.band(GetItemFamily(id), family) > 0 or GetItemFamily(id) == family) and
    select(9, GetItemInfo(id)) ~= 'INVTYPE_BAG' or
	(family == 9 and GetItemFamily(id) == 256)
end
```

**Comment by nivfreak** [comment]
This fix appears to sort keys back into your main bags, but does stop the sorting loop.

**Comment by chab95** [comment]
Hi All,

Same error here since today on all my characters. Never got it before.
It seems that it loops when he want to reorganize items on my main default bags with usual items not keys.

![Bagnon_issue](https://user-images.githubusercontent.com/91122620/134145472-29939396-12a2-4279-89f9-d2c33b3f0610.jpg)
s.

**Comment by rozuja** [comment]
Confirm bug. After 2 patches it fail to reorganize.
I have to do it, then /reload and move like 3 items it didnt organize. (The items are allways random)
