### ISSUE TITLE
Bagnon Must Be disabled to deposit anima

### ISSUE THREAD

**Issue by josborne26** [Jaliborc/Bagnon#1474]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.0.3-10.0.0
 - Server patch: [e.g. Build 8.0.1.27178] 10.0.0 (46366)

 **Have you read the changelog? (please don't waste our time)**
Changelog read

**Describe the bug**
When turning in anima, a message pops up that Bagnon has attempted an action that is only available to the Blizzard UI.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to covenant Sanctum
2. Click on 'Deposit Anima'
3. Error appears

**Expected behaviour**
Anima should be deposited in the reservoir.

**Screenshots**
![WoWScrnShot_110322_194119](https://user-images.githubusercontent.com/54518658/199861912-e0fea5d5-eaf3-4049-87f7-df8e539c76b7.jpg)
**Error Logs**
None

**Additional context**

**Comment by Silicon14asp** [comment]
@Jaliborc closed this same report from me 6 days ago. This issue is related to a screw up in Blizzard UI API, and the Bagno Dev team cannot resolve this issue, until Blizzard resolves it on their side. (blizzard bug) This issue is on Bizzard's End (Spaghetti Code)
