### ISSUE TITLE
Not showing guild bank tabs/contents

### ISSUE THREAD

**Issue by booitsme3109** [Jaliborc/Bagnon#1481]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.0.3
 - Server patch: 10.0.0

 **Have you read the changelog? (please don't waste our time)**
Yes

**Describe the bug**
Bagnon guild bank frame not showing tabs or contents of the guild bank.

**To Reproduce**
Steps to reproduce the behaviour:
1. Reset the WoW User Interface (clearing WoW cache)
2. Open Guild Bank

**Expected behaviour**
View all Guild Bank Contents

**Screenshots**
![BagNon Guild bank](https://user-images.githubusercontent.com/52218072/200095234-951d64ca-dd8e-44ad-9a8f-adaa5879a8fc.jpg)
![bagnon wow guild bank](https://user-images.githubusercontent.com/52218072/200095236-7368b93f-949e-4b90-aa46-908ca3d4a1c4.jpg)

**Error Logs**
None

**Additional context**
Yesterday, it showed the contents that were there from months ago. I attempted to add new items and Bagnon wasn't displaying any newly added items. I reset the WoW User Interface and cleared the cache and now does not show anything. Bagnon is only Add-on currently installed.

(Apologies if this was posted already, there were a few similar ones with the bank tabs but I didn't see anything that included the contents.)

**Comment by Centias** [comment]
See if my file here works for you 
https://github.com/tullamods/Bagnon/issues/1458
