### ISSUE TITLE
Bagnon not working with Blizz UI

### ISSUE THREAD

**Issue by stingray66** [Jaliborc/Bagnon#1498]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.0.3-10.0.0
 - Server patch: [e.g. Build 8.0.1.27178]

 **Have you read the changelog? (please don't waste our time)**
 Mark if read.
  Yes
**Describe the bug**
when i launch addon when starting wow
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to wow launcher and when wow launches errors are there
2. Click on new wow bag UI and then comes the 4th error
3. Scroll down the list and it shows 4 errors
(Error 1) Message: ...erface/AddOns/Bagnon/common/Wildpants/api/events.lua:91: attempt to call global 'GetContainerNumSlots' (a nil value)
Time: Thu Nov 17 22:44:24 2022
Count: 1
Stack: ...erface/AddOns/Bagnon/common/Wildpants/api/events.lua:91: attempt to call global 'GetContainerNumSlots' (a nil value)
[string "@Interface/AddOns/Bagnon/common/Wildpants/api/events.lua"]:91: in function `UpdateSize'
[string "@Interface/AddOns/Bagnon/common/Wildpants/api/events.lua"]:33: in function `?'
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua"]:20: in function <...ommon/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua"]:56: in function <...ommon/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Interface/AddOns/DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:24: in function <...ore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Interface/AddOns/DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <.../AddOns/DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:536: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:587: in function `CombatLog_LoadUI'
[string "@Interface/FrameXML/UIParent.lua"]:1484: in function <Interface/FrameXML/UIParent.lua:1362>

Locals: <none>

(Error 2) Message: ...s/Bagnon/common/Wildpants/features/tooltipCounts.lua:34: QuickKeybindTooltip doesn't have a "OnTooltipSetItem" script
Time: Thu Nov 17 22:44:25 2022
Count: 1
Stack: ...s/Bagnon/common/Wildpants/features/tooltipCounts.lua:34: QuickKeybindTooltip doesn't have a "OnTooltipSetItem" script
[string "=[C]"]: in function `HookScript'
[string "@Interface/AddOns/Bagnon/common/Wildpants/features/tooltipCounts.lua"]:34: in function `Hook'
[string "@Interface/AddOns/Bagnon/common/Wildpants/features/tooltipCounts.lua"]:25: in function `?'
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua"]:20: in function <...ommon/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua"]:56: in function <...ommon/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Interface/AddOns/DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:24: in function <...ore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Interface/AddOns/DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <.../AddOns/DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: <none>

(Error 3)  Message: ...erface/AddOns/Bagnon/common/Wildpants/api/events.lua:91: attempt to call global 'GetContainerNumSlots' (a nil value)
Time: Thu Nov 17 22:44:25 2022
Count: 1
Stack: ...erface/AddOns/Bagnon/common/Wildpants/api/events.lua:91: attempt to call global 'GetContainerNumSlots' (a nil value)
[string "@Interface/AddOns/Bagnon/common/Wildpants/api/events.lua"]:91: in function `UpdateSize'
[string "@Interface/AddOns/Bagnon/common/Wildpants/api/events.lua"]:71: in function `?'
[string "@Interface/AddOns/DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:114: in function <...ore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Interface/AddOns/DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:24: in function <...ore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Interface/AddOns/DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <.../AddOns/DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: <none>

(Error 4 after clikcing bag button) Message: ...Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:178: attempt to call global 'GetContainerNumFreeSlots' (a nil value)
Time: Thu Nov 17 23:00:37 2022
Count: 1
Stack: ...Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:178: attempt to call global 'GetContainerNumFreeSlots' (a nil value)
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua"]:178: in function <...Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:160>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/frame.lua"]:117: in function <...ace/AddOns/Bagnon/common/Wildpants/classes/frame.lua:116>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/itemGroup.lua"]:46: in function `RegisterEvents'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/itemGroup.lua"]:32: in function `Update'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/itemGroup.lua"]:27: in function <...AddOns/Bagnon/common/Wildpants/classes/itemGroup.lua:13>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:26: in function `New'
[string "@Interface/AddOns/Bagnon/common/Wildpants/api/frames.lua"]:44: in function `New'
[string "@Interface/AddOns/Bagnon/common/Wildpants/api/frames.lua"]:81: in function `Show'
[string "@Interface/AddOns/Bagnon/common/Wildpants/api/frames.lua"]:77: in function <...erface/AddOns/Bagnon/common/Wildpants/api/frames.lua:76>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/common/Wildpants/features/autoDisplay.lua"]:82: in function `ToggleBag'
[string "@Interface/FrameXML/MainMenuBarBagButtons.lua"]:76: in function <Interface/FrameXML/MainMenuBarBagButtons.lua:66>
[string "=[C]"]: ?

Locals: self = <table> {
 IsKeyring = <function> defined @Interface/AddOns/Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:405
 FrameTemplate = "BackdropTemplate"
 IsRetail = true
 GetOwnerID = <function> defined @Interface/AddOns/Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:285
 Frames = <table> {
 }
 Currency = <table> {
 }
 InBank = <function> defined @Interface/AddOns/Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:382
 ItemGroup = <table> {
 }
 RestoreItemData = <function> defined @Interface/AddOns/Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:319
 Frame = <table> {
 }
 OptionsToggle = <table> {
 }
 Bag = <table> {
 }
 IsBank = <function> defined @Interface/AddOns/Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:409
 RegisterMessage = <function> defined @Interface/AddOns/DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:85
 UnregisterMessage = <function> defined @Interface/AddOns/DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:148
 IsBagCached = <function> defined @Interface/AddOns/Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:306
 Base = <table> {
 }
 UnregisterSignal = <function> defined @Interface/AddOns/Bagnon/common/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua:78
 GetOwnerAddress = <function> defined @Interface/AddOns/Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:290
 RegisterEvent = <function> defined @Interface/AddOns/DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:85
 sets = <table> {
 }
 OnEnable = <function> defined @Interface/AddOns/Bagnon/common/Wildpants/Wildpants.lua:101
 Name = "Bagnon"
 IterateOwners = <function> defined @Interface/AddOns/Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:129
 InGuild = <function> defined @Interface/AddOns/Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:390
 Parented = <table> {
 }
 NewModule = <function> defined @Interface/AddOns/Bagnon/common/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua:68
 RestorePetLinkData = <function> defined @Interface/AddOns/Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:373

**Expected behaviour**
the bag should open up as before showing access to bag inventory as well as all other characters

**Screenshots**
![bagnon error](https://user-images.githubusercontent.com/42881157/202817583-ddb80b82-28d3-4de9-80e8-d637fc0d8e16.PNG)

this was after i clicked on the bag button
![bagnon error1](https://user-images.githubusercontent.com/42881157/202817683-5462991b-9f18-4cd7-8911-bdb46768401e.PNG)

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the message with `ID: 1` (labelled 1/X). This is generally NOT the message that the window shows by default.
Error shows up immediately after launching game with Bagnon enabled in addon list and it's the same error as above 
**Additional context**
when i load game with bagnon enabled and use /console scriptErrors 0 and reload the bag button is non functionable..I alos got the same error as the 4th when i clicked on the mailbox. I also disabled all my addons except Bagnon and still got the above errors

Tks hope it helps

**Comment by Taplatero** [comment]
same problem!.

**Comment by yoshimo** [comment]
Lots of functions regarding bags moved below the C_Container node.
This is the easy one.
Tooltip API changed in 10.0 and again in 10.0.2 which is the bigger challenge.
Has to be done in Wildpants as library.

tooltipcounts.lua fails at
	```
tip:HookScript('OnTooltipCleared', self.OnClear)
	tip:HookScript('OnTooltipSetItem', self.OnItem)
```

**Comment by Schlasi** [comment]
I have the same problem O-O

**Comment by stingray66** [comment]
seen on a twitch stream the author is experiencing some personal issues so pls be patient

________________________________

**Comment by Schlasi** [comment]
Thank You :-)
