### ISSUE TITLE
LUA error in Wildpants when going into Void and Guild frame tab in options

### ISSUE THREAD

**Issue by raysmith59** [Jaliborc/Bagnon#1521]
Version 10.0.5

Happens when I go into the Void and Guild frame settings in options.

3x ...on/Wildpants/libs/Sushi-3.1-5/classes/drops/Choice.lua:49: bad argument #1 to 'ipairs' (table expected, got nil)
[string "=[C]"]: in function `ipairs'
[string "@Bagnon/common/Wildpants/libs/Sushi-3.1-5/classes/drops/Choice.lua"]:49: in function `method'
[string "@Bagnon/common/Wildpants/libs/Sushi-3.1-5/classes/core/Callable.lua"]:53: in function `FireCalls'
[string "@Bagnon/common/Wildpants/libs/Sushi-3.1-5/classes/groups/Group.lua"]:70: in function `Update'
[string "@Bagnon/common/Wildpants/libs/Sushi-3.1-5/classes/groups/Group.lua"]:89: in function `method'
[string "@Bagnon/common/Wildpants/libs/Sushi-3.1-5/classes/core/Callable.lua"]:53: in function `FireCalls'
[string "@Bagnon/common/Wildpants/libs/Sushi-3.1-5/classes/buttons/Clickable.lua"]:40: in function <...ldpants/libs/Sushi-3.1/classes/buttons/Clickable.lua:34>
[string "=(tail call)"]: ?
[string "@Bagnon/common/Wildpants/libs/Sushi-3.1-5/classes/drops/Button.lua"]:69: in function <...on/Wildpants/libs/Sushi-3.1/classes/drops/Button.lua:67>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by Peregran** [comment]
Just installed 10.0.6, still getting errors on the Guild Tab:

82x SharedXML/Tooltip/TooltipUtil.lua:8: attempt to index local 'tbl' (a nil value)
[string "@SharedXML/Tooltip/TooltipUtil.lua"]:8: in function `SurfaceArgs'
[string "@Bagnon_ItemInfo/modules/itembind.lua"]:112: in function `update'
[string "@Bagnon_ItemInfo/dispatcher.lua"]:68: in function <Bagnon_ItemInfo/dispatcher.lua:66>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Update'
[string "@Bagnon/common/Wildpants/classes/item.lua"]:129: in function <...faceBagnon/common/Wildpants/classes/item.lua:124>
[string "=[C]"]: in function `Show'
[string "@Bagnon/common/Wildpants/classes/item.lua"]:43: in function <...faceBagnon/common/Wildpants/classes/item.lua:35>
[string "=(tail call)"]: ?
[string "@Bagnon/common/Wildpants/classes/itemGroup.lua"]:124: in function `func'
[string "@Bagnon/common/Wildpants/libs/MutexDelay-1.0-2/MutexDelay-1.0.lua"]:36: in function <...mon/Wildpants/libs/MutexDelay-1.0/MutexDelay-1.0.lua:30>

Locals:
tbl = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'tbl' (a nil value)"

**Comment by Jaliborc** [comment]
cannot replicate :(

**Comment by Peregran** [comment]
Sorry to hear you couldn't replicate it.   Just downloaded the latest update and no more errors (Yay) but when mousing over items, some don't show tooltips and others show wrong tools tips.   This is in reference to the Guild Bank
[WoWScrnShot_112922_165114.zip](https://github.com/Jaliborc/Bagnon/files/10117630/WoWScrnShot_112922_165114.zip)
The mouse was over the piece of ore on the top row for reference.
