### ISSUE TITLE
Unable to view contents of bank remotely

### ISSUE THREAD

**Issue by gythwulf** [Jaliborc/Bagnon#1526]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.0.6
 - Server patch: 10.0.2.46801

 **Have you read the changelog? (please don't waste our time)**
yes

**Describe the bug**
When I open the bank remotely, It shows all of the bank slots, but it does not show any of the items in the bank.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Bagnon
2. Right-click "Bag Slots" icon
3. no bank items are shown

**Expected behaviour**
Items in the bank display normally

**Error Logs**
There are no errors

**Additional context**
I initially thought that perhaps I needed to visit my bank first since the latest update, but even after visiting my bank, no items are shown when I try to view my bank remotely.

And in case it matters, I have the Guild Bank and Void Storage plugins disabled (though I tried enabling them and it still did not work).

**Comment by alexnaumovich** [comment]
Do you have BagBrother addon enabled by any chance?

**Comment by gythwulf** [comment]
BagBrother is enabled, forgot to mention that. That is packaged with Bagnon, right? I did not see a separate addon.

**Comment by Fyler74** [comment]
I can confirm. I have the same problem as well.
