### ISSUE TITLE
Bagnon has been blocked from an action only available to the Blizzard UI

### ISSUE THREAD

**Issue by Edmaster530** [Jaliborc/Bagnon#1528]
**Running Software (issues missing this information will be deleted):**
 - Addon version: Bagnon-10.0.6 for WoW-10.0.2.zip
 - Server patch: [e.g. Build 8.0.1.27178] 10.0.2.46801

 **Have you read the changelog? (please don't waste our time)**
 Mark if read.
Yes

**Describe the bug**
When the end-user disables the inventory (while keeping the bank / guild options on) the end-user is unable to use certain items without constantly triggering the default WoW alert mentioned in title.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open bagnon configuration, disable inventory
2. Open inventory (should have default WoW UI)
3. Attempt to use hearthstone

**Expected behaviour**
I'm not sure here other that the error shouldn't be prompted.  I'm not sure why though the system is referencing the inventory at all if it's been "disabled".

**Screenshots**
Not sure it's applicable

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the message with `ID: 1` (labelled 1/X). This is generally NOT the message that the window shows by default.
No logs shown

**Additional context**
I made sure to completely remove all my addon folder content, re-install the bagnon addon only and then checked that the error still persists and it does.

**Comment by jcliu0** [comment]
pretty sure it has something to do with the empower skills for dracyr, everytime i press one of those it bugs out.

**Comment by MrRawrrino89** [comment]
I  am getting this even with custom made macro's when i press it i get it
