### ISSUE TITLE
can't see items on alt 

### ISSUE THREAD

**Issue by madmat1993** [Jaliborc/Bagnon#1532]
For some unknown reason each time i logged onto my main or alt on wrath classic  i cannot see their items in inventory, bank and guild bank.

This hasn't happened before only today since the update is there a chance that it can resolved at somepoint ?

**Comment by Knakriktsur** [comment]
I have the same Problem and can`t see bag or Bank from alts.
WOTLK 3.4.0.46779 GER client
Bagnon 28/11/2022 Bagnon-10.0.6 for WoW-3.4.0
