### ISSUE TITLE
New regent Pouch 26 slot

### ISSUE THREAD

**Issue by Jonny-Aitch** [Jaliborc/Bagnon#1533]
![Screenshot (54)](https://user-images.githubusercontent.com/75708597/204597269-10a1dadc-8f65-40d4-b458-df0826005841.png)

This is a new reagent pouch from Ruby Lifeshrine 26 slot bag.
/reload delete cache does not remove the message.
Only option is to turn Bagnon off.

**Comment by Jonny-Aitch** [comment]
I have removed it know but you do need to disable bagnon to get the abiliy to close the message

**Comment by vipii** [comment]
Same with the 32 slot bag. "Simply stitched Reagent bag"
https://screenshots.expliciet.be/Mvmo0z

Even after disabling bagnon, opening and closing the bag, the notice goes away.
But whenI re-enable bagnon, the notice comes back.

**Comment by vipii** [comment]
> Same with the 32 slot bag. "Simply stitched Reagent bag" https://screenshots.expliciet.be/Mvmo0z
> 
> Even after disabling bagnon, opening and closing the bag, the notice goes away. But whenI re-enable bagnon, the notice comes back.

A relog seems to fix this sometimes apparently.

**Comment by ShawnSmall43** [comment]
> > Same with the 32 slot bag. "Simply stitched Reagent bag" https://screenshots.expliciet.be/Mvmo0z
> > Even after disabling bagnon, opening and closing the bag, the notice goes away. But whenI re-enable bagnon, the notice comes back.
> 
> A relog seems to fix this sometimes apparently.

I have this problem also but reloging does not fix for me.

**Comment by Jonny-Aitch** [comment]
With bagnon off after a few tries the message should give you an option to close it. May need to completely uninstall bagnon also.
