### ISSUE TITLE
Bagnon still dependant on BagBrother despite update.

### ISSUE THREAD

**Issue by leginnos1en** [Jaliborc/Bagnon#1535]
Hello I see there has been an update yet Bagnon is still needs BagBrother to run. This is unnecessary, please fix this bug that I have already informed you of.

**Comment by Vilogity** [comment]
Sorry for the Question, but without BagBrother it dosnt work ?

**Comment by Jevnaker** [comment]
yeah i bagbrother has been required for it to work since i started using bagnon quite some time ago so i was also confused by this issue thingy.
