### ISSUE TITLE
10 seconds of severe lag on login

### ISSUE THREAD

**Issue by BradCOnGitHub** [Jaliborc/Bagnon#1538]
Immediately after logging in I get client lag that brings me to 3 FPS for 10-15 seconds. Disabling BagBrother (which disables Bagnon) makes the lag no longer occur.

I deleted the cached characters I had but it doesn't seem to help

**Comment by ZJKonWoW** [comment]
Same issue, immediately after update 10.0.7 for WoW-10.0.2 except log in screen sticks with full blue bar and WoW unresponsive for several minutes.
Was really looking forward to having Bagnon back again.

**Comment by Jevnaker** [comment]
same also during the mega lag im unable to even alt tab back into the game before the lag has stopped.

**Comment by alexnaumovich** [comment]
Similar issue is discussed [here](https://github.com/Jaliborc/Bagnon/issues/1513).
