### ISSUE TITLE
Log in Hangs, WoW Unresponsive

### ISSUE THREAD

**Issue by ZJKonWoW** [Jaliborc/Bagnon#1539]
- Addon version:  10.0.7 for WoW-10.0.2
 - Server patch: 10.0.0.46879

Read the Changelog

Immediately after update the log in screen sticks with full blue bar and WoW goes unresponsive for a minutes, then logs into a frozen screen for several minutes
Disabled Bagnon, no issues. Deleted Bagnon, no issues.

Steps to reproduce the behaviour:
1. Bagnon enabled
2. Log in on a charachter

**Expected behaviour**
Expect to log in 

**Screenshots**
None that shows you anything of worth

**Error Logs**
None

**Comment by eSkiSo** [comment]
Have the same issue, downloaded “Addon Usage” addon to see what addon was causing the slowness, Bagnon had 50 cpu usage, next in line was around 9. Disabled Bagnon and game got back to normal loading times. (All around slowness not just on load btw)

**Comment by vril14** [comment]
Same problem...  ver. 10.0.7 and same problem with release type beta

**Comment by ZJKonWoW** [comment]
Still happening as of 10.0.8 update

**Comment by alexnaumovich** [comment]
Similar issue is discussed [here](https://github.com/Jaliborc/Bagnon/issues/1513).
