### ISSUE TITLE
bagnon causes game crash

### ISSUE THREAD

**Issue by fergusincoronato** [Jaliborc/Bagnon#1541]
- Addon version: 10.0.7 for WoW-10.0.2
 - Server patch: 10.0.0.46879

**Comment by Jevnaker** [comment]
I also have this issue but only if i have the blizzard unified bag turned on when i activated the addon otherwise i just have mega lag like described in other issues.

**Comment by FROlCi** [comment]
+1 at the start of the game on the lag. after it wokrs perfectly

**Comment by vril14** [comment]
same here

**Comment by fergusincoronato** [comment]
> I also have this issue but only if i have the blizzard unified bag turned on when i activated the addon otherwise i just have mega lag like described in other issues.

I have it without unified bags. Five second freeze then crash.

**Comment by Hindrex** [comment]
Same for me, can't even get out of the loading screen.

**Comment by alexnaumovich** [comment]
Similar issue is discussed [here](https://github.com/Jaliborc/Bagnon/issues/1513).
