### ISSUE TITLE
Empty tooltip window when selling or disenchanting

### ISSUE THREAD

**Issue by Trajor** [Jaliborc/Bagnon#1543]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.0.7 for WoW-3.4.0        (present in all 10.0.X versions)
 - Server patch: [e.g. Build 8.0.1.27178]  3.4.0.46779

 **Have you read the changelog? (please don't waste our time)**
Yes

**Describe the bug**
Bagnon 10.0.X for WoW-3.4.0 introduced a bug when selling or disenchanting an item, it leaves behind a blank empty tooltip window.  The behavior in Bagnon 9.2.2 is the tooltip window immediately closes.
This was previously reported on curseforge by several users.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to an npc merchant
2. Right click on any item to sell it
3. See empty tooltip window

**Expected behaviour**
Tooltip window should immediately close

**Screenshots**
![Empty_Tooltip_after_selling](https://user-images.githubusercontent.com/24498585/204820678-5251182d-efbe-40ad-8313-d0b1a11f61cd.JPG)

**Error Logs**
None

**Additional context**
Workaround is to roll back to 9.2.2 for 3.4.0

**Comment by agable74** [comment]
Same behavior is seen when you move an item and quickly move cursor back to the old bag slot. I had been using 9.2.2 as a workaround until some other addon I had been using updated and broke that version of Bagnon. Seen when all addons disabled aside from Bagnon and BagBrother
![image](https://user-images.githubusercontent.com/33661673/205186052-353cc733-bf20-4fa9-a8c1-be3add84a0f6.png)
