### ISSUE TITLE
ElvUI and/with BagBrother Error in instance

### ISSUE THREAD

**Issue by SypherRed** [Jaliborc/Bagnon#1550]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.0.8 for 10.0.2
 - ElvUI version: 13.07
 - Server patch: 10.0.2.46879

 **Have you read the changelog? (please don't waste our time)**
 ✅

**Describe the bug**
While being in an instance, I get a red error message in chat and the error message window jumps on me directly out of combat with the below error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have ElvUI
2. Be in an instance
3. Use spells and/or have while in combat your bag open? (Really don't know what exactly might trigger it)
4. See error output below

**Expected behaviour**
I really don't know since I'm unsure if that is from Bagnon or ElvUI, but I do face quite some issues with Bagnon since BagBrother is a think now. (They are already mentioned in previous reports)

**Screenshots**

**Error Logs**
```
Message: ADDON_ACTION_BLOCKED: ElvUI versucht die geschützte Funktion aufrufen 'MultiBarBottomRight:SetPointBase()'.
Time: Thu Dec  1 09:00:13 2022
Count: 3
Stack: ADDON_ACTION_BLOCKED: ElvUI versucht die geschützte Funktion aufrufen 'MultiBarBottomRight:SetPointBase()'.
[string "@Interface/AddOns/BagBrother/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...her/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/BagBrother/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/BagBrother/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...AddOns/BagBrother/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `SetPointBase'
[string "@Interface/FrameXML/EditModeSystemTemplates.lua"]:72: in function `SetPoint'
[string "@Interface/FrameXML/EditModeManager.lua"]:628: in function `UpdateBottomActionBarPositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:554: in function `UpdateActionBarLayout'
[string "@Interface/FrameXML/ActionBar.lua"]:351: in function `UpdateVisibility'
[string "@Interface/FrameXML/ActionBar.lua"]:310: in function `Show'
[string "@Interface/FrameXML/MainMenuBar.lua"]:119: in function `Update'
[string "@Interface/FrameXML/MainMenuBar.lua"]:96: in function <Interface/FrameXML/MainMenuBar.lua:95>

Locals: <none>
```

**Additional context**
Only active options in ElvUI regarding bags are "Cooldowntext" and "Sell grey items" within the modul options.
Everything in its own "Bag" category is disabled except the sell grey items.

For above a translation of the lines with:
```
Message: ADDON_ACTION_BLOCKED: ElvUI versucht die geschützte Funktion aufrufen 'MultiBarBottomRight:SetPointBase()'.
```
to
```
Message: ADDON_ACTION_BLOCKED: ElvUI tried to call the protected function 'MultiBarBottomRight:SetPointBase()'.
```

**Comment by Jaliborc** [comment]
Nothing to do with bagbrother
