### ISSUE TITLE
A green arrow upgrade indicator stays shown on an empty bag slot after moving an item with that indicator to a different slot 

### ISSUE THREAD

**Issue by alexnaumovich** [Jaliborc/Bagnon#1556]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.0.9
 - Server patch: Build 10.0.2.46924

 **Have you read the changelog? (please don't waste our time)**
I did.

**Describe the bug**
I have Bagnon and Pawn installed together. Pawn (I assume) displays a green arrow on an item in my bags which is an upgrade for my character. If I move such item from one bag slot into another, the arrow is now shown on both old and new slot. 
I am not sure if the Pawn is to blame for this, or Bagnon is, so reporting it for both. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Have Bangon and Pawn installed together.
2. Have an item in your bag that has better stats than the one your character has equipped, displayed with a green arrow.
3. Move this item to a different bag slot. 
4. Observe the green arrow shown on both slots.

**Expected behaviour**
I expect an arrow to be shown on an item and not on an empty bag slot.

**Screenshots**
![image](https://user-images.githubusercontent.com/40657589/205389001-1724f8f6-fe98-4d54-a72a-d2c98855d222.png)

**Error Logs**
No errors.

**Additional context**
The green arrow on an empty bag slot can be removed by moving any other item on that slot.

**Comment by ChloeMarie** [comment]
Having this issue too.

**Comment by Neciss** [comment]
Same for me, but with green border and item level in empty slots. It seems like only main bag is bugged. As soon as I move the item which is causing the issue to another bag, it's fine.

![image](https://user-images.githubusercontent.com/36779345/205447724-dbc79df9-5009-44bb-a486-669583dd7825.png)
