### ISSUE TITLE
Momentary Freeze & FPS Drop

### ISSUE THREAD

**Issue by Razertongue** [Jaliborc/Bagnon#1558]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.0.10
 - Server patch: [e.g. Build 10.0.2.46924

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. Yes

**Describe the bug**
When Addon is enabled, I see a 10 frame drop. There is also 5-10 seconds of a complete screen lock up while something is loading. Similar to how databases are built with ATT or Auctionator. 

**To Reproduce**
Steps to reproduce the behaviour:
1- Install Addon 
2 (optional)- Wipe setting from BagBrother and Combuctor from previous installs)

**Expected behaviour**
No screen lock on any load or /reload. FPS drop would be nice to avoid too. 

**Screenshots**
https://imgur.com/a/fRju37X

**Error Logs**
None

**Additional context**
PC Runing:
Intel i7-12700k
RTX 3070 TI
16 Gigs Memory
Installed on SSD

**Comment by Snipy2k4** [comment]
same here. login and relog feeze. sporadic lag when opening the bag

**Comment by MarcEspiard** [comment]
Same here, full freeze on initial load for up to 30 seconds, even didn't load at all once. Happened right after a clean addon install. Disabling the addon completly fixed the issue (I have very few addons)

**Comment by Nillx** [comment]
This was happening way before DF.

**Comment by Snipy2k4** [comment]
I have the problem but currently with Bagnon-10.0.10 for WoW-10.0.2.zip .... and the current patch version 04.12.202

**Comment by teknosavy** [comment]
> Same here, full freeze on initial load for up to 30 seconds, even didn't load at all once. Happened right after a clean addon install. Disabling the addon completly fixed the issue (I have very few addons)

Same here but game crashes in end or I get disconnected.

**Comment by teknosavy** [comment]
> **Running Software (issues missing this information will be deleted):**
> 
> * Addon version: 10.0.10
> * Server patch: [e.g. Build 10.0.2.46924
> 
> **Have you read the changelog? (please don't waste our time)** Mark if read. Yes
> 
> **Describe the bug** When Addon is enabled, I see a 10 frame drop. There is also 5-10 seconds of a complete screen lock up while something is loading. Similar to how databases are built with ATT or Auctionator.
> 
> **To Reproduce** Steps to reproduce the behaviour: 1- Install Addon 2 (optional)- Wipe setting from BagBrother and Combuctor from previous installs)
> 
> **Expected behaviour** No screen lock on any load or /reload. FPS drop would be nice to avoid too.
> 
> **Screenshots** https://imgur.com/a/fRju37X
> 
> **Error Logs** None
> 
> **Additional context** PC Runing: Intel i7-12700k RTX 3070 TI 16 Gigs Memory Installed on SSD

This version works from IcyVeins works. You first need to delete Bagnon in its entirety from the addon folder and then install it however. Here it is. Also side note, game still freezes for full like 30-40 seconds before load but then goes on to work, most of the time anyways.
Icy Veins Link - https://www.icy-veins.com/forums/topic/69751-working-version-of-bagnon-for-patch-1002/
Download Link in Icy Veins Post - https://drive.google.com/file/d/1Xz1_yB0SuLI8gwENN87jHzx-hbquh8Au/view

P.S. Make sure to delete the previous installation of Bagnon otherwise it wont work.

**Comment by godlike64** [comment]
Same here, but I always get a disconnect after that freeze is over. The workaround I have found is to login, disable Bagnon on the character select screen, log in with a character, and **then** enable Bagnon and reload. Only Bagnon needs to be disabled/re-enabled thus (all the other addons get disabled as dependencies).

If ever I get kicked out to the login screen (not the character selection screen - a different bug in Pet Tracker/Rematch causes this when entering a pet battle) I have to repeat the workaround, otherwise I also get instant disconnect after one of my characters loads.

**Comment by teknosavy** [comment]
> Same here, but I always get a disconnect after that freeze is over. The workaround I have found is to login, disable Bagnon on the character select screen, log in with a character, and **then** enable Bagnon and reload. Only Bagnon needs to be disabled/re-enabled thus (all the other addons get disabled as dependencies).
> 
> If ever I get kicked out to the login screen (not the character selection screen - a different bug in Pet Tracker/Rematch causes this when entering a pet battle) I have to repeat the workaround, otherwise I also get instant disconnect after one of my characters loads.

Did you try Bagnon version I just linked?

**Comment by Razertongue** [comment]
> > Same here, but I always get a disconnect after that freeze is over. The workaround I have found is to login, disable Bagnon on the character select screen, log in with a character, and **then** enable Bagnon and reload. Only Bagnon needs to be disabled/re-enabled thus (all the other addons get disabled as dependencies).
> > If ever I get kicked out to the login screen (not the character selection screen - a different bug in Pet Tracker/Rematch causes this when entering a pet battle) I have to repeat the workaround, otherwise I also get instant disconnect after one of my characters loads.
> 
> Did you try Bagnon version I just linked?

I mean, linking an IcyVein link is unnecessary, you can download old version right from Curse. 

That being said too, old versions are old for a reason, especially this early in a patch. Downloading 10.02 will reintroduce a bunch of inefficiencies and potentially make your play experience worse.

**Comment by teknosavy** [comment]
> > > Same here, but I always get a disconnect after that freeze is over. The workaround I have found is to login, disable Bagnon on the character select screen, log in with a character, and **then** enable Bagnon and reload. Only Bagnon needs to be disabled/re-enabled thus (all the other addons get disabled as dependencies).
> > > If ever I get kicked out to the login screen (not the character selection screen - a different bug in Pet Tracker/Rematch causes this when entering a pet battle) I have to repeat the workaround, otherwise I also get instant disconnect after one of my characters loads.
> > 
> > 
> > Did you try Bagnon version I just linked?
> 
> I mean, linking an IcyVein link is unnecessary, you can download old version right from Curse.
> 
> That being said too, old versions are old for a reason, especially this early in a patch. Downloading 10.02 will reintroduce a bunch of inefficiencies and potentially make your play experience worse.

Thats what im telling you, I can play with the IcyVeins older version but cannot play with newest bagnon version which is very annoying to me....

**Comment by AevusErus** [comment]
I've been encountering this same issue with the game freeze and FPS dropping when logging in. 

I agree with the observation of @Razertongue that the behavior if very similar to other addons when they're rebuilding a database, like TSM, or also similar to addons that run lots of calculations like TLDR Missions. Is it possible that there is some sort of heavy calculation being done on load or perhaps BagBrother loading in data?

Apologies, I haven't had a chance to read over all the code and get a better understanding of things, just kind of spitballing ideas in the hope that they might trigger a thought.

**Comment by godlike64** [comment]
I don't know what happened, I don't recall there being an addon update, but for some reason since yesterday I stopped getting the disconnect. I still get a big freeze first time I log in to a character (with the game being closed) but no more disconnects.
