### ISSUE TITLE
Is there a reason why BagBrother cannot be disabled?

### ISSUE THREAD

**Issue by Nillx** [Jaliborc/Bagnon#1560]
Came back to Bagnon but i cannot figure out why im unable to disable BagBrother anymore. Would be nice if there was a way to disable its features since i prefer to keep my tooltips as close to the default ones as possible.

**Comment by UglaSannur** [comment]
I support this opinion. Author, please make BagBrother disabled. It lags, reduces FPS, and sometimes the game freezes completely when loading.
It is unfortunate that such a wonderful addon has become problematic just because of one option.

**Comment by Razertongue** [comment]
> I support this opinion. Author, please make BagBrother disabled. It lags, reduces FPS, and sometimes the game freezes completely when loading. It is unfortunate that such a wonderful addon has become problematic just because of one option.

If you look into "What" BagBrother is, its the actual engine for the addon. We only see it as providing the information between alts (which is a redundant feature to anyone using Alto) BUT its definitely required.

You can comment out the dependency in the BagNon.TOC and allowing you to 'disable' it but BagNon doesnt work without it. From what I can see, BagBrother is the code that allows BagNon and Combuctor to be worked on seperately but also the same. 

I (and im sure the author) would love to know what about BagBrother is "slow" when its basically 90% OF BagNon

**Comment by Nillx** [comment]
I dont really have any performance issues with it, all i wish was to be able to hide the name of my char and alts on the tooltip

**Comment by Razertongue** [comment]
> I dont really have any performance issues with it, all i wish was to be able to hide the name of my char and alts on the tooltip

![image](https://user-images.githubusercontent.com/42005883/205524757-51d2136a-26e8-4db4-9cbf-1f68aae7fc12.png)

**Comment by yad** [comment]
Try to delete (or move for backup) your bagnon addon config/cache/saves files :

.\World of Warcraft\_retail_\WTF\Account\{YOURID}#1\SavedVariables\BagBrother.lua
.\World of Warcraft\_retail_\WTF\Account\{YOURID}#1\SavedVariables\Bagnon.lua
