### ISSUE TITLE
Bagnon Crashing WoW Upon Login

### ISSUE THREAD

**Issue by teknosavy** [Jaliborc/Bagnon#1561]
Since 10.0.2 Bagnon is crashing my game immediately upon logging in. The only solution I found was using this Bagnon that was provided on IcyVeins. 

Icy Veins Post - https://www.icy-veins.com/forums/topic/69751-working-version-of-bagnon-for-patch-1002/
Download Link to One that Works - https://drive.google.com/file/d/1Xz1_yB0SuLI8gwENN87jHzx-hbquh8Au/view

When WoW loads with official newest build of Bagnon, it basically freezes World of Warcraft. Its odd because I can hear the ambient environment noise and the sound of friends logging in and out. It seems like game is working other than being visually frozen and nothing works. If I click one too many times then windows crashes the game. Nothing happens until I finally control alt delete to exit game. Altered version also freezes game but eventually unfreezes. Not sure what the difference between them is but one crashes my game and the other does not. If someone could help me I would highly appreciate it, thank you.

**Comment by Aur0r4** [comment]
When I login while Bagnon is enabled I can see my character and then the screen is freezing for abour 3-5 seconds. When I move while it is freezed it even takes longer. 
So its not crashing my game as long I keep calm and do not click any button. Never seen that issue before 10.0.

**Comment by teknosavy** [comment]
I dont click anything, nothing at all and it either crashes or just does nothing indefinitely.

**Comment by AevusErus** [comment]
I've run into the same issue as well. If I try to move my character or do anything immediately after logging in, it'll freeze my game. But if I wait 5-10 seconds, it'll clear up and seem to be mostly fine from that point forward.

**Comment by wellhyper** [comment]
My game literally freezes for 3 mins solid when I first log into the game (including if I DC and log back), when swapping between chars it "only " freezes about 1 minute or so..

I could live with this as I love the addon, but after being DC'd twice this evening and having to literally wait 3/4 mins before I could do anything means I'm gonna have to disable it for the time being. :(

**Comment by teknosavy** [comment]
I dont understand why this hasnt been addressed.

**Comment by Jevnaker** [comment]
yeah still an issue for me too and not sure why it hasnt been adressed yet.

**Comment by rlanglee** [comment]
I have this same exact issue....

**Comment by coldimmune** [comment]
Same issue, WoW takes several minutes to load a character. Won't even maximize and if you try to do anything Windows tries to shut it down as not responding

Disabling Bagbrother immediately resolves it, but then I lose all Bagnon functionality

**Comment by Aur0r4** [comment]
Just updated to latest version of Bagnon:
Seems like its fixed now. I had zero lag/fps issues after login with two characters.

Thanks @Jaliborc
