### ISSUE TITLE
Bagnon and Profession Bags

### ISSUE THREAD

**Issue by Licht95** [Jaliborc/Bagnon#1564]
Hello.

I would appreciate if you could add the ability to specify the sorting of profession bags. For example to have the profession bag appear the the botttom end of the inventory instead of having it at the top of it.
![5e753781658126108e8c67864dc653fb](https://user-images.githubusercontent.com/108841000/205538022-f49d1dc5-bbdd-4453-9bf6-47ca3cedcadd.jpg)

**Comment by Licht95** [comment]
I know there is an option to invert the bag but I'd like this solely for the profession bag. I'd even settle with an option to exclude the profession bag like the blizzard UI does. 
![ca62eec60f93e5ac63c177e2e83fe7cb](https://user-images.githubusercontent.com/108841000/205538793-94ee0224-4584-4d97-b6f8-82cb45356301.jpg)

**Comment by Jaliborc** [comment]
dont know what you did with the settings, but the bag shows at the bottom by default
