### ISSUE TITLE
New reagent bag notification not disappearing when opening bag

### ISSUE THREAD

**Issue by szukir1996** [Jaliborc/Bagnon#1566]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.0.10
 - Server patch: Build 10.0.2 (46924)

 **Have you read the changelog? (please don't waste our time)**
yes

**Describe the bug**
When you craft a new reagent bag for the first time via tailoring profession, the game displays a notification window above your bag that you should open it. It does not disappear when you click it. If you disable the addon then click the bag, it disappears.

**To Reproduce**
Steps to reproduce the behaviour:
1. Craft a reagent bag for the first time.

**Expected behaviour**
It should disappear.

**Comment by Bashercon** [comment]
Bump I am having the same issue , received a new reagent bag and it has a message in a gold box that will not go away that states - You've obtained a reagent bag! open your bags . i have removed and put that bag back that the gold box remains with no way to get rid of it 
![WoWScrnShot_120622_185703](https://user-images.githubusercontent.com/119981898/206051582-0d5eb892-1d0c-45c5-ac3d-e84a90b00e5b.jpg)
Please help

**Comment by szukir1996** [comment]
> Bump I am having the same issue , received a new reagent bag and it has a message in a gold box that will not go away that states - You've obtained a reagent bag! open your bags . i have removed and put that bag back that the gold box remains with no way to get rid of it
> ![WoWScrnShot_120622_185703](https://user-images.githubusercontent.com/119981898/206051582-0d5eb892-1d0c-45c5-ac3d-e84a90b00e5b.jpg)
> Please help

hey. there is a workaround. disable the addon, then you can click the bag.

**Comment by Bashercon** [comment]
That did the trick . Thank you
