### ISSUE TITLE
Button to deposit all reagents in the bank window

### ISSUE THREAD

**Issue by Licen-it** [Jaliborc/Bagnon#1568]
This feature is basic in wow interface and it's the only useful feature of that interface. I'm wondering why is not present into this addon.

**Describe the solution you'd like**
As described above it's already present in the basic interface, so i guess the solution would be to have a similar button calling the same functionality (if not possible to reuse the basic interface button)

**Describe alternatives you've considered**
This feature is missing since ages and so far i was using a different addon just for the bank but always keeping Bagnon for anything else as i like it more.

**Comment by alexnaumovich** [comment]
![image](https://user-images.githubusercontent.com/40657589/206121581-615451f4-89e8-4967-9a43-87cf957774e4.png)

Isn't that exactly what you are looking for?

**Comment by Licen-it** [comment]
> ![image](https://user-images.githubusercontent.com/40657589/206121581-615451f4-89e8-4967-9a43-87cf957774e4.png)
> 
> Isn't that exactly what you are looking for?

yes....I feel so bad i didn't notice it. Closing as not required.
