### ISSUE TITLE
right clicking "Key framing or disenchanting gear" gets Bagnon is blocked error

### ISSUE THREAD

**Issue by Bashercon** [Jaliborc/Bagnon#1573]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.0.11
 - Server patch: 10.0.11

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. i have read 

**Describe the bug**
When i am trying to Create keys for the restored obsidian key i get the blizzard error " <Bagnon> has been blocked from an action only available to the Blizzard UI” .
Also the same issue when i try and disenchant items in my bags . 

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
The key fame combines with the key fragments to form an obsidian key 
**Screenshots**

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the message with `ID: 1` (labelled 1/X). This is generally NOT the message that the window shows by default.

**Additional context**
![WoWScrnShot_120922_165227](https://user-images.githubusercontent.com/119981898/206801924-423e300b-2207-40c9-8223-335fa4fc96e8.jpg)
![WoWScrnShot_120922_165513](https://user-images.githubusercontent.com/119981898/206802172-dcee6ad7-b743-4ac9-b6c4-6d2739ab528a.jpg)

**Comment by Roneasaurus** [comment]
im also getting the Blocked error from trying ti use crafting Knowledge or any other item that needs to be used from the bag.



3x [ADDON_ACTION_FORBIDDEN] AddOn 'Bagnon' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@FrameXML/ContainerFrame.lua"]:1409: in function `ContainerFrameItemButton_OnClick'
[string "@FrameXML/ContainerFrame.lua"]:1461: in function <FrameXML/ContainerFrame.lua:1448>
[string "=[C]"]: ?
