### ISSUE TITLE
Unable to disenchant items with 10.0.11

### ISSUE THREAD

**Issue by Peregran** [Jaliborc/Bagnon#1574]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.0.11
 - Server patch: Retail 10.0.2

 **Have you read the changelog? (please don't waste our time)**
 Yes I read it

**Describe the bug**
When I try to disenchant an item I get a lua error with bugsack

**To Reproduce**
Steps to reproduce the behaviour:
1 Open your bag
2. Click on disenchant button on tools bar
3. Click on item in bag to disenchant

2x [ADDON_ACTION_FORBIDDEN] AddOn 'Bagnon' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@FrameXML/ContainerFrame.lua"]:1325: in function `ContainerFrameItemButton_OnClick'
[string "@FrameXML/ContainerFrame.lua"]:1461: in function <FrameXML/ContainerFrame.lua:1448>
[string "=[C]"]: ?

**Expected behaviour**
The item gets disenchanted

**Screenshots**
see above

**Comment by xZabuzax** [comment]
Got the same error here with the latest version of Bagnon, can't even use the Hearthstone from the bags, I need to place it in the action bars to be able to use it.

**Comment by Hammerpass** [comment]
wth  same error here

**Comment by ChrisCoxArt** [comment]
Same here, but it appears to be a known Blizzard bug -- happens even without addons, and the Blizzard code just blames random addons.
But why did the Bagnon version change the behavior of the bug in the Blizzard UI code?
And why the @%#$W$% isn't Blizzard fixing their code?
