### ISSUE TITLE
unable to interact with consumables in bag

### ISSUE THREAD

**Issue by Suddenly117** [Jaliborc/Bagnon#1575]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.0.11
 - Server patch: 10.0.2.46924

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. Yes, read

**Describe the bug**
With the newest update, attempted to learn a knowledge point item, immediately got "Bagnon has been blocked from an action only available to the Blizzard UI." Continued upon reload, only with consumable items (potion, knowledge point item). Solved by reverting back to 10.0.10
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to update addon to 10.0.11
2. Open bags
3. click on potion
5. Click on Alchemy KP item
6. See error
7. 
**Expected behaviour**
to drink the potion or to learn knowledge points 

**Screenshots**

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the message with `ID: 1` (labelled 1/X). This is generally NOT the message that the window shows by default.
No message appeared 

**Additional context**

**Comment by ludicritz** [comment]
Have this same issue since installing the update.

**Comment by huastekotester** [comment]
I have the same issue right after i updated to this version. I had to go back and install version Bagnon-10.0.10 for WoW-10.0.2.zip using Curseforge to be able to consume the skinning skill points i just collected

**Comment by alexnaumovich** [comment]
![image](https://user-images.githubusercontent.com/40657589/206819287-c21ed8cb-da61-4d79-9bb5-891cdcf10735.png)

Any right-click action on a consumable item causes this error. Food, snowball, healthstone, etc.

**Comment by chengyi-wu** [comment]
I have the same issue, resolved by reverting to 10.0.11

**Comment by tfmonk** [comment]
same issue for me ca't disenchant or open containers

**Comment by robertjamesftw** [comment]
Same issue. On attempting to eat something, received error:

```
Message: [ADDON_ACTION_FORBIDDEN] AddOn 'Bagnon' tried to call the protected function 'UNKNOWN()'.
Time: Fri Dec  9 19:00:26 2022
Count: 1
Stack: [ADDON_ACTION_FORBIDDEN] AddOn 'Bagnon' tried to call the protected function 'UNKNOWN()'.
[string "@Interface/FrameXML/ContainerFrame.lua"]:1409: in function `ContainerFrameItemButton_OnClick'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1461: in function <Interface/FrameXML/ContainerFrame.lua:1448>
[string "=[C]"]: ?

Locals: <none>
```

**Comment by Dmeister406** [comment]
> ![image](https://user-images.githubusercontent.com/40657589/206819287-c21ed8cb-da61-4d79-9bb5-891cdcf10735.png)
> 
> Any right-click action on a consumable item causes this error. Food, snowball, healthstone, etc.

Same issue here.

**Comment by RavenDT** [comment]
> Same issue. On attempting to eat something, received error:
> 
> ```
> Message: [ADDON_ACTION_FORBIDDEN] AddOn 'Bagnon' tried to call the protected function 'UNKNOWN()'.
> Time: Fri Dec  9 19:00:26 2022
> Count: 1
> Stack: [ADDON_ACTION_FORBIDDEN] AddOn 'Bagnon' tried to call the protected function 'UNKNOWN()'.
> [string "@Interface/FrameXML/ContainerFrame.lua"]:1409: in function `ContainerFrameItemButton_OnClick'
> [string "@Interface/FrameXML/ContainerFrame.lua"]:1461: in function <Interface/FrameXML/ContainerFrame.lua:1448>
> [string "=[C]"]: ?
> 
> Locals: <none>
> ```
> 
> Reverted to 10.0.10

Same error, and reverting to 10.0.10 fixed the issue for me.

**Comment by Larzous** [comment]
Can't interact with this item either:
![image](https://user-images.githubusercontent.com/68357365/206828960-08160199-9cc2-480e-a4f8-babc7a9509b1.png)

**Comment by Vilogity** [comment]
Same Error since update 10.0.11
Also cant use Homestone......

**Comment by layzsmurf** [comment]
Culprit seems to be Blizzard UseContainerItem() -> #1579

**Comment by briantorluemke** [comment]
Same issue still

**Comment by KiwisKiwi** [comment]
Issue is back
