### ISSUE TITLE
Usage: local data = C_TooltipInfo.GetBagItem(bagIndex, slotIndex)

### ISSUE THREAD

**Issue by Thrumbar** [Jaliborc/Bagnon#1584]
Running Software (issues missing this information will be deleted):

    Addon version: Bagnon_BoE-2.0.52 Release
    Server patch: 10.0.2.56924

Have you read the changelog? (please don't waste our time)
Yes

Describe the bug
Logged in , open bags and recieved bug

To Reproduce
Steps to reproduce the behaviour:

    Log on
    Bug

Expected behaviour
Logon without error

Screenshots

Error Logs
40x Usage: local data = C_TooltipInfo.GetBagItem(bagIndex, slotIndex)
[string "=[C]"]: in function `GetBagItem'
[string "@Bagnon_ItemLevel/main.lua"]:92: in function `update'
[string "@Bagnon_BoE/dispatcher.lua"]:76: in function <Bagnon_BoE/dispatcher.lua:74>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Update'
[string "@BagBrother/addons/core/classes/item.lua"]:128: in function <...rfaceBagBrother/addons/core/classes/item.lua:123>
[string "=[C]"]: in function `Show'
[string "@BagBrother/addons/core/classes/item.lua"]:42: in function <...rfaceBagBrother/addons/core/classes/item.lua:34>
[string "=(tail call)"]: ?
[string "@BagBrother/addons/core/classes/itemGroup.lua"]:124: in function `func'
[string "@BagBrother/libs/MutexDelay-1.0-2/MutexDelay-1.0.lua"]:36: in function <...ns/BagBrother/libs/MutexDelay-1.0/MutexDelay-1.0.lua:30>

Locals:
(*temporary) = "Usage: local data = C_TooltipInfo.GetBagItem(bagIndex, slotIndex)"

Additional context

**Comment by zdhar** [comment]
its not bagnon himself but bagnon item level

**Comment by Fleymour** [comment]
> its not bagnon himself but bagnon item level

ill dont have bagnon item level installed and i got the same error.

**Comment by Jaliborc** [comment]
Outdated plugins
