### ISSUE TITLE
10.0.10 work but 10.0.11 is causing  blocked by blizzard called a protected function popup

### ISSUE THREAD

**Issue by I-AM-T3X** [Jaliborc/Bagnon#1585]
**Running Software (issues missing this information will be deleted):**
 - Addon version: Bagnon-10.0.11 for WoW-10.0.2
 - Server patch:  version 10.0.2.46924

 **Have you read the changelog? (please don't waste our time)**
 Mark if read.
 Yes

**Describe the bug**
Some code between 10.0.10 & 10.0.11 has changed and is causing the blocked by blizzard protected function popup

this is what BugGrabber grabbed when when i was trying to click item in my bag on 10.0.11
this does not happen in 10.0.10
⬇
below in **Error Logs**

**To Reproduce**
 click any use item in the bag while on 10.0.11

**Expected behaviour**
click the item and use it

**Screenshots**

**Error Logs**
[ADDON_ACTION_FORBIDDEN] AddOn 'Bagnon' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@FrameXML/ContainerFrame.lua"]:1409: in function `ContainerFrameItemButton_OnClick'
[string "@FrameXML/ContainerFrame.lua"]:1461: in function <FrameXML/ContainerFrame.lua:1448>
[string "=[C]"]: ?.

**Comment by RedRoach** [comment]
Getting two errors I think:

1x [ADDON_ACTION_FORBIDDEN] AddOn 'Bagnon' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@FrameXML/ContainerFrame.lua"]:1409: in function `ContainerFrameItemButton_OnClick'
[string "@FrameXML/ContainerFrame.lua"]:1461: in function <FrameXML/ContainerFrame.lua:1448>
[string "=[C]"]: ?

And:

 60x Usage: local data = C_TooltipInfo.GetBagItem(bagIndex, slotIndex)
[string "=[C]"]: in function `GetBagItem'
[string "@Bagnon_ItemLevel/main.lua"]:92: in function `update'
[string "@Bagnon_ItemLevel/dispatcher.lua"]:76: in function <Bagnon_ItemLevel/dispatcher.lua:74>
[string "=[C]"]: in function `Update'
[string "@BagBrother/addons/core/classes/item.lua"]:128: in function <...rfaceBagBrother/addons/core/classes/item.lua:123>
[string "=[C]"]: in function `Show'
[string "@BagBrother/addons/core/classes/item.lua"]:42: in function <...rfaceBagBrother/addons/core/classes/item.lua:34>
[string "=(tail call)"]: ?
[string "@BagBrother/addons/core/classes/itemGroup.lua"]:124: in function `func'
[string "@BagBrother/libs/MutexDelay-1.0-2/MutexDelay-1.0.lua"]:36: in function <...ns/BagBrother/libs/MutexDelay-1.0/MutexDelay-1.0.lua:30>

Locals:
(*temporary) = "Usage: local data = C_TooltipInfo.GetBagItem(bagIndex, slotIndex)"

**Comment by Silicon14asp** [comment]
When using weight stone or sharping stones, will trigger this error from the bags in the 10.0.11, like others I have downgraded to 10.0.10 to resolve this issue.

**Comment by Azerox050** [comment]
Yep having the same.

**Comment by JasperKazai** [comment]
Yeah, I'm completely unable to use quest items from my bags or disenchant items in my bags with this new update, even after reloading the UI several times. But it works fine when I downgrade to the older version.

**Comment by Hazno** [comment]
The same applies to using both the regular and Dalaran Hearthstone from my bags, if you need an easy way to reproduce this.

**Comment by ProfStevenFalken** [comment]
Also having this identical issue when trying to use any hearthstone or consumable recipe after the latest update.

**Comment by hein-are** [comment]
I'm having the same exact issue after updating the addon. Reloading UI or exiting and restarting the game does not fix the issue.

Issue happens whenever I click any usable item, like dragon manuscripts, hearthstones, food, quest items...

**Comment by Zortt** [comment]
yes when trying to learn something form the bag you get the pop up that it was blocked and to disable the addon    SAD TIMES I love this addon

**Comment by Dranni21312** [comment]
I can confirm issues when trying to use items in the bags with Bagnon on. Reverting to 10.0.10 works.

**Comment by layzsmurf** [comment]
the culprit seems to be a taint of the blizzard function see #1579

**Comment by rursache** [comment]
Same issue, almost any item i click on would trigger the blizzard interface error. Rolled back to 10.0.10

**Comment by Toenail1203** [comment]
i can create a shortcut by putting  an on-use item in a bar slot and then use it from there. obviously that is a PITA. the previous version did not cause this problem. long-time user and i do recall this happening from time to time with previous versions. not in a while though.

thanks for all the work you have put into this.

**Comment by Cleric670** [comment]
Latest version 10.0.0.12 fixes this issue.
