### ISSUE TITLE
WoW error when clicking new pet item (to add this to my pet list) in inventory

### ISSUE THREAD

**Issue by beckerde** [Jaliborc/Bagnon#1586]
Date: 2022-12-11 00:15:41
ID: 1
Error occured in: Global
Count: 1
Message: Usage: local containerInfo = C_Container.GetContainerItemInfo(containerIndex, slotIndex)
Debug:
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Bagnon_ItemInfo/modules/itembind.lua"]:92: update()
   [string "@Interface/AddOns/Bagnon_ItemInfo/dispatcher.lua"]:68:
      Interface/AddOns/Bagnon_ItemInfo/dispatcher.lua:66
   [string "=[C]"]: Update()
   [string "@Interface/AddOns/BagBrother/addons/core/classes/item.lua"]:128:
      ...rface/AddOns/BagBrother/addons/core/classes/item.lua:123
   [string "=[C]"]: Show()
   [string "@Interface/AddOns/BagBrother/addons/core/classes/item.lua"]:42:
      ...rface/AddOns/BagBrother/addons/core/classes/item.lua:34
   [string "=(tail call)"]: ?
   [string "@Interface/AddOns/BagBrother/addons/core/classes/itemGroup.lua"]:124: func()
   [string "@Interface/AddOns/BagBrother/libs/MutexDelay-1.0/MutexDelay-1.0.lua"]:36:
      ...ns/BagBrother/libs/MutexDelay-1.0/MutexDelay-1.0.lua:30
Locals:
(*temporary) = "Usage: local containerInfo = C_Container.GetContainerItemInfo(containerIndex, slotIndex)"

AddOns:
  Swatter, v<%version%> (<%codename%>)
  Auctioneer, v9.1.BETA.5.7 (OneMawTime)
  AuctioneerStatsOverTime, v9.1.BETA.5.7 (OneMawTime)
  AuctioneerUtilDealFinder, v9.1.BETA.5.7 (OneMawTime)
  AuctioneerUtilValuer, v9.1.BETA.5.7 (OneMawTime)
  BagBrother, v
  Bagnon, v10.0.11
  BagnonItemInfo, v2.0.45-Release
  DBMCore, v05da521
  DBMStatusBarTimers, v05da521
  DBMVPVEM, vfce23ce
  Details, v#Details.DF.Wrath.10334.147
  DetailsCompare2, v
  Enchantrix, v5.1.DEV.4632
  HandyNotes, vv1.6.13
  Informant, v<%version%> (<%codename%>)
  Pawn, v2.7.13
  RareScanner, v10.0.2.7
  SlideBar, v<%version%> (<%codename%>)
  Stubby, v9.1.BETA.5.7 (OneMawTime)
  Titan, v6.00.09.100002
  TitanBag, v6.00.09.100002
  TitanClock, v6.00.09.100002
  TitanGold, v6.00.09.100002
  TitanLocation, v6.00.09.100002
  TitanLootType, v6.00.09.100002
  TitanPerformance, v6.00.09.100002
  TitanRepair, v6.00.09.100002
  TitanVolume, v6.00.09.100002
  TitanXP, v6.00.09.100002
  BlizRuntimeLib_deDE v10.0.2.100002 <none>
  (ck=3e7)

Date: 2022-12-11 00:14:03
ID: -1
Error occured in: AddOn: Bagnon
Count: 5
Message: Error: AddOn Bagnon attempted to call a forbidden function (UNKNOWN()) from a tainted execution path.
Debug:
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: UseContainerItem()
   [string "@Interface/FrameXML/ContainerFrame.lua"]:1409: ContainerFrameItemButton_OnClick()
   [string "@Interface/FrameXML/ContainerFrame.lua"]:1461:
      Interface/FrameXML/ContainerFrame.lua:1448
   [string "=[C]"]: ?
Locals:
None
AddOns:
  Swatter, v<%version%> (<%codename%>)
  Auctioneer, v9.1.BETA.5.7 (OneMawTime)
  AuctioneerStatsOverTime, v9.1.BETA.5.7 (OneMawTime)
  AuctioneerUtilDealFinder, v9.1.BETA.5.7 (OneMawTime)
  AuctioneerUtilValuer, v9.1.BETA.5.7 (OneMawTime)
  BagBrother, v
  Bagnon, v10.0.11
  BagnonItemInfo, v2.0.45-Release
  DBMCore, v05da521
  DBMStatusBarTimers, v05da521
  DBMVPVEM, vfce23ce
  Details, v#Details.DF.Wrath.10334.147
  DetailsCompare2, v
  Enchantrix, v5.1.DEV.4632
  HandyNotes, vv1.6.13
  Informant, v<%version%> (<%codename%>)
  Pawn, v2.7.13
  RareScanner, v10.0.2.7
  SlideBar, v<%version%> (<%codename%>)
  Stubby, v9.1.BETA.5.7 (OneMawTime)
  Titan, v6.00.09.100002
  TitanBag, v6.00.09.100002
  TitanClock, v6.00.09.100002
  TitanGold, v6.00.09.100002
  TitanLocation, v6.00.09.100002
  TitanLootType, v6.00.09.100002
  TitanPerformance, v6.00.09.100002
  TitanRepair, v6.00.09.100002
  TitanVolume, v6.00.09.100002
  TitanXP, v6.00.09.100002
  BlizRuntimeLib_deDE v10.0.2.100002 <none>
  (ck=3e7)

**Comment by beckerde** [comment]
Date: 2022-12-11 00:24:05
ID: 2
Error occured in: Global
Count: 54
Message: Usage: local data = C_TooltipInfo.GetBagItem(bagIndex, slotIndex)
Debug:
   [string "=[C]"]: ?()
   [string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:250:
      Interface/SharedXML/Tooltip/TooltipDataHandler.lua:240
   [string "=[C]"]: securecallfunction()
   [string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:237:
      Interface/SharedXML/Tooltip/TooltipDataHandler.lua:236
   [string "=(tail call)"]: ?
   [string "@Interface/AddOns/Bagnon_ItemInfo/modules/uncollected.lua"]:58: update()
   [string "@Interface/AddOns/Bagnon_ItemInfo/dispatcher.lua"]:68:
      Interface/AddOns/Bagnon_ItemInfo/dispatcher.lua:66
   [string "=[C]"]: Update()
   [string "@Interface/AddOns/BagBrother/addons/core/classes/item.lua"]:128:
      ...rface/AddOns/BagBrother/addons/core/classes/item.lua:123
   [string "=[C]"]: Show()
   [string "@Interface/AddOns/BagBrother/addons/core/classes/item.lua"]:42:
      ...rface/AddOns/BagBrother/addons/core/classes/item.lua:34
   [string "=(tail call)"]: ?
   [string "@Interface/AddOns/BagBrother/addons/core/classes/itemGroup.lua"]:124: func()
   [string "@Interface/AddOns/BagBrother/libs/MutexDelay-1.0/MutexDelay-1.0.lua"]:36:
      ...ns/BagBrother/libs/MutexDelay-1.0/MutexDelay-1.0.lua:30
Locals:
(*temporary) = "Usage: local data = C_TooltipInfo.GetBagItem(bagIndex, slotIndex)"

AddOns:
  Swatter, v<%version%> (<%codename%>)
  Auctioneer, v9.1.BETA.5.7 (OneMawTime)
  AuctioneerStatsOverTime, v9.1.BETA.5.7 (OneMawTime)
  AuctioneerUtilDealFinder, v9.1.BETA.5.7 (OneMawTime)
  AuctioneerUtilValuer, v9.1.BETA.5.7 (OneMawTime)
  BagBrother, v
  Bagnon, v10.0.11
  BagnonItemInfo, v2.0.45-Release
  DBMCore, v05da521
  DBMStatusBarTimers, v05da521
  DBMVPVEM, vfce23ce
  Details, v#Details.DF.Wrath.10334.147
  DetailsCompare2, v
  Enchantrix, v5.1.DEV.4632
  Informant, v<%version%> (<%codename%>)
  Pawn, v2.7.13
  RareScanner, v10.0.2.8
  SlideBar, v<%version%> (<%codename%>)
  Stubby, v9.1.BETA.5.7 (OneMawTime)
  Titan, v6.00.09.100002
  TitanBag, v6.00.09.100002
  TitanClock, v6.00.09.100002
  TitanGold, v6.00.09.100002
  TitanLocation, v6.00.09.100002
  TitanLootType, v6.00.09.100002
  TitanPerformance, v6.00.09.100002
  TitanRepair, v6.00.09.100002
  TitanVolume, v6.00.09.100002
  TitanXP, v6.00.09.100002
  BlizRuntimeLib_deDE v10.0.2.100002 <none>
  (ck=3d0)

**Comment by layzsmurf** [comment]
likely #1579

**Comment by Ghostamoose** [comment]
Update to the newest version of Bagnon. Should be fixed.
