### ISSUE TITLE
10.0.12 forbidden action...when NOT using Frame for inventory

### ISSUE THREAD

**Issue by Cald** [Jaliborc/Bagnon#1587]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.0.12
 - Server patch: 10.0.2 (46924)

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. **YES**

**Describe the bug**
1. Cannot click-use items from bags

**To Reproduce**
1. Go to Bag
2. Click on Hearthstone (right-click to use)
3. See error

**Expected behavior**
Expected to start casting hearth

**Screenshots**
![bagnon_10_0_12_error](https://user-images.githubusercontent.com/120345731/206939126-44e71693-165b-42f5-9ced-12eacab4a9fa.png)

**Error Logs**
1x [ADDON_ACTION_FORBIDDEN] AddOn 'Bagnon' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@FrameXML/ContainerFrame.lua"]:1409: in function <FrameXML/ContainerFrame.lua:1318>
[string "=[C]"]: in function `ContainerFrameItemButton_OnClick'
[string "@FrameXML/ContainerFrame.lua"]:1461: in function <FrameXML/ContainerFrame.lua:1448>

**Additional context**
tried to downgrade to 10.0.11, 10.0.10 all have the same issue.  I have disabled ALL other add-ons and can confirm same behavior.

I have found that if I "Enable Frame" for inventory it works.  But if I do not "enable frame" it errors.

**Comment by vamborala** [comment]
> **Additional context** tried to downgrade to 10.0.11, 10.0.10 all have the same issue. I have disabled ALL other add-ons and can confirm same behavior.

I had this problem when I upgraded to 11 but when downgraded to 10 solved this problem. Maybe your installation is messed up somewhere else, i recommend you delete the addon at all and reinstall it mainly because version 12 solved it.

**Comment by Cald** [comment]
Thanks for the advice, I have tried that.  I have found that if I "Enable Frame" for inventory it works.  But if I do not "enable frame" it errors.

**Comment by Ghostamoose** [comment]
> Thanks for the advice, I have tried that. I have found that if I "Enable Frame" for inventory it works. But if I do not "enable frame" it errors.

This happens because the default Blizzard frame breaks itself (yeah, thanks Blizzard.) - The way around that bug is to have Bagnon create it's own entire bag frame so it doesn't interact with the Blizzard frame that breaks the inventory contents.

So until Blizzard fixes the taint issues with bags, you're going to have to either use **no bag addon** or Bagnon with the custom frame enabled.
