### ISSUE TITLE
Guilds and connected realms

### ISSUE THREAD

**Issue by davidricheson1** [Jaliborc/Bagnon#1609]
version 8.1.9
The issue looks to be in bagbrother.
Setup:
given 2 toons in the same guild (GuildA), but they are on different servers (RealmC and RealmD) that are connected.

Issue:
The tool tip shows the guild twice. once from RealmC and once from RealmD. 

Analysis:
Looking at ..\SavedVariables\BagBrother.lua I see the guild data is saved under the toon's realm. in the above example twice.

Possible fix:
A quick fix would be to save the Guild data under REALMS[1] versus the realm the player is on. 

LibItemCache-2.0.lua does pull in connected realms:
 local FindRealms = function()
	if not REALM then
		PLAYER, REALM = UnitFullName('player')
		FACTION = UnitFactionGroup('player')
		REALMS = GetAutoCompleteRealms()

		if not REALMS or #REALMS == 0 then
			REALMS = {REALM}
		end
	end
end

**Comment by Jaliborc** [comment]
Fixed in alpha branch
