### ISSUE TITLE
Tooltips not loading for items in bags

### ISSUE THREAD

**Issue by greggie87** [Jaliborc/Bagnon#1615]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.0.15
 - Server patch: 3.4.1.47612

**Describe the bug**
When hovering the cursor over items in your bags, a tooltip usually shows with the item name atc. This is not working after today's patch in wotlk.

**Error Logs**
Date: 2023-01-18 10:42:46
ID: 24
Error occured in: Global
Count: 1
Message: ...AddOns/Auc-Advanced/Libs/LibExtraTip/LibExtraTip.lua line 1120:
   attempt to call global 'GetContainerItemInfo' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: GetContainerItemInfo()
   [string "@Interface/AddOns/Auc-Advanced/Libs/LibExtraTip/LibExtraTip.lua"]:1120: hook()
   [string "@Interface/AddOns/Auc-Advanced/Libs/LibExtraTip/LibExtraTip.lua"]:432:
      ...AddOns/Auc-Advanced/Libs/LibExtraTip/LibExtraTip.lua:428
   [string "@Interface/AddOns/TradeSkillMaster/LibTSM/Service/ItemTooltipClasses/Wrapper.lua"]:103:
      ...Master/LibTSM/Service/ItemTooltipClasses/Wrapper.lua:101
   [string "=[C]"]: ?
   [string "=[C]"]: SetBagItem()
   [string "@Interface/FrameXML/ContainerFrame_Shared.lua"]:1362: ContainerFrameItemButton_OnEnter()
   [string "@Interface/AddOns/BagBrother/addons/core/classes/item.lua"]:358: ShowTooltip()
   [string "@Interface/AddOns/BagBrother/addons/core/classes/item.lua"]:185:
      ...rface/AddOns/BagBrother/addons/core/classes/item.lua:181
Locals:
(*temporary) = true
(*temporary) = <function> defined =[C]:-1

**Comment by evildroid78** [comment]
My bagnon dont work even,when i open bags i see standart blizzard bags

**Comment by Firehex12** [comment]
Yeah, it's bug for everyone, need to wait fix

**Comment by ssateneth** [comment]
Your tooltip issue is not a problem with bagnon. It's a problem with libextratooltip, a library part of Auctioneer. Disable auctioneer entirely including libextratip if you see it in your addon list and your tooltips will work again

**Comment by kongkaal** [comment]
I needed to disable Informant too before I got my tooltips back
