### ISSUE TITLE
Addon not working in classic since 9.2.2 properly.

### ISSUE THREAD

**Issue by RasmusSwahn** [Jaliborc/Bagnon#1621]
- Addon version: 10.0.15 for Wow-3.4.0
 - Server patch: 3.4.1

Read through changelogs since 9.2.2 (version i was running on previously that wasn't broken for me but new 3.4.1 broke that)

**Describe the bug**
Ever since 9.2.2 Bagnon has been broken, features that don't work: Cannot access banktab from outside bank anymore, the button just doesn't exist where it used to in 9.2.2, the currency feature implemented is non-existent, moving items in bags causes them to not update until bags are closed and opened again.

**To Reproduce**
Steps to reproduce the behaviour:
Literally just downloaded the addon, doing it through curse-app currently, but tried manually removing and downloading through website aswell. Tried troubleshooting, and from what i've gathered its not being caused by other addons, only running Bagnon i get the same result, a little unsure if this is something gathered elsewhere.

**Expected behaviour**
Expecting it to work as it did for me running 9.2.2, with added access to new developed features such as currency-managing etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/99730435/213388110-44f546e6-f159-456b-bff1-707651d6b52f.png)
Edit: marked section is where bank-button usually is, have moved around a bunch of items as you can tell by the greyed out icons.

**Error Logs**
No error logs are created, at any point during playing or anything sadly.

**Additional context**
as previously mentioned, 9.2.2 was the latest version i tried running that worked, but with ulduarpatch 3.4.1 that broke completely, so installing latest version i was hoping things would be working, but sadly not.

**Comment by joaomcarlos** [comment]
I have the exact same problem

**Comment by jp1995** [comment]
reproduced

**Comment by joaomcarlos** [comment]
On Discord guildies sharing this: https://github.com/Jaliborc/Bagnon/issues/1620#issuecomment-1396327530

**Comment by RasmusSwahn** [comment]
It fixed the items updating when being moved, does not fix bank-button no longer appearing and currency not working still.

**Comment by joaomcarlos** [comment]
Addon was updated 20mins ago: https://www.curseforge.com/wow/addons/bagnon/files

**Comment by RasmusSwahn** [comment]
Update: apparently after 9.2.2 they removed this button, and rightclicking up here is the new way to display bank, terrible UX design, and changelogs show nothing past 9.2.3 moving forward about it, closing issue, please add  the button to the bottom left, its one of the key features of bagnon and not having it easy access even with new currency tracker is horrible design.
![image](https://user-images.githubusercontent.com/99730435/213517906-a95eb957-0e9e-408d-b2aa-8ba44e0dbfab.png)
