### ISSUE TITLE
Icon brightness for on-use items does not reset after cooldown expiration.

### ISSUE THREAD

**Issue by btnmasher** [Jaliborc/Bagnon#1626]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.0.16
 - Server patch: Version 3.4.1 (47612) Wrath Classic

 **Have you read the changelog? (please don't waste our time)**
Yes

**Describe the bug**
When using an on-use item from the bags, the item icon and all other items which share a GCD with that item will darken and display the cooldown wiper overlay. At the completion of the cooldown, the icon(s) do not return back to its full brightness until the bag is closed and reopened. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Use an item within the bags (food/water, potion, bandage, etc).
2. Observe the icon(s) being darker, and the cooldown ticking.
3. Observe the icon(s) remaining darker after the cooldown has completed.
4. Close and re-open bags to observe icon is back to normal brightness.

**Expected behaviour**
After using an item and its cooldown completing, the icon should return to its default state.

**Screenshots**
After using the item (post-cooldown completion):
![](https://i.imgur.com/SbZo73E.png)

Reopening the bag (restores icon brightness to original):
![](https://i.imgur.com/sPVfzhX.png)

**Error Logs**
```
1x Select/utils/utils.lua:93: attempt to call global 'GetContainerNumSlots' (a nil value)
[string "@Select/utils/utils.lua"]:93: in function `GetContainerNumSlots'
[string "@Select/data/cache.lua"]:265: in function `func'
[string "@Select/utils/timer.lua"]:48: in function <Select/utils/timer.lua:40>

Locals:
self = <table> {
 SetAttributes = <function> defined @Select/utils/utils.lua:49
 RunForEach = <function> defined @Select/utils/utils.lua:73
 GetEscapedText = <function> defined @Select/utils/utils.lua:36
 RegisterForClicks = <function> defined @Select/utils/utils.lua:123
 CopyAttributes = <function> defined @Select/utils/utils.lua:65
 GetContainerItemQuestInfo = <function> defined @Select/utils/utils.lua:113
 GetContainerItemLink = <function> defined @Select/utils/utils.lua:105
 GetContainerNumSlots = <function> defined @Select/utils/utils.lua:89
 GetContainerItemID = <function> defined @Select/utils/utils.lua:97
 GetTableSize = <function> defined @Select/utils/utils.lua:79
 GetAttributes = <function> defined @Select/utils/utils.lua:57
 GetCaseInsensitive = <function> defined @Select/utils/utils.lua:27
 Debug = <function> defined @Select/utils/utils.lua:42
}
bag = 0
(*temporary) = nil
(*temporary) = 0
(*temporary) = "attempt to call global 'GetContainerNumSlots' (a nil value)"
isModernClient = false
```

**Additional context**
This was introduced with version 10.0.x series of updates, and was not present in the 9.x series prior. I avoided this issue by staying on the 9.x version as long as possible until the Ulduar patch arrived which necessitated updating.

**Comment by danschne** [comment]
+1
