### ISSUE TITLE
Retail: Bag slots not updating  as is should

### ISSUE THREAD

**Issue by Pecanz72** [Jaliborc/Bagnon#1637]
This is for Retail:  After current WOW patch 10.0.5 when you are moving items from one slot to another in the bag sit doesn't update the slots.  So if I try moving anything in my bag or bank bags the slots just do not update and looks like I never moved it.  You have to close out the bags and reopen to get it to update.  

Unfortunately this is a inconvenience  and forced me to stop using Bagnon until it is resolved.

**Comment by sliceandice** [comment]
Was just going to post about the same thing happening. So for now am using baudbag

**Comment by Pecanz72** [comment]
yeah I thought about that and made sure I was on the correct version still doing it even without any other addon active.  I will wait it out and just disable till it works again.

**Comment by sliceandice** [comment]
One other thing you can try if you havent yet is go to your WTF folder and click on account then your account folder what ever you named it. Then click on the saved variables folder and delete all files that come with bagnon. some times those files stop working right and a fresh install solves the issue. Have had it happen to me a few times with addons. Hope that works if not then guess have to wait for an update.

**Comment by Pecanz72** [comment]
it started working again I did not have to do anything to make it wor,  but thinking is was a WOW issue and not an issue with the add-on.  thanks for the information and will try that next time, if needed.  :)
