### ISSUE TITLE
Unable to buy new guild bank tabs with Bagnon Guild Bank loaded

### ISSUE THREAD

**Issue by Hondu128** [Jaliborc/Bagnon#1651]
**Running Software (issues missing this information will be deleted):**
 - Addon version: Bagnon Guild Bank - Bagnon-10.0.16 for WoW-3.4.1 (fully patched to current version)
 - Server patch: [WOW WOTLK - 3.4.1.48340] (fully patched current version)

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. X-I have read it!

**Describe the bug**
When using Bagnon Guild Bank Add-On, there is no interface to buy a new guild bank tab

**To Reproduce**
<<<obvious>>> - see screenshots as needed.

**Expected behaviour**
Buy new guild bank tab available for use as per native functionality

**Screenshots**
Not working:
![image](https://user-images.githubusercontent.com/68867741/223514737-07e213ef-2a8d-45da-a246-f2ecea08c8ce.png)
Native view:
![image](https://user-images.githubusercontent.com/68867741/223515496-36a35a3a-0c42-4a4a-af7d-553759180d2f.png)

**Comment by bbuecken** [comment]
Also I cannot change the icon or the guild bank properties
