### ISSUE TITLE
Doesn't work since 10.1 update just shows blank screen

### ISSUE THREAD

**Issue by PirateKain** [Jaliborc/Bagnon#1661]
**Running Software (issues missing this information will be deleted):**
 - Addon version: v10.0.16
 - Server patch: [e.g. Build 8.0.1.27178] - 10.1.0

 **Have you read the changelog? (please don't waste our time)**
 Yes

**Describe the bug**
When I open the bags via Bagnon it comes up with just an outline of the whole bag window but it is all blank except I can see the individual bags and other options on the top and bottom of bag window, but the item slots are all blank. Not even the item slots boxes are visible. Also no items in the bag can be seen.

**To Reproduce**
Steps to reproduce the behaviour:
Just have to open the bags no matter how you open them.

**Expected behaviour**
To see all item slots and all the items within my bags.

**Screenshots**

**Error Logs**
Date: 2023-05-03 05:06:27
ID: 3
Error occured in: Global
Count: 1
Message: ...erface/AddOns/BagBrother/libs/ItemSearch-1.3/API.lua line 53:
   attempt to index field 'args' (a nil value)
Debug:
   [string "=[C]"]: ?
   [string "@Interface/AddOns/BagBrother/libs/ItemSearch-1.3/API.lua"]:53:
      ...erface/AddOns/BagBrother/libs/ItemSearch-1.3/API.lua:50
   [string "@Interface/AddOns/BagBrother/libs/ItemSearch-1.3/API.lua"]:58: IsUnusable()
   [string "@Interface/AddOns/BagBrother/addons/core/classes/item.lua"]:243: UpdateBorder()
   [string "@Interface/AddOns/BagBrother/addons/core/classes/item.lua"]:206:
      ...rface/AddOns/BagBrother/addons/core/classes/item.lua:199
   [string "=[C]"]: Update()
   [string "@Interface/AddOns/BagBrother/addons/core/classes/item.lua"]:134:
      ...rface/AddOns/BagBrother/addons/core/classes/item.lua:129
   [string "=[C]"]: Show()
   [string "@Interface/AddOns/BagBrother/addons/core/classes/item.lua"]:47:
      ...rface/AddOns/BagBrother/addons/core/classes/item.lua:39
   [string "=(tail call)"]: ?
   [string "@Interface/AddOns/BagBrother/addons/core/classes/itemGroup.lua"]:124: func()
   [string "@Interface/AddOns/PetTracker/libs/MutexDelay-1.0/MutexDelay-1.0.lua"]:36:
      ...ns/PetTracker/libs/MutexDelay-1.0/MutexDelay-1.0.lua:30
Locals:
(*temporary) = <function> defined =[C]:-1

**Comment by Mekilya** [comment]
Having same issue.. Log in opened bags and all black screen. Reloaded and a few items showed up but it doesn't last and few items that do show up having issue vendoring and learning etc.

**Comment by Dahustler** [comment]
Same/similar issue for me. The first time you open your bag it seems to work, but it kinda doesnt. Whenever you open your bags again it looks like this 
![image](https://user-images.githubusercontent.com/72993848/235917667-68ccb7b1-ef8d-4dd0-96ac-725078f66f21.png)

**Comment by bahahamut** [comment]
https://github.com/Jaliborc/Bagnon/issues/1660

apparently some kind of workaround here.

**Comment by Arunn2287** [comment]
quick fix
![image](https://user-images.githubusercontent.com/73995869/235975702-1c95fcb2-1ae2-417f-abf3-e16fb0c94998.png)
World of Warcraft\_retail_\Interface\AddOns\BagBrother\addons\core\classes\item.lua

This disable red color for border

**Comment by The-Sickness** [comment]
Replace line 53 with this:

function Lib:IsUnusable(id)
    if Unfit:IsItemUnusable(id) then
        return true
    elseif Lib.Unusable[id] == nil and IsEquippableItem(id) then
        Lib.Unusable[id] = (function()
            local lines = C.TooltipInfo.GetItemByID(id).lines
            for i = #lines-1, 5, -1 do
                if lines[i].args ~= nil then -- add this check
                    local class = lines[i].args[2].stringVal:match(L.CLASS_REQUIREMENT)
                    if class then
                        return not class:find(L.PLAYER_CLASS)
                    end
                end
            end
        end)() or false
    end
    return Lib.Unusable[id]
end

**Comment by moldytoastaz** [comment]
same issues -- 
![BAGNON SS 2 3MAY2023](https://user-images.githubusercontent.com/132492106/236004191-fbc24c1d-ff0a-43f4-8d34-c31a28d53120.png)
![BAGNON SS 3 3MAY2023](https://user-images.githubusercontent.com/132492106/236004196-1c69e9e3-818c-45fa-a52a-fd9f1d12a2a0.png)
![BAGNON SS 3MAY2023](https://user-images.githubusercontent.com/132492106/236004199-8f1aacbe-87cf-4d96-b341-2f8369017076.png)

**Comment by bubfeeld** [comment]
> Replace line 53 with this:
> 
> function Lib:IsUnusable(id) if Unfit:IsItemUnusable(id) then return true elseif Lib.Unusable[id] == nil and IsEquippableItem(id) then Lib.Unusable[id] = (function() local lines = C.TooltipInfo.GetItemByID(id).lines for i = #lines-1, 5, -1 do if lines[i].args ~= nil then -- add this check local class = lines[i].args[2].stringVal:match(L.CLASS_REQUIREMENT) if class then return not class:find(L.PLAYER_CLASS) end end end end)() or false end return Lib.Unusable[id] end

In what .lua file?

**Comment by Thr33nP1nK** [comment]
> > Replace line 53 with this:
> > function Lib:IsUnusable(id) if Unfit:IsItemUnusable(id) then return true elseif Lib.Unusable[id] == nil and IsEquippableItem(id) then Lib.Unusable[id] = (function() local lines = C.TooltipInfo.GetItemByID(id).lines for i = #lines-1, 5, -1 do if lines[i].args ~= nil then -- add this check local class = lines[i].args[2].stringVal:match(L.CLASS_REQUIREMENT) if class then return not class:find(L.PLAYER_CLASS) end end end end)() or false end return Lib.Unusable[id] end
> 
> In what .lua file?

This is the file you want to put  that in "BagBrother\libs\ItemSearch-1.3\API.lua"

**Comment by Yllelder** [comment]
Another option is to change the API.lua file to [the new one](https://raw.githubusercontent.com/Jaliborc/ItemSearch-1.3/master/API.lua), updated a few hours ago. With that it works again.

_BagBrother\libs\ItemSearch-1.3\API.lua_

**Comment by Demonz-clouds** [comment]
? where do u open it in

**Comment by Demonz-clouds** [comment]
and what if it's not a folder?

**Comment by Demonz-clouds** [comment]
![Uploading IMG_20230503_163913541.jpg…]()
see

**Comment by Demonz-clouds** [comment]
![IMG_20230503_163913541](https://user-images.githubusercontent.com/132520650/236066524-84af6242-2648-487b-a08e-fc76f90d3b73.jpg)

**Comment by bubfeeld** [comment]
> ![IMG_20230503_163913541](https://user-images.githubusercontent.com/132520650/236066524-84af6242-2648-487b-a08e-fc76f90d3b73.jpg)

i had the same issue, reinstall the latest version of bagnon, you and I were missing the sub directories there.

**Comment by josemendiola** [comment]
> and what if it's not a folder? pls someone help me

You can open it with Windows Notepad. 1) Open NotePad 2) Drag and drop the file in NotePad window.

**Comment by bubfeeld** [comment]
> ? where do u open it in b/c i can only open it in windows word

i use https://www.wowinterface.com/downloads/info4989

it says its outdated, but it still works

**Comment by Demonz-clouds** [comment]
> > and what if it's not a folder? pls someone help me
> 
> You can open it with Windows Notepad. 1) Open NotePad 2) Drag and drop the file in NotePad window.

so i just open and drag the .aip

**Comment by Demonz-clouds** [comment]
@josemendiola what file?

**Comment by Demonz-clouds** [comment]
![IMG_20230503_175852018](https://user-images.githubusercontent.com/132520650/236076071-3b38adcd-63a8-406f-bd61-fd399f8bcc6b.jpg)

this is what i tooks like after playing for 10 mins

**Comment by josemendiola** [comment]
> @josemendiola what file?

BagBrother\libs\ItemSearch-1.3\API.lua and BagBrother\libs\ItemSearch-1.3\API.lua\Filters.lua

You need to apply this solution:
https://github.com/Jaliborc/Bagnon/issues/1660#issuecomment-1533354338

**Comment by Rezy942** [comment]
The only solution is to delete Bagnon and go support LiteBag or other similar solutions. The author of this addon is milking the donation button. Give that support somewhere else instead. Bagnon really is a buggy sh*t stain of an addon lately.

**Comment by DockieB** [comment]
Thanks! that seems to have fixed it.

**Comment by Siixes** [comment]
@Yllelder 's comment worked for me. Can now see items in bags appropriately!
