### ISSUE TITLE
Does not work on WotLK PTR. 

### ISSUE THREAD

**Issue by B4LSTAD** [Jaliborc/Bagnon#1664]
- Addon version: 10.0.15 and 10.0.16
 - Server patch: 3.4.2.49442

 **Have you read the changelog? (please don't waste our time)**
Yes

**Describe the bug**
Does not seem to interact with the game at all, likely due to significant updates to the client by blizzard.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download the PTR. 
2. Install Bagnon
3. Enable in addons
4. Press the keybind for ur bags
5. observe error

**Expected behaviour**
Expected to see all my bags nicely sorted into one big bag.

**Error Logs**

Message: [string "Interface/AddOns/BagBrother/libs/TaintLess/..."]:77: hooksecurefunc(): GetAttribute is not a function
Time: Fri May  5 13:09:40 2023
Count: 1
Stack: [string "Interface/AddOns/BagBrother/libs/TaintLess/..."]:77: hooksecurefunc(): GetAttribute is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "Interface/AddOns/BagBrother/libs/TaintLess/TaintLess.xml:<Scripts>"]:77: in main chunk

Message: Interface/AddOns/BagBrother/addons/core/core.lua:11: attempt to call global 'GetAddOnMetadata' (a nil value)
Time: Fri May  5 13:09:40 2023
Count: 1
Stack: Interface/AddOns/BagBrother/addons/core/core.lua:11: attempt to call global 'GetAddOnMetadata' (a nil value)
[string "@Interface/AddOns/BagBrother/addons/core/core.lua"]:11: in main chunk

Locals: ADDON = "Bagnon"
Addon = <table> {
 PickupItem = <function> defined @Interface/AddOns/BagBrother/libs/LibItemCache-2.0/LibItemCache-2.0.lua:280
 FrameTemplate = "BackdropTemplate"
 IsRetail = false
 GetOwnerID = <function> defined @Interface/AddOns/BagBrother/libs/LibItemCache-2.0/LibItemCache-2.0.lua:300
 UnregisterAllEvents = <function> defined @Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 NumBags = 4
 RestorePetLinkData = <function> defined @Interface/AddOns/BagBrother/libs/LibItemCache-2.0/LibItemCache-2.0.lua:388
 InBank = <function> defined @Interface/AddOns/BagBrother/libs/LibItemCache-2.0/LibItemCache-2.0.lua:397
 IsClassic = false
 RestoreItemData = <function> defined @Interface/AddOns/BagBrother/libs/LibItemCache-2.0/LibItemCache-2.0.lua:334
 Tag = "BAGNON_"
 IsBackpackBag = <function> defined @Interface/AddOns/BagBrother/libs/LibItemCache-2.0/LibItemCache-2.0.lua:416
 IsOwnerCached = <function> defined @Interface/AddOns/BagBrother/libs/LibItemCache-2.0/LibItemCache-2.0.lua:317
 IsBank = <function> defined @Interface/AddOns/BagBrother/libs/LibItemCache-2.0/LibItemCache-2.0.lua:424
 RegisterMessage = <function> defined @Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 IsBackpack = <function> defined @Interface/AddOns/BagBrother/libs/LibItemCache-2.0/LibItemCache-2.0.lua:412
 IsBagCached = <function> defined @Interface/AddOns/BagBrother/libs/LibItemCache-2.0/LibItemCache-2.0.lua:321
 GetItemID = <function> defined @Interface/AddOns/BagBrother/libs/LibItemCache-2.0/LibItemCache-2.0.lua:261
 IsReagents = <function> defined @Interface/AddOns/BagBrother/libs/LibItemCache-2.0/LibItemCache-2.0.lua:432
 IsBankBag = <function> defined @Interface/AddOns/BagBrother/libs/LibItemCache-2.0/LibItemCache-2.0.lua:428
 SendMessage = <function> defined @Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:49
 GetBagInfo = <function> defined @Interface/AddOns/BagBrother/libs/LibItemCache-2.0/LibItemCache-2.0.lua:166
 NewModule = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:68
 IsKeyring = <function> defined @Interface/AddOns/BagBrother/libs/LibItemCache-2.0/LibItemCache-2.0.lua:420
 UnregisterSignal = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:78
 GetOwnerAddress = <function> defined @Interface/AddOns/BagBrother/libs/LibItemCache-2.0/LibItemCache-2.0.lua:305
 GetItemInfo = <function> defined @Interface/AddOns/BagBrother/libs/LibItemCache-2.0/LibItemCache-2.0.lua:229
 SendSignal = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:82
 RegisterEvent = <function> defined @Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterAllMessages = <function> defined @Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 GetOwnerInfo = <function> defined @Interface/AddOns/BagBrother/libs/LibItemCache-2.0/LibItemCache-2.0.lua:95
 DeleteOwnerInfo = <function> defined @Interface/AddOns/BagBrother/libs/LibItemCache-2.0/LibItemCache-2.0.lua:122
 UnregisterMessage = <function> defined @Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 Slash = "bgn"
 Name = "Bagnon"
 IterateOwners = <function> defined @Interface/AddOns/BagBrother/libs/LibItemCache-2.0/LibItemCache-2.0.lua:135
 RegisterSignal = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:74
 InVault = <function> defined @Interface/AddOns/BagBrother/libs/LibItemCache-2.0/LibItem

Message: Interface/AddOns/TacoTip/options.lua:3: attempt to call global 'GetAddOnMetadata' (a nil value)
Time: Fri May  5 13:09:41 2023
Count: 1
Stack: Interface/AddOns/TacoTip/options.lua:3: attempt to call global 'GetAddOnMetadata' (a nil value)

Locals: 

Message: ...dOns/BagBrother/addons/core/features/autoDisplay.lua:132: attempt to index field 'sets' (a nil value)
Time: Fri May  5 13:09:45 2023
Count: 1
Stack: ...dOns/BagBrother/addons/core/features/autoDisplay.lua:132: attempt to index field 'sets' (a nil value)
[string "@Interface/AddOns/BagBrother/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...AddOns/BagBrother/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface_Wrath/FrameXML/UIParent.lua"]:398: in function `UIParentLoadAddOn'
[string "@Interface_Wrath/FrameXML/UIParent.lua"]:489: in function `TimeManager_LoadUI'
[string "@Interface_Wrath/FrameXML/UIParent.lua"]:800: in function <Interface_Wrath/FrameXML/UIParent.lua:769>

Locals: this = AceEvent30Frame {
 0 = <userdata>
}
event = "ADDON_LOADED"
events = <table> {
 recurse = 1
 events = <table> {
 }
 OnUsed = <function> defined @Interface/AddOns/BagBrother/libs/AceEvent-3.0/AceEvent-3.0.lua:32
 Fire = <function> defined @Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:49
 OnUnused = <function> defined @Interface/AddOns/BagBrother/libs/AceEvent-3.0/AceEvent-3.0.lua:36
 insertQueue = <table> {
 }
}

**Comment by MojoOli** [comment]
@B4LSTAD Just edit `Interface\AddOns\BagBrother\addons\core\core.lua`. Replace `Addon.Version = GetAddOnMetadata(ADDON, 'Version')` with e.g. `Addon.Version = 101`. Should be working after.
