### ISSUE TITLE
itemlevel for equipment

### ISSUE THREAD

**Issue by Juelanda23** [Jaliborc/Bagnon#1666]
Id love to see the itemlevel of my equipment when sorting.
I can see it in the tooltip but would love to just have it displayed where normally the count is shown.
Would that be possible?

Love the Addon since Vanilla

**Comment by Rezy942** [comment]
That is available through other addons like Bagnon ItemInfo
Unfortunately it wont happen in core Bagnon addon as author doesnt really add new features anymore (for past few years now)
Just updates to get it working to keep that donation button juice flowing

Currently those other addons are bugged, so there is no way to do this.

**Comment by Jaliborc** [comment]
> Id love to see the itemlevel of my equipment when sorting. I can see it in the tooltip but would love to just have it displayed where normally the count is shown. Would that be possible?
> 
> Love the Addon since Vanilla

I try to  avoid adding features that other authors have added as plugins, because it would be a bit like stealing. Talk with Goldpaw if ItemLevel isn't doing it for you!

**Comment by Rezy942** [comment]
Terrible reasoning sorry - this is your addon not theirs, they are improving it because yours is lacking.
I call lazyness not "addon theft".
