### ISSUE TITLE
Other addons dont work with Bagnon

### ISSUE THREAD

**Issue by Y4EV** [Jaliborc/Bagnon#1667]
Other addons such as Oilvl or Scrap dont work when I have bagnon enabled. I can't see either my gear ilvl in my bags (Oilvl) or icon on junk item I can sell (Scrap)

**Comment by Rezy942** [comment]
All those addons are broken as of now.
Hopefully not Bagnon related issue - but wouldnt be surprised at this point.
LiteBag seems like a better alternative day by day.

**Comment by Jaliborc** [comment]
I use Scrap myself (I'm the author) and it's working. Did I update Bagnon Scrap and forgot to upload it?
Anyway, itemlevel stuff is broken but not on my end.

**Comment by rookdorf** [comment]
This is still an active issue, Oilvl's "show item levels in bag" does not function with Bagnon enabled.
![image](https://github.com/Jaliborc/Bagnon/assets/28067431/b9d5ed7b-5444-4253-afbc-d181effb9955)
![image](https://github.com/Jaliborc/Bagnon/assets/28067431/10409eb4-c37a-4ac7-bc8d-1324889865ce)
