### ISSUE TITLE
Taking the required number of items from the guild bank

### ISSUE THREAD

**Issue by Louivatar** [Jaliborc/Bagnon#1669]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.1
 - Server patch: 10.1.0.49444

**Describe the bug**
Click "Shift" + left mouse button on item in guild bank = error and nothing happens 

**Expected behaviour**
taking the required number of items from the stack from the guild bank

**Error Logs**
3x BagBrother/frames/guild/item.lua:30: attempt to compare number with nil
[string "@BagBrother/frames/guild/item.lua"]:30: in function <BagBrother/frames/guild/item.lua:26>

Locals:
self = BagnonGuildItem32 {
 0 = <userdata>
 SetItem = <function> defined @FrameXML/ItemButtonTemplate.lua:544
 IconOverlay = Texture {
 }
 Super = <function> defined @BagBrother/libs/Poncho-2.0/Poncho-2.0.lua:157
 showMatchHighlight = true
 flashAnim = AnimationGroup {
 }
 GetTemplate = <function> defined @BagBrother/libs/Poncho-2.0/Poncho-2.0.lua:108
 SetReadable = <function> defined @FrameXML/ContainerFrame.lua:1675
 UpdateNewItem = <function> defined @FrameXML/ContainerFrame.lua:1621
 __count = 32

**Comment by JimGiordano2** [comment]
I also have this problem.  Any quick fixes?
