### ISSUE TITLE
LUA error string

### ISSUE THREAD

**Issue by Acer2690** [Jaliborc/Bagnon#1677]
Message: ...erface/AddOns/BagBrother/libs/ItemSearch-1.3/API.lua:53: attempt to index field 'args' (a nil value)
Time: Wed May 10 17:33:12 2023
Count: 23
Stack: ...erface/AddOns/BagBrother/libs/ItemSearch-1.3/API.lua:53: attempt to index field 'args' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/BagBrother/libs/ItemSearch-1.3/API.lua"]:53: in function <...erface/AddOns/BagBrother/libs/ItemSearch-1.3/API.lua:50>
[string "@Interface/AddOns/BagBrother/libs/ItemSearch-1.3/API.lua"]:58: in function `IsUnusable'
[string "@Interface/AddOns/BagBrother/addons/core/classes/item.lua"]:243: in function `UpdateBorder'
[string "@Interface/AddOns/BagBrother/addons/core/classes/item.lua"]:206: in function `Update'
[string "@Interface/AddOns/BagBrother/addons/core/classes/item.lua"]:134: in function <...rface/AddOns/BagBrother/addons/core/classes/item.lua:129>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/BagBrother/addons/core/api/frames.lua"]:85: in function `Show'
[string "@Interface/AddOns/BagBrother/addons/core/api/frames.lua"]:77: in function <...terface/AddOns/BagBrother/addons/core/api/frames.lua:76>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/BagBrother/addons/core/features/autoDisplay.lua"]:83: in function <...dOns/BagBrother/addons/core/features/autoDisplay.lua:82>
[string "=[C]"]: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals: (*temporary) = <function> defined =[C]:-1

I keep getting these LUA errors. Says everything is updated in CurseForge, but I always get these.

**Comment by Galthariel** [comment]
Same error
