### ISSUE TITLE
GetAttribute is not a function - error

### ISSUE THREAD

**Issue by R3verse** [Jaliborc/Bagnon#1704]
**Running Software (issues missing this information will be deleted):**
 - Addon version:10.0.16
 - Server patch: Newest!

 **Have you read the changelog? (please don't waste our time)**
YES

**Describe the bug**
Message: [string "Interface/AddOns/BagBrother/libs/TaintLess/..."]:77: hooksecurefunc(): GetAttribute is not a function
Time: Sat Jun 24 23:20:27 2023
Count: 1
Stack: [string "Interface/AddOns/BagBrother/libs/TaintLess/..."]:77: hooksecurefunc(): GetAttribute is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "Interface/AddOns/BagBrother/libs/TaintLess/TaintLess.xml:<Scripts>"]:77: in main chunk

**Expected behaviour**

**Screenshots**
[Check screenshot! - HERE ](https://i.imgur.com/m1V0FuZ.png)

**Error Logs**
Message: [string "Interface/AddOns/BagBrother/libs/TaintLess/..."]:77: hooksecurefunc(): GetAttribute is not a function
Time: Sat Jun 24 23:22:54 2023
Count: 1
Stack: [string "Interface/AddOns/BagBrother/libs/TaintLess/..."]:77: hooksecurefunc(): GetAttribute is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "Interface/AddOns/BagBrother/libs/TaintLess/TaintLess.xml:<Scripts>"]:77: in main chunk

**Comment by melvintj** [comment]
Same error

Date: 2023-06-26 13:18:48
ID: 1
Error occured in: Global
Count: 1
Message: [string "Interface/AddOns/Scrap/libs/TaintLess/Taint..."] line 77:
   hooksecurefunc(): GetAttribute is not a function
Debug:
   [string "=[C]"]: hooksecurefunc()
   [string "Interface/AddOns/Scrap/libs/TaintLess/TaintLess.xml:<Scripts>"]:77: in main chunk
Locals:

AddOns:
  KalielsTracker, v3.3.0
  Swatter, v3.4.6921 (SwimmingSeadragon)
  AtlasLootClassic, vv3.1.2
  AtlasLootClassicData, vv3.1.2
  AtlasLootClassicDungeonsAndRaids, vv3.1.2
  AucAdvanced, v3.4.6931 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6941 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6928 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6913 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6910 (SwimmingSeadragon)
  AucStatSimple, v3.4.6911 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6912 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6914 (SwimmingSeadragon)
  Bartender4, v4.14.10
  BeanCounter, v3.4.6933 (SwimmingSeadragon)
  BetterVendorPrice, vv1.19.01
  DBMCore, v962c5cc
  DBMStatusBarTimers, v962c5cc
  DBMVPVEM, v12a1962
  Details, v#Details.20230520.11023.151
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Enchantrix, v3.4.6942 (SwimmingSeadragon)
  EnchantrixBarker, v3.4.6917 (SwimmingSeadragon)
  GTFO, v5.0.5
  MythicDungeonTools, v4.0.4.12
  Pawn, v2.8.2
  Plater, vPlater-v560.4-Wrath
  Questie, v8.7.1
  RareScanner, v3.4.2.1
  Scrap, v10.1
  SlideBar, v3.4.6919 (SwimmingSeadragon)
  Stubby, v3.4.6920 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v3.4.2.30402 <none>
  (ck=4f2)

**Comment by jozefizso** [comment]
Happens to me with Wrath `3.4.2.50172`


```
Date: 2023-06-27 17:02:39
ID: 1
Error occured in: Global
Count: 1
Message: [string "Interface/AddOns/BagBrother/libs/TaintLess/..."] line 77:
   hooksecurefunc(): GetAttribute is not a function
Debug:
   [string "=[C]"]: hooksecurefunc()
   [string "Interface/AddOns/BagBrother/libs/TaintLess/TaintLess.xml:<Scripts>"]:77: in main chunk
Locals:

AddOns:
  Swatter, v3.4.6921 (SwimmingSeadragon)
  Atlas, vv1.52.07
  AtlasBurningCrusade, vv1.52.02
  AtlasClassicWoW, vv1.52.04
  AtlasDungeonLocs, vv1.52.02
  AtlasOutdoorRaids, vv1.52.03
  AtlasTransportation, vv1.52.03
  AtlasWrathoftheLichKing, vv1.52.02
  AucAdvanced, v3.4.6931 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6941 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6928 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6913 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6910 (SwimmingSeadragon)
  AucStatSimple, v3.4.6911 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6912 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6914 (SwimmingSeadragon)
  Auctionator, v10.1.8
  BagBrother, v
  Bagnon, v10.0.16
  SlideBar, v3.4.6919 (SwimmingSeadragon)
  Stubby, v3.4.6920 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v3.4.2.30402 <none>
  (ck=32f)
```

**Comment by F22Astroturf** [comment]
Same problem here with the "GetAttribute is not a function"  error so no sense repeating all the log files other have already posted.

**Comment by NayooZ** [comment]
Fix is here: https://github.com/Jaliborc/Bagnon/issues/1703

You need to replace the TaintLess.xml

**Comment by kriminy** [comment]
> 

Thank you for posting this. I just wanted to share that this fix also works for the same error on the Classic Era PTR (toc 1.14.4).

**Comment by NickNiz** [comment]
How do I go about replacing the Taintless.xml? I cant find it in the program files/ add on folders

**Comment by F22Astroturf** [comment]
This is the Locations for both folders WotLK and Classic
C:\Program Files (x86)\World of Warcraft\_classic_\Interface\AddOns\BagBrother\libs\TaintLess       <--- WotLK
C:\Program Files (x86)\World of Warcraft\_classic_era_\Interface\AddOns\BagBrother\libs\TaintLess  <-- Classic
