### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by Feronas** [Jaliborc/Bagnon#1706]
**Running Software (issues missing this information will be deleted):**
 - Addon version:
![image](https://github.com/Jaliborc/Bagnon/assets/65334149/8991fef9-c5c3-4139-b3f8-73a32d20a5ba)

 - Server patch: [e.g. Build 8.0.1.27178]
![image](https://github.com/Jaliborc/Bagnon/assets/65334149/139589d6-5c67-4f83-9cc5-2f4fd8154ce3)

 **Have you read the changelog? (please don't waste our time)**
Yes I read it.

**Describe the bug**
Lua error when logging in to the game.

**To Reproduce**
Log on

**Expected behaviour**
Lua error always pops upon log in

**Screenshots**
![image](https://github.com/Jaliborc/Bagnon/assets/65334149/9a9e2c11-d699-4819-8e7a-acafccd1f729)

**Comment by NayooZ** [comment]
https://github.com/Jaliborc/Bagnon/issues/1703

Fix is here. Replace TaintLess lib with the one from the link

**Comment by Feronas** [comment]
> #1703
> 
> Fix is here. Replace TaintLess lib with the one from the link

Thanks for the reply, will the addon be updated soon with this mentioned fix? Regards.

**Comment by NayooZ** [comment]
> 

I have submitted a pull request in the BagBrother Github for Jaliborc to review and merge.
