### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by warcraftclassicgamer** [Jaliborc/Bagnon#1710]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 2.13.3
 - Server patch: 50250

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. Yes read

**Describe the bug**
I am using your addon for wotlk classic. Since the launch of phase 3 of wotlk classic, the lua error shows up. Previously in phase 1 and phase 2 of wotlk classic, your addon worked perfect with no lua errors.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download your addon version for wotlk classic
2. install to the wotlk classic addons folder
3. log into wotlk classic
4. lua error shows up

**Expected behaviour**
log into the game without bagnon lua error

**Screenshots**
https://ibb.co/qpLLt2B

**Error Logs**

Date: 2023-07-06 19:01:18
ID: 1
Error occured in: Global
Count: 1
Message: [string "Interface/AddOns/BagBrother/libs/TaintLess/..."] line 77:
   hooksecurefunc(): GetAttribute is not a function
Debug:
   [string "=[C]"]: hooksecurefunc()
   [string "Interface/AddOns/BagBrother/libs/TaintLess/TaintLess.xml:<Scripts>"]:77: in main chunk
Locals:

AddOns:
  Swatter, v3.4.6921 (SwimmingSeadragon)
  Atlas, vv1.52.07
  AtlasBurningCrusade, vv1.52.02
  AtlasClassicWoW, vv1.52.04
  AtlasWrathoftheLichKing, vv1.52.01
  AtlasLootClassic, vv3.1.2
  AtlasLootClassicData, vv3.1.2
  AtlasLootClassicDungeonsAndRaids, vv3.1.2
  Attune, v312
  Auctionator, v10.1.12
  BadBoy, vv10.1.1
  BadBoyCCleaner, vv10.1.1
  BadBoyHistory, vv10.1.1
  BadBoyLevels, vv9.2.4
  BagBrother, v
  Bagnon, v10.0.16
  BlizRuntimeLib_enUS v3.4.2.30402 <none>
  (ck=1db)

**Additional context**
Date: 2023-07-06 19:00:27
ID: 1
Error occured in: Global
Count: 1
Message: [string "Interface/AddOns/BagBrother/libs/TaintLess/..."] line 77:
   hooksecurefunc(): GetAttribute is not a function
Debug:
   [string "=[C]"]: hooksecurefunc()
   [string "Interface/AddOns/BagBrother/libs/TaintLess/TaintLess.xml:<Scripts>"]:77: in main chunk
Locals:

AddOns:
  Swatter, v3.4.6921 (SwimmingSeadragon)
  Atlas, vv1.52.07
  AtlasBurningCrusade, vv1.52.02
  AtlasClassicWoW, vv1.52.04
  AtlasWrathoftheLichKing, vv1.52.01
  AtlasLootClassic, vv3.1.2
  AtlasLootClassicData, vv3.1.2
  AtlasLootClassicDungeonsAndRaids, vv3.1.2
  Attune, v312
  Auctionator, v10.1.12
  BadBoy, vv10.1.1
  BadBoyCCleaner, vv10.1.1
  BadBoyHistory, vv10.1.1
  BadBoyLevels, vv9.2.4
  BagBrother, v
  Bagnon, v10.0.16
  BlizRuntimeLib_enUS v3.4.2.30402 <none>
  (ck=1db)

**Comment by NayooZ** [comment]
Already fixed here and waiting on pull request to be merged. 

https://github.com/Jaliborc/Bagnon/issues/1703
