### ISSUE TITLE
Bagbrother bug

### ISSUE THREAD

**Issue by Dinbandit** [Jaliborc/Bagnon#1711]
1x [string "BagBrother/libs/TaintLess/..."]:77: hooksecurefunc(): GetAttribute is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "BagBrother/libs/TaintLess/TaintLess.xml:<Scripts>"]:77: in main chunk

**Comment by NayooZ** [comment]
Already fixed here and waiting on pull request to be merged. 

https://github.com/Jaliborc/Bagnon/issues/1703
