### ISSUE TITLE
Error on login without doing anything

### ISSUE THREAD

**Issue by Knakriktsur** [Jaliborc/Bagnon#1712]
**WOTLK 3.4.2.50250
Ger Client
Bagnon "Bagnon-10.0.16 for wow-3.4.1"

When I login i get this error without doing anything:
1x [string "BagBrother/libs/TaintLess/..."]:77: hooksecurefunc(): GetAttribute is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "BagBrother/libs/TaintLess/TaintLess.xml:<Scripts>"]:77: in main chunk

Locals:

**Comment by NayooZ** [comment]
Already fixed here and waiting on pull request to be merged. 

https://github.com/Jaliborc/Bagnon/issues/1703
