### ISSUE TITLE
Lua Errors upon login

### ISSUE THREAD

**Issue by Nausican0069** [Jaliborc/Bagnon#1715]
Greetings.  Upon login, with all addons disabled except Bagnon and BagBrother, all saved variable deleted, I receive the following errors. 

Message: [string "Interface/AddOns/BagBrother/libs/TaintLess/..."]:77: hooksecurefunc(): GetAttribute is not a function
Time: Sun Jul 16 23:05:30 2023
Count: 1
Stack: [string "Interface/AddOns/BagBrother/libs/TaintLess/..."]:77: hooksecurefunc(): GetAttribute is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "Interface/AddOns/BagBrother/libs/TaintLess/TaintLess.xml:<Scripts>"]:77: in main chunk

Locals: 

This is across (3) accounts and WTF was deleted to test this behavior. 

Thanx in advance.

**Comment by Speaker1264** [comment]
I'm getting the same LUA error:

Message: [string "Interface/AddOns/BagBrother/libs/TaintLess/..."]:77: hooksecurefunc(): GetAttribute is not a function
Time: Mon Jul 24 19:04:45 2023
Count: 1
Stack: [string "Interface/AddOns/BagBrother/libs/TaintLess/..."]:77: hooksecurefunc(): GetAttribute is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "Interface/AddOns/BagBrother/libs/TaintLess/TaintLess.xml:<Scripts>"]:77: in main chunk

Locals:
