### ISSUE TITLE
LUA bagbrother

### ISSUE THREAD

**Issue by sonixxone** [Jaliborc/Bagnon#1716]
I have been getting this error lately everytime i login

31x [string "BagBrother/libs/TaintLess/..."]:77: hooksecurefunc(): GetAttribute is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "BagBrother/libs/TaintLess/TaintLess.xml:<Scripts>"]:77: in main chunk

Locals:

Any idea why this is happening? Any solution to make this error stop popping up?
I think i saw one similar thread but not the exact same, almost, was a few differences.

Best regards

**Comment by F22Astroturf** [comment]
That's that Taintless error from before. Still have to get the The included version of TaintLess lib is out of date - a fix for 3.4.2 was released and fixes this issue. Can be resolved by including the newest release from https://www.townlong-yak.com/addons/taintless/release/23-05-18
I just reloaded this on mine and it still works
Replace the Taintless folder with this one.   Folder located at C:\Program Files (x86)\World of Warcraft\_classic_era_\Interface\AddOns\BagBrother\libs

**Comment by F22Astroturf** [comment]
Got way to many Errors in classic after updating so went back to version 10.1.1 and redid the Taintless  fix from from https://www.townlong-yak.com/addons/taintless/release/23-05-18 now everything seems to be working again

**Comment by sonixxone** [comment]
> Got way to many Errors in classic after updating so went back to version 10.1.1 and redid the Taintless fix from from https://www.townlong-yak.com/addons/taintless/release/23-05-18 now everything seems to be working again

Did it actually work this time? Cuz i think i have to do the same actually

**Comment by F22Astroturf** [comment]
> > Got way to many Errors in classic after updating so went back to version 10.1.1 and redid the Taintless fix from from https://www.townlong-yak.com/addons/taintless/release/23-05-18 now everything seems to be working again
> 
> Did it actually work this time? Cuz i think i have to do the same actually

Yes going back to the older version and replacing the Taintless Folder works fine for me
