### ISSUE TITLE
Can't see BANK on main character or OTHER characters

### ISSUE THREAD

**Issue by jasond12** [Jaliborc/Bagnon#1722]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.1.3
 - Server patch: 1.14.3

 **Have you read the changelog? (please don't waste our time)**
 Yes.

**Describe the bug**
Bank shows empty bags when trying to view away from the banker
Also cannot see bank across characters

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the bank
2. Move away from bank
3. Open Bagnon and attempt to open Bank
4. Empty/nothing in bank, check other characters, same issue

**Expected behaviour**
I should be able to see my bank (and on other characters) when away from the banker in the open world

**Comment by Masquue** [comment]
I'm experiencing the same issue.

**Comment by wishes90** [comment]
Same thing

**Comment by Deymanwow** [comment]
Yup, same problem here. I tried installing a few other older versions but those don't work at all. Bank shows nothing and i also have to talk to the bank npc twice to get the bank to show, when i speak with him the first time he shows me the empty 1 bag. Viewing my alts bag works but i can't view their bank. I really hope this gets fixed as i am super used over all these years to be able to view my & my alts bank from anywhere i am. Now I have to actually go to the bank or log my alt then go to the bank... Sending my prayers that the devs fix this asap :D

**Comment by wishes90** [comment]
So I just deleted following BagBrother cache files and everything seems to work fine so far:
_C:\Program Files (x86)\World of Warcraft\_classic_\WTF\Account\YouAccount\SavedVariables\BagBrother.lua
C:\Program Files (x86)\World of Warcraft\_classic_\WTF\Account\YouAccount\SavedVariables\BagBrother.lua.bak_

But keep in mind - **Bagnon will lose all data about all your characters**, you will have to re-enter each character and re-open banks to fill items data back

**Comment by Deymanwow** [comment]
> 

I tried this now, it did delete the data about all characters but it did not fix any problems :(

**Comment by jasond12** [comment]
@wishes90 tried this, did not fix the issue it seems

**Comment by Offroads** [comment]
Same, classic wotlk.

**Comment by VirusViper** [comment]
Had same issue since 10.1.2, moved to 10.1.3 still present, Tried 10.1.4 same issue. Rolled back to 10.0.16 and had to rebuild new lua files. Trying to roll back on updated .lua files causes errors.

**Comment by Deymanwow** [comment]
2 weeks later... The same issue still exists.
I've realised how Bagnon have made me so addicted to it! And I took it all for granted... This feature to view the bank from anywhere (even viewing your alt's bank) is so incredibly useful and I'm so sad to have it broken atm... :'( Every day when I open the curseforge client to update my addons, I get impatient because Bagnon still doesn't appear in the list! I hope it gets fixed soon! <3

**Comment by wishes90** [comment]
Guys, do your bank data disappear if you move away from the banker and the bank window closes automatically? Or at some other time (when you don't interact with the banker at all)?

**Comment by Deymanwow** [comment]
> Guys, do your bank data disappear if you move away from the banker and the bank window closes automatically? Or at some other time (when you don't interact with the banker at all)?

When i move away yes, not experienced any issue when afk at the bank.

**Comment by wishes90** [comment]
I [left a pull request](https://github.com/Jaliborc/BagBrother/pull/27) to the author with an attempt to fix it, but I'm not sure when he will be able to see it.
If anyone wants to try testing:

- Download this file [https://github.com/wishes90/BagBrother/blob/master/core/features/caching.lua](https://github.com/wishes90/BagBrother/blob/master/core/features/caching.lua) (yes, it's about BagBrother, not Bagnon)
- Go to `C:\Program Files (x86)\World of Warcraft\_classic_\Interface\AddOns\BagBrother\core\features`
- Backup (copy/move somewhere) original **caching.lua** file
- Replace it with the one you downloaded
- Restart the game and go to the bankers again to update bank items cache
- Check if it helped and tell me if not

**Comment by ManiacalOne** [comment]
> I [left a pull request](https://github.com/Jaliborc/BagBrother/pull/27) to the author with an attempt to fix it, but I'm not sure when he will be able to see it. If anyone wants to try testing:
> 
> * Download this file https://github.com/wishes90/BagBrother/blob/master/core/features/caching.lua (yes, it's about BagBrother, not Bagnon)
> * Go to `C:\Program Files (x86)\World of Warcraft\_classic_\Interface\AddOns\BagBrother\core\features`
> * Backup (copy/move somewhere) original **caching.lua** file
> * Replace it with the one you downloaded
> * Restart the game and go to the bankers again to update bank items cache
> * Check if it helped and tell me if not

Small sample size over a couple of logouts, but this APPEARS to have worked for me (so far)! Thanks!

**Comment by Deymanwow** [comment]
> I [left a pull request](https://github.com/Jaliborc/BagBrother/pull/27) to the author with an attempt to fix it, but I'm not sure when he will be able to see it. If anyone wants to try testing:
> 
> * Download this file https://github.com/wishes90/BagBrother/blob/master/core/features/caching.lua (yes, it's about BagBrother, not Bagnon)
> * Go to `C:\Program Files (x86)\World of Warcraft\_classic_\Interface\AddOns\BagBrother\core\features`
> * Backup (copy/move somewhere) original **caching.lua** file
> * Replace it with the one you downloaded
> * Restart the game and go to the bankers again to update bank items cache
> * Check if it helped and tell me if not

I tried this, it works and it solved the entire problem! THANK YOU SO MUCH <3

**Comment by foobarna** [comment]
> I [left a pull request](https://github.com/Jaliborc/BagBrother/pull/27) to the author with an attempt to fix it, but I'm not sure when he will be able to see it. If anyone wants to try testing:
> 
> * Download this file https://github.com/wishes90/BagBrother/blob/master/core/features/caching.lua (yes, it's about BagBrother, not Bagnon)
> * Go to `C:\Program Files (x86)\World of Warcraft\_classic_\Interface\AddOns\BagBrother\core\features`
> * Backup (copy/move somewhere) original **caching.lua** file
> * Replace it with the one you downloaded
> * Restart the game and go to the bankers again to update bank items cache
> * Check if it helped and tell me if not

This fixes the issue.

**Comment by Jaliborc** [comment]
> I [left a pull request](https://github.com/Jaliborc/BagBrother/pull/27) to the author with an attempt to fix it, but I'm not sure when he will be able to see it. If anyone wants to try testing:
> 
>     * Download this file https://github.com/wishes90/BagBrother/blob/master/core/features/caching.lua (yes, it's about BagBrother, not Bagnon)
> 
>     * Go to `C:\Program Files (x86)\World of Warcraft\_classic_\Interface\AddOns\BagBrother\core\features`
> 
>     * Backup (copy/move somewhere) original **caching.lua** file
> 
>     * Replace it with the one you downloaded
> 
>     * Restart the game and go to the bankers again to update bank items cache
> 
>     * Check if it helped and tell me if not

Jesus, that's the issue!? Goddamit Blizzard! And here I thought there was a bug lurking somewhere in the new caching code.
