### ISSUE TITLE
Bank archive is reset/forgotten after opening the bank archive view for the first time

### ISSUE THREAD

**Issue by Adalace** [Jaliborc/Bagnon#1730]
**Running Software**
 - Addon version: 10.1.4
 - Server patch: 1.14.3 (49821) (WoW Classic)

 **Describe the bug**
While away from the bank, I can only view archived bank items one time. If I open the bank view after the first time, a blank bank view is displayed with the default number of slots that are all empty. Visiting the actual bank and leaving resets this process so I can view the archived items one time before it resets again.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the bank so the items in the bank are archived/remembered by the addon.
2. While away from the bank, open the archived bank view (items in the bank should be displayed)
3. Close the bank archive view.
4. While away from the bank, open the archived bank view (same as step 2).

**Expected Behavior**
Upon opening the bank archive view for the second (or subsequent) times, the correct bank items should be displayed as though the actual bank were opened.

**Actual Behavior**
Upon opening the bank archive view for the second (or subsequent) times, the bank archive view shows the default number of slots and all of them are empty. It is as though the previously stored/archived bank state has been lost.

**Screenshots**
First time opening the bank archive view after visiting the actual bank:
![image](https://github.com/Jaliborc/Bagnon/assets/3720037/af1bb393-eb17-4750-b23c-a2590e28f71b)
Second time opening the bank archive view, just after closing the first view above.
![image](https://github.com/Jaliborc/Bagnon/assets/3720037/2f861a56-1833-4886-ac1f-48f4c6c9bda4)

**Error Logs**
No error window/message was displayed when I followed the instructions and reproduced the issue using the steps above.

**Additional context**
Addon version 10.0.16 from 2023-01-19 works correctly, without any bank archive issues.
Possibly related: Sometimes the actual bank view is reset/empty the first time I open the real bank, and I have to close and reopen the real bank to make the contents appear.

**Comment by Edder** [comment]
Same issue here

**Comment by SoMuchGreg** [comment]
Same here. Also a simiar issue happens when going back to bank after the bank archive is forgotten. When I go back to the bank to "refresh" the forgotten archive, the first time I talk to the bank teller, I see an empty default bank. Only the second time I talk to the teller, my bank refreshes and I see all the items there.

**Comment by Bratwurst99** [comment]
Same issue in WotLK Classic, addon version 10.1.4, game ver 3.4.2

**Comment by Adalace** [comment]
This issue does not affect WoW Classic version 1.14.4 (51001) (Release x64), Aug 18 2023.
I think now that this version has been pushed to live Classic realms, this bug no longer affects any live WoW versions and can be closed.
