### ISSUE TITLE
Bank snapshot not saving

### ISSUE THREAD

**Issue by Kyung783** [Jaliborc/Bagnon#1734]
in wotlk classic

**Comment by FuSoYa** [comment]
Also in classic era

**Comment by FuSoYa** [comment]
I tried to look into the issue, but the code for bagnon is difficult

**Comment by MyungHunPark** [comment]
10.1.3 works well.
but 10.1.4 has problem.

**Comment by wishes90** [comment]
[Here's another thread with a possible fix](https://github.com/Jaliborc/Bagnon/issues/1722#issuecomment-1666090774)

**Comment by FuSoYa** [comment]
That fixed it thanks @wishes90
