### ISSUE TITLE
Clean Items not combining stacks

### ISSUE THREAD

**Issue by RedDrumJay** [Jaliborc/Bagnon#1735]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.1.4
 - Server patch: Build 3.4.2 50664

 **Have you read the changelog? (please don't waste our time)**
Has not been updated since 10.1.2, but yes.

**Describe the bug**
Stacks are not consolidating on clean up. Flashing new items in bags continue to flash after mouseover and do not stop until closing and reopening bags.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open bags
2. Click on clean items icon
4. Cry

**Expected behaviour**
I expected the stacks to consolidate after cleanup, and for new items to stop flashing after mouseover.

**Screenshots**

**Error Logs**
None

**Additional context**
N/A

![image](https://github.com/Jaliborc/Bagnon/assets/1888234/c7f55c6d-8d15-4c4f-ac9e-582d41d97257)

**Comment by wazerstar** [comment]
can confirm WOTLK, stacks not combinding items

**Comment by skyler-code** [comment]
Quick fix
in `BagBrother\core\api\sorting.lua`
Change Line 119 to:
`local name, _,_, level, _,_,_,stack,equip, _, _, class, subclass = GetItemInfo(id)`
Change Line 123 to:
`item.subclass, item.equip, item.level, item.stack = subclass, equip, level, stack`

**Comment by 13ombadil** [comment]
> Quick fix in `BagBrother\core\api\sorting.lua` Change Line 119 to: `local name, _,_, level, _,_,_,stack,equip, _, _, class, subclass = GetItemInfo(id)` Change Line 123 to: `item.subclass, item.equip, item.level, item.stack = subclass, equip, level, stack`

just created an account to say thank you, this had really been bothering me

**Comment by RedDrumJay** [comment]
Thanks Skyler! That did it!

**Comment by bakemono-30** [comment]
I didn't get this error but a sort error and surprisingly this fix worked! 

@wazerstar yes those were my line numbers too!

**Comment by bugeaggeorge** [comment]
This bug still persists in WoTLK.

**Comment by ValsPedz** [comment]
> > local name, _,_, level, _,_,_,stack,equip, _, _, class, subclass = GetItemInfo(id)
> 
> You mean
> 
> **Line 118**
> 
> From ` local name, _,_, level, _,_,_,_, equip, _, _, class, subclass = GetItemInfo(id)`
> 
> To ` local name, _,_, level, _,_,_,stack,equip, _, _, class, subclass = GetItemInfo(id)`
> 
> **Line 122**
> 
> From ` item.subclass, item.equip, item.level = subclass, equip, level` To ` item.subclass, item.equip, item.level, item.stack = subclass, equip, level, stack`

FYI - I have to keep making this 2-line edit every time I update this Addon - I bookmarked this page for quick access, but it's 
very frustrating...

**Comment by LucasMoon** [comment]
Stack option not working anymore. I cant eve see where is the option for it. I follow some of the tips here and its a no go.
