### ISSUE TITLE
Does not retain bank info for all characters

### ISSUE THREAD

**Issue by Velarax** [Jaliborc/Bagnon#1738]
**Running Software (issues missing this information will be deleted):**
 - Addon version: current
 - Server patch: [e.g. Build 8.0.1.27178]

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. YES

**Describe the bug**

Does not retain ss of character banks.  When away from bank, often present character bank not retained.  All toons have been to the bank so Bagnon should have a ss of all banks.  But if I click to check another toon's bank, it's blank.

**To Reproduce**
Steps to reproduce the behaviour:

See above

**Expected behaviour**

Should have a pic of character bank, not a blank bank

**Screenshots**

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the message with `ID: 1` (labelled 1/X). This is generally NOT the message that the window shows by default.

None

**Additional context**

**Comment by Bratwurst99** [comment]
I have the same problem, Bagnon ver 10.1.4, WoW Wotlk Classic version 3.4.2.50664.

No bank information is available, even on the character I am currently playing, unless I go to the bank. If I log in and out the bank information is gone and shows empty tabs.

**Comment by Jaliborc** [comment]
Please report the characters' realm, name, race and class for which this happens, and for which it does not. Need to find the cause.

**Comment by Velarax** [comment]
I have characters on Ateish (alliance) Mankrik (horde) and Westfall (alliance).  I could list all 28 toons but that wouldn't really help you.  It has happened literally to each and every single one of my toons.  All races, all classes.  Bagnon seems not to discriminate.  All I know is every time I log in, banks are blank.  Even if I load all toons to refresh their banks, if I switch characters, the other toons' banks are blank.  Example:  I get on Velara NE hunter, view bank, no problem.  I log on Xune, Dranei warrior, same server and Vel's bank is blank.

**Comment by Jaliborc** [comment]
> I have characters on Ateish (alliance) Mankrik (horde) and Westfall (alliance). I could list all 28 toons but that wouldn't really help you. It has happened literally to each and every single one of my toons. All races, all classes. Bagnon seems not to discriminate. All I know is every time I log in, banks are blank. Even if I load all toons to refresh their banks, if I switch characters, the other toons' banks are blank. Example: I get on Velara NE hunter, view bank, no problem. I log on Xune, Dranei warrior, same server and Vel's bank is blank.

Can you post here your BagBrother saved variables?

**Comment by Jaliborc** [comment]
Also, in which language is your computer and game client?

**Comment by Jaliborc** [comment]
nevermind, found the cause!
