### ISSUE TITLE
Shift clicking on stack in gbank throws error - WotLK

### ISSUE THREAD

**Issue by RedDrumJay** [Jaliborc/Bagnon#1746]
**Running Software (issues missing this information will be deleted):**
 - Addon version:  10.4.1
 - Server patch: Build 3.4.2.50664

 **Have you read the changelog? (please don't waste our time)**
Yes

**Describe the bug**
Shift clicking a stack of items (5 items in this specific instance) resulted in the error below.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to guild bank
2. Shift-Click on on a stack to try to get just 1 item from the stack
3. See Error

**Expected behaviour**
I expected it to bring up the box to select how many items I wanted off the stack.

**Screenshots**

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the message with `ID: 1` (labelled 1/X). This is generally NOT the message that the window shows by default.

Message: Interface/AddOns/BagBrother/frames/guild/item.lua:30: attempt to compare number with nil
Time: Sun Aug 13 11:21:57 2023
Count: 1
Stack: Interface/AddOns/BagBrother/frames/guild/item.lua:30: attempt to compare number with nil
[string "@Interface/AddOns/BagBrother/frames/guild/item.lua"]:30: in function <Interface/AddOns/BagBrother/frames/guild/item.lua:26>

Locals: self = BagnonGuildItem31 {
 timeSinceUpgradeCheck = 0
 OnEnter = <function> defined @Interface/AddOns/BagBrother/core/classes/item.lua:118
 __super = <table> {
 }
 UnregisterAll = <function> defined @Interface/AddOns/BagBrother/core/classes/base.lua:27
 IconOverlay = Texture {
 }
 Super = <function> defined @Interface/AddOns/BagBrother/libs/Poncho-2.0/Poncho-2.0.lua:157
 Bind = <function> defined @Interface/AddOns/BagBrother/core/classes/item.lua:91
 IconBorder = Texture {
 }
 flashAnim = AnimationGroup {
 }
 OnReceiveDrag = <function> defined @Interface/AddOns/BagBrother/frames/guild/item.lua:59
 icon = BagnonGuildItem31IconTexture {
 }
 Backgrounds = <table> {
 }
 UpdateTooltip = <function> defined @Interface/AddOns/BagBrother/core/classes/item.lua:118
 ExtendedOverlay = Texture {
 }
 __type = "Button"
 __count = 31
 GetFrameID = <function> defined @Interface/AddOns/BagBrother/core/classes/parented.lua:35
 NewItemTexture = Texture {
 }
 Delay = <function> defined @Interface/AddOns/BagBrother/libs/MutexDelay-1.0/MutexDelay-1.0.lua:27
 SplitStack = <function> defined @Interface/AddOns/BagBrother/frames/guild/item.lua:75
 BagStaticBottom = Texture {
 }
 UpdateLocked = <function> defined @Interface/AddOns/BagBrother/core/classes/item.lua:182
 UnregisterMessage = <function> defined @Interface/AddOns/BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 Update = <function> defined @Interface/AddOns/BagBrother/core/classes/item.lua:141
 flash = Texture {
 }
 Dummy = Button {
 }
 RegisterFrameSignal = <function> defined @Interface/AddOns/BagBrother/core/classes/base.lua:15
 SetDesaturated = <function> defined @Interface/AddOns/BagBrother/core/classes/item.lua:187
 UpdateSearch = <function> defined @Interface/AddOns/BagBrother/core/classes/item.lua:215
 hasItem = true
 UnregisterSignal = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:78
 count = 5
 GetProfile = <function> defined @Interface/AddOns/BagBrother/core/classes/parented.lua:19
 info = <table> {
 }
 GetQuery = <function> defined @Interface/AddOns/BagBrother/core/classes/item.lua:305
 OnDragStart = <function> defined @Interface/AddOns/BagBrother/frames/guild/item.lua:53
 frame = BagnonGuild1 {
 }
 Delaying = <function> defined @Interface/AddOns/BagBrother/libs/MutexDelay-1.0/MutexDelay-1.0.lua:46
 Count = BagnonGuildItem31Count {
 }
 UnregisterAllEvents = <function> defined =[C]:-1
 IconGlow = Texture {
 }
 searchOverlay = BagnonGuildItem31SearchOverlay {
 }
 Construct = <function> defined @Interface/AddOns/BagBrother/frames/guild/item.lua:13
 BagFamilies = <table> {
 }
 SendSignal = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:82
 bag = 1
 BattlepayItemTexture = Texture {
 }
 GetOwner = <function> defined @Interface/AddOns/BagBrother/core/classes/parented.lua:27
 JunkIcon = Texture {
 }
 GetTipAnchor = <function> defined @Interface/AddOns/BagBrother/core/classes/tipped.lua:19
 __template = "ContainerFrameItemButtonTemplate"
 Flash = AnimationGroup {
 }
 UnregisterEvent = <function> defined =[C]:-1
 GetClassName = <function> defined @Interface/AddOns/BagBrother/libs/Poncho-2.0/Poncho-2.0.lua:100
 GetClass = <function> defined @Interface/AddOns/BagBrother/libs/Poncho-2.0/Poncho-2.0.lua:135
 ShowTooltip = <function> defined @Interface/AddOns/BagBrother/frames/guild/item.lua:68
 newitemglowAnim = AnimationGroup {
 }
 IsAbstract = <function> defined @Interface/AddOns/BagBrother/libs/Poncho-2.0/Poncho-2.0.lua:116
 UpdateUpgradeIcon = <function> defined @Interface/AddOns/BagBrother/core/classes/item.lua:223
 New = <function> 

**Additional context**

**Comment by Tregan** [comment]
> I have the issue open on the BagBrother github here: [Jaliborc/BagBrother#24](https://github.com/Jaliborc/BagBrother/issues/24)

Fix for this can be found in the comment section of the mentioned issue.
