### ISSUE TITLE
Flashing items doesn't work

### ISSUE THREAD

**Issue by Xdembe** [Jaliborc/Bagnon#1750]
**Running Software (issues missing this information will be deleted):**
 - Addon version:10.1.4
 - Server patch: 1.14.4(51056)

 **Have you read the changelog? (please don't waste our time)**
 Yes
**Describe the bug**
Alt-clicking feature doesn't work

**To Reproduce**
Steps to reproduce the behaviour:
1. Open bags
2. Hold Alt and click on any item
3. See error

**Expected behaviour**
Flashing same items in bags

**Screenshots**
not relevant

**Error Logs**
99x BagBrother/core/classes/itemGroup.lua:71: attempt to index field 'Flash' (a nil value)
[string "@BagBrother/core/classes/itemGroup.lua"]:71: in function `?'
[string "@BagBrother/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:119: in function <...her/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@BagBrother/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:29: in function <...her/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@BagBrother/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:64: in function `SendMessage'
[string "@BagBrother/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:83: in function `SendSignal'
[string "@BagBrother/core/classes/item.lua"]:114: in function <BagBrother/core/classes/item.lua:112>
[string "=(tail call)"]: ?
[string "@BagBrother/frames/containers/item.lua"]:46: in function <BagBrother/frames/containers/item.lua:45>
[string "=[C]"]: ?

Locals:
self = Frame {
 0 = <userdata>
 buttons = <table> {
 }
 order = <table> {
 }
 frame = BagnonInventory1 {
 }
 bags = <table> {
 }
}
_ = "BAGNON_FLASH_ITEM"
itemID = 5206
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = BagnonContainerItem55 {
 }
 2 = BagnonContainerItem56 {
 }
 3 = BagnonContainerItem57 {
 }
 4 = BagnonContainerItem58 {
 }
 5 = BagnonContainerItem1 {
 }
 6 = BagnonContainerItem2 {
 }
 7 = BagnonContainerItem3 {
 }
 8 = BagnonContainerItem4 {
 }
 9 = BagnonContainerItem5 {
 }
 10 = BagnonContainerItem6 {
 }
 11 = BagnonContainerItem7 {
 }
 12 = BagnonContainerItem8 {
 }
 13 = BagnonContainerItem9 {
 }
 14 = BagnonContainerItem10 {
 }
 15 = BagnonContainerItem11 {
 }
 16 = BagnonContainerItem12 {
 }
 17 = BagnonContainerItem13 {
 }
 18 = BagnonContainerItem14 {
 }
 19 = BagnonContainerItem15 {
 }
 20 = BagnonContainerItem16 {
 }
 21 = BagnonContainerItem17 {
 }
 22 = BagnonContainerItem18 {
 }
 23 = BagnonContainerItem19 {
 }
 24 = BagnonContainerItem20 {
 }
 25 = BagnonContainerItem21 {
 }
 26 = BagnonContainerItem22 {
 }
 27 = BagnonContainerItem23 {
 }
 28 = BagnonContainerItem24 {
 }
 29 = BagnonContainerItem25 {
 }
 30 = BagnonContainerItem26 {
 }
 31 = BagnonContainerItem27 {
 }
 32 = BagnonContainerItem28 {
 }
 33 = BagnonContainerItem53 {
 }
 34 = BagnonContainerItem54 {
 }
}
(for control) = 1
i = 1
button = BagnonContainerItem55 {
 0 = <userdata>
 OnLeave = <function> defined @BagBrother/core/classes/item.lua:126
 __super = <table> {
 }
 UnregisterAll = <function> defined @BagBrother/core/classes/base.lua:27
 IconOverlay = Texture {
 }
 UpdateCooldown = <function> defined @BagBrother/frames/containers/item.lua:86
 Bind = <function> defined @BagBrother/core/classes/item.lua:91
 IconBorder = Texture {
 }
 flashAnim = AnimationGroup {
 }
 icon = BagnonContainerItem55IconTexture {
 }
 Backgrounds = <table> {
 }
 UpdateTooltip = <function> defined @BagBrother/frames/containers/item.lua:57
 ExtendedOverlay = Texture {
 }
 __type = "Button"
 __count = 55
 GetFrameID = <function> defined @BagBrother/core/classes/parented.lua:35
 NewItemTexture = Texture {
 }
 Delay = <function> defined @BagBrother/libs/MutexDelay-1.0/MutexDelay-1.0.lua:27
 SplitStack = <function> defined @FrameXML/ContainerFrame_Shared.lua:1059
 BagStaticBottom = Texture {
 }
 UpdateLocked = <function> defined @BagBrother/core/classes/item.lua:182
 UnregisterMessage = <function> defined @BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 Update = <function> defined @BagBrother/frames/containers/item.lua:70
 flash = Texture {
 }
 Dummy = Button {
 }
 RegisterFrameSignal = <function> defined @BagBrother/core/classes/base.lua:15
 SetDesaturated = <function> defined @BagBrother/core/classes/item.lua:187
 UpdateSearch = <function> defined @BagBrother/core/classes/item.lua:215
 hasItem = true
 readable = false
 UnregisterSignal = <function> defined @BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:78
 count = 1
 info = <table> {
 }
 GetProfile = <function> defined @BagBrother/core/classes/parented.lua:19
 UpdateNewItemAnimation = <function> defined @BagBrother/core/classes/item.lua:227
 GetQuery = <function> defined @BagBrother/frames/containers/item.lua:122
 frame = BagnonInventory1 {
 }
 UnregisterAllEvents = <function> defined =[C]:-1
 UnregisterEvent = <function> defined =[C]:-1
 Count = BagnonContainerItem55Count {
 }
 IconGlow = Texture {
 }
 OnPreClick = <function> defined @BagBrother/frames/containers/item.lua:20
 searchOverlay = BagnonContainerItem55SearchOverlay {
 }
 Construct = <function> defined @BagBrother/frames/containers/item.lua:14
 BagFamilies = <table> {
 }
 SendSignal = <function> defined @BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:82
 ba
**Additional context**

**Comment by alexnaumovich** [comment]
It has been broken for some time.
As a workaround, edit BagBrother\core\classes\itemGroup.lua and change two occurrences of "self.Flash" to "button.flashAnim". It should be around line 71 and 73.

https://github.com/rowaasr13/BagBrother/commit/f51c13a44d9e4debc65b6b8095f838dda1100c7d#diff-0a89f16a2962951fdcb3bfcaf42e16861a0677d60bf8dbd72d1ffad68ffdd36a

**Comment by Jaliborc** [comment]
On it. Confused myself why there are two flashing animation objects now

**Comment by Jaliborc** [comment]
Figured it out. Fix coming out next week.
