### ISSUE TITLE
v10.1.8 on retail bagbrother currency error

### ISSUE THREAD

**Issue by Xorag** [Jaliborc/Bagnon#1757]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.1.8
 - Server version: 10.1.7

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. -Yes

**Describe the bug**
When zoning into a new area via portal I am getting this currency bagbrother error. I have done a completely fresh install and deleted all of my saved variable files

**To Reproduce**
Steps to reproduce the behaviour:
1. Fresh install bag brother
2. Go through a portal or use a hearth stone
3. Error should occur

**Expected behaviour**
No error

**Screenshots**
n/a

**Error Logs**
4x BagBrother/core/features/caching.lua:93: attempt to compare number with nil
[string "@BagBrother/core/features/caching.lua"]:93: in function `?'
[string "@BagBrother/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:119: in function <...her/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@BagBrother/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:29: in function <...her/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@BagBrother/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@BagBrother/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <BagBrother/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 SendSignal = <function> defined @BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:82
 ParseItem = <function> defined @BagBrother/core/features/caching.lua:187
 RegisterMessage = <function> defined @BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 SaveBag = <function> defined @BagBrother/core/features/caching.lua:158
 PLAYER_EQUIPMENT_CHANGED = <function> defined @BagBrother/core/features/caching.lua:80
 SaveEquip = <function> defined @BagBrother/core/features/caching.lua:183
 player = <table> {
 }
 SendMessage = <function> defined @BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:59
 GUILDBANKBAGSLOTS_CHANGED = <function> defined @BagBrother/core/features/caching.lua:132
 UnregisterAllEvents = <function> defined @BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 UnregisterSignal = <function> defined @BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:78
 VAULT_CLOSE = <function> defined @BagBrother/core/features/caching.lua:119
 PLAYER_MONEY = <function> defined @BagBrother/core/features/caching.lua:88
 BANK_CLOSE = <function> defined @BagBrother/core/features/caching.lua:107
 RegisterEvent = <function> defined @BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 CURRENCY_TRACKED_CHANGED = <function> defined @BagBrother/core/features/caching.lua:96
 NewModule = <function> defined @BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:68
 PLAYER_LEVEL_UP = <function> defined @BagBrother/core/features/caching.lua:84
 OnEnable = <function> defined @BagBrother/core/features/caching.lua:20
 BAG_UPDATE = <function> defined @BagBrother/core/features/caching.lua:74
 RegisterSignal = <function> defined @BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:74
 CURRENCY_DISPLAY_UPDATE = <function> defined @BagBrother/core/features/caching.lua:92
 GUILD_ROSTER_UPDATE = <function> defined @BagBrother/core/features/caching.lua:128
 UnregisterEvent = <function> defined @BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 Tag = "BAGNON_"
}
_ = "CURRENCY_DISPLAY_UPDATE"
id = nil
quantity = nil
(*temporary) = <table> {
 2088 = 2
 2245 = 348
 2402 = 2
 2594 = 980
 823 = 9
 1585 = 695852
 1586 = 81
 515 = 9
 1155 = 13
 tracked = <table> {
 }
 1220 = 425
 2118 = 714
 1533 = 569
 1273 = 1
 2021 = 2
 824 = 12
 2002 = 1
 2003 = 1334
 1342 = 25
 2024 = 1
 1166 = 1480
}
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"

**Additional context**
Not atm

**Comment by Jaliborc** [comment]
Please let me know if the issue persists in the upcoming 10.1.9 version. Thought I had fixed that issue, maybe released without the fix.

**Comment by markstenerson** [comment]
@Jaliborc where can we get 10.1.9? Or is it not quite out yet?
