### ISSUE TITLE
LUA error on loging with latest Bagnon + Bagnon Scrap

### ISSUE THREAD

**Issue by empiricalbw** [Jaliborc/Bagnon#1759]
**Which software were you running?**
 - Addon version name: Bagnon, Bagnon Scrap
 - Client used: WoW Classic Hardcore v1.14.4

**Have you read the changelog?**
No

**Please describe the bug.**
I logged in and it threw this error.

**Please describe how to reproduce it.**
Logged in to my character and it threw the error.

**Any Screenshots?**
Attached screenshot shows what was in my inventory after I closed the error log window and immediately opened my bags.  I don't have anything really unusual in my bags; just some quest items and then some random trash.

**Error Logs are Important!**
Message: ...nterface/AddOns/BagBrother/core/features/caching.lua:93: attempt to compare number with nil
Time: Mon Sep 11 20:37:02 2023
Count: 1
Stack: ...nterface/AddOns/BagBrother/core/features/caching.lua:93: attempt to compare number with nil
[string "@Interface/AddOns/BagBrother/core/features/caching.lua"]:93: in function `?'
[string "@Interface/AddOns/BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:119: in function <...her/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...her/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/BagBrother/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...AddOns/BagBrother/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: self = <table> {
 SendSignal = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:82
 ParseItem = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:187
 RegisterMessage = <function> defined @Interface/AddOns/BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface/AddOns/BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 SaveBag = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:158
 PLAYER_EQUIPMENT_CHANGED = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:80
 SaveEquip = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:183
 player = <table> {
 }
 SendMessage = <function> defined @Interface/AddOns/BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:59
 GUILDBANKBAGSLOTS_CHANGED = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:132
 UnregisterAllEvents = <function> defined @Interface/AddOns/BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 UnregisterSignal = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:78
 VAULT_CLOSE = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:119
 PLAYER_MONEY = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:88
 BANK_CLOSE = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:107
 RegisterEvent = <function> defined @Interface/AddOns/BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @Interface/AddOns/BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 CURRENCY_TRACKED_CHANGED = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:96
 NewModule = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:68
 PLAYER_LEVEL_UP = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:84
 OnEnable = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:20
 BAG_UPDATE = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:74
 RegisterSignal = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:74
 CURRENCY_DISPLAY_UPDATE = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:92
 GUILD_ROSTER_UPDATE = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:128
 UnregisterEvent = <function> defined @Interface/AddOns/BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 Tag = "BAGNON_"
}
_ = "CURRENCY_DISPLAY_UPDATE"
id = nil
quantity = nil
(*temporary) = <table> {
 tracked = <table> {
 }
}
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"

<img width="581" alt="Screen Shot 2023-09-11 at 8 39 48 PM" src="https://github.com/Jaliborc/Bagnon/assets/83632614/68c33024-084d-4510-bcf7-c55ebbc99c49">

**Comment by sasquatch1955** [comment]
I am also having this error thrown every time that I port with my mage to any location.

Message: ...nterface/AddOns/BagBrother/core/features/caching.lua:93: attempt to compare number with nil
Time: Tue Sep 12 02:56:55 2023
Count: 1
Stack: ...nterface/AddOns/BagBrother/core/features/caching.lua:93: attempt to compare number with nil
[string "@Interface/AddOns/BagBrother/core/features/caching.lua"]:93: in function `?'
[string "@Interface/AddOns/TomTom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...Tom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/TomTom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...Tom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/TomTom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/TomTom/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...ace/AddOns/TomTom/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: self = <table> {
 SendSignal = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:82
 ParseItem = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:187
 RegisterMessage = <function> defined @Interface/AddOns/TomTom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @Interface/AddOns/TomTom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 SaveBag = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:158
 PLAYER_EQUIPMENT_CHANGED = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:80
 SaveEquip = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:183
 player = <table> {
 }
 SendMessage = <function> defined @Interface/AddOns/TomTom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:49
 GUILDBANKBAGSLOTS_CHANGED = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:132
 UnregisterAllEvents = <function> defined @Interface/AddOns/TomTom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 UnregisterSignal = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:78
 VAULT_CLOSE = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:119
 PLAYER_MONEY = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:88
 BANK_CLOSE = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:107
 RegisterEvent = <function> defined @Interface/AddOns/TomTom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterAllMessages = <function> defined @Interface/AddOns/TomTom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 CURRENCY_TRACKED_CHANGED = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:96
 NewModule = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:68
 PLAYER_LEVEL_UP = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:84
 OnEnable = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:20
 BAG_UPDATE = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:74
 RegisterSignal = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:74
 CURRENCY_DISPLAY_UPDATE = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:92
 GUILD_ROSTER_UPDATE = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:128
 UnregisterEvent = <function> defined @Interface/AddOns/TomTom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 Tag = "BAGNON_"
}
_ = "CURRENCY_DISPLAY_UPDATE"
id = nil
quantity = nil
(*temporary) = <table> {
 829 = 19
 1889 = 47
 2032 = 825
 1810 = 18
 2017 = 9
 1906 = 2572
 2002 = 10
 2018 = 66727
 2052 = 43885
 1828 = 12275
 2402 = 1
 2003 = 10580
 823 = 29
 2594 = 1897
 2118 = 19815
 1226 = 89
 2087 = 17
 2020 = 50
 2088 = 19
 402 = 14
 2021 = 18
 1704 = 3
 2155 = 43
 777 = 6554
 1816 = 2686
 2124 = 7
 1721 = 4
 2125 = 3
 2157 = 8
 1166 =
