### ISSUE TITLE
Bank views not remembered

### ISSUE THREAD

**Issue by nyqvistatwork** [Jaliborc/Bagnon#1761]
**Which software were you running?**
 - Bagnon-10.1.4
 - Classic Hardcore

**Please describe the bug.**
Characters bank views are not remembered between game sessions and character switches.
Cannot view any alt character banks.

**Please describe how to reproduce it.**
1. Login to character A
2. Go to bank and open bank
3. Open Bagnon bank view and verify you can see character A bank in Bagnon bank
4. Switch character to character B
5. Open Bagnon bank view for character A

**Any Screenshots?**
![image](https://github.com/Jaliborc/Bagnon/assets/92366570/eaf751d3-ad01-4ce4-a3b5-53a6294ce69d)

**Comment by harrisonzalman** [comment]
Hi @Jaliborc, saw this issue as well - is there something we can do to avoid it?

**Comment by midnightsyntax** [comment]
> Hi @Jaliborc, saw this issue as well - is there something we can do to avoid it?

Yeah. Apparently the close reason was "completed last week" but some more info would be great @Jaliborc Like, is there a fix for it implemented in a version update available on Curseforged?

**Comment by ANaPhOrAX** [comment]
I doubt this is fixed at all, I had this issue just yesterday, and I've kept bagnon up to date. @Jaliborc
