### ISSUE TITLE
Lags when installed with PetTracker and pressing Mouse Keys

### ISSUE THREAD

**Issue by PJai** [Jaliborc/Bagnon#1810]
- Addon version name: Bagnon10.1.14 + PetTracker 10.1.1
 - Client used: Retail 10.1.7

**Have you read the changelog?**
yes

**Please describe the bug.**
When running both Addons Bagnon and PetTracker (without any other addons. ElvUI just enabled for Memory View) the Game has massive FPS Lags when pression mouse buttons (eg. middle mouse).
If I disable one of the two addons there are no lags.

**Please describe how to reproduce it.**
1. Log in WoW with Bagnon10.1.14 + PetTracker 10.1.1 enabled
2. Spam Middle Mouse Button
3. Game Lags and Bagnon produces multiple MB Addon Memory.
4. Enable for example EvlUI to view Memory

**Any Screenshots?**
![2023-10-14 18_30_05-World of Warcraft](https://github.com/Jaliborc/Bagnon/assets/22389964/08548149-3803-410d-8dd8-b902e65954d6)
![2023-10-14 18_39_42-World of Warcraft](https://github.com/Jaliborc/Bagnon/assets/22389964/ce8cd704-9675-4293-b6b3-f95b87bde43f)

**Error Logs are Important!**
no error messages shown

**Comment by HeroProc** [comment]
Bumping this: Verified with multiple others in guild. Disabling bagnon resolves the lag/stutter.

**Comment by Hrocks1** [comment]
Can confirm it, too. When i'm in Valdrakken and hammering my left and right mouse buttons the memory usage from bagnon goes over 200 MB and the game stutters.

**Comment by HeroProc** [comment]
This is still happening since version 10.1.15. Game lags every second when moving and bagnon memory usage balloons to 140mb+. Rolling back to 10.1.12 resolves this problem.

**Comment by Jaliborc** [comment]
It was a problem in Sushi-3.1. Fixed.

**Comment by Hrocks1** [comment]
Still the same problem in the latest release: 10.2.2 Bloated memory and stuttering, but after hours of playtime, not right from the start
