### ISSUE TITLE
Clean up error

### ISSUE THREAD

**Issue by exnoia** [Jaliborc/Bagnon#1815]
**Which software were you running?**
 - Addon version name: 10.1.15
 - Client used: WoTLK

**Have you read the changelog?**
 YES

**Please describe the bug.**
When I click to "clean"/"sort" my bags the error appears. However sometimes the error just doestn happens, and when it does if I use the Right mouse button to click kinda works.

**Please describe how to reproduce it.**
1. Open bag.
2. Click on "sort" icon

**Any Screenshots?**
            

**Error Logs are Important!**
            Here's the log.
4x BagBrother/core/api/sorting.lua:122: attempt to compare nil with number
[string "@BagBrother/core/api/sorting.lua"]:122: in function `GetSpaces'
[string "@BagBrother/core/api/sorting.lua"]:43: in function `Iterate'
[string "@BagBrother/core/api/sorting.lua"]:36: in function `Run'
[string "@BagBrother/core/api/sorting.lua"]:30: in function `Start'
[string "@BagBrother/core/classes/frameBase.lua"]:116: in function <BagBrother/core/classes/frameBase.lua:115>
[string "=(tail call)"]: ?
[string "@BagBrother/frames/containers/bank.lua"]:32: in function `SortItems'
[string "@BagBrother/core/classes/sortButton.lua"]:39: in function <BagBrother/core/classes/sortButton.lua:30>

Locals:
self = <table> {
 SendSignal = <function> defined @BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:82
 CanRun = <function> defined @BagBrother/core/api/sorting.lua:171
 RegisterMessage = <function> defined @Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 NewModule = <function> defined @BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:68
 GetOrder = <function> defined @ItemLock/Plugins/Plugin_Bagnon_Combuctor.lua:26
 Proprieties = <table> {
 }
 GetFamilies = <function> defined @BagBrother/core/api/sorting.lua:135
 target = BagnonBank1 {
 }
 SendMessage = <function> defined @Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:49
 Delaying = <function> defined @BagBrother/libs/MutexDelay-1.0/MutexDelay-1.0.lua:46
 Rule = <function> defined @BagBrother/core/api/sorting.lua:183
 UnregisterSignal = <function> defined @BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:78
 FitsIn = <function> defined @BagBrother/core/api/sorting.lua:175
 Move = <function> defined @BagBrother/core/api/sorting.lua:196
 GetSpaces = <function> defined @BagBrother/core/api/sorting.lua:110
 RegisterSignal = <function> defined @BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:74
 UnregisterAllMessages = <function> defined @Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 Run = <function> defined @BagBrother/core/api/sorting.lua:33
 UnregisterAllEvents = <function> defined @Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 Iterate = <function> defined @BagBrother/core/api/sorting.lua:42
 UnregisterMessage = <function> defined @Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 Stop = <function> defined @BagBrother/core/api/sorting.lua:103
 RegisterEvent = <function> defined @Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 Start = <function> defined @BagBrother/core/api/sorting.lua:23
 Delay = <function> defined @BagBrother/libs/MutexDelay-1.0/MutexDelay-1.0.lua:27
 UnregisterEvent = <function> defined @Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 Tag = "BAGNON_"
}
spaces = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 28 = <table> {
 }
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = -1
 2 = 5
 3 = 6
 4 = 7
 5 = 8
 6 = 9
 7 = 10
 8 = 11
}
(for control) = 2
_ = 2
bag = 5
family = 0
(for index) = 1
(for limit) = 20
(for step) = 1
slot = 1
item = <table> {
 itemName = ""
 hyperlink = "|cffffffff|Hitem:2770::::::::65:::::::::|h[]|h|r"
 isPaid = false
 hasLoot = false
 isNew = false
 iconFileID = 134566
 hasNoValue = false
 isLocked = false
 itemID = 2770
 isBound = false
 stackCount = 3
 isFiltered = false
 isReadable = false
}
id = 2770
name = nil
_ = nil
_ = nil
level = nil
_ = nil
_ = nil
_ = nil
stack = nil
equip = nil
_ = nil
_ = nil
class = nil
subclass = nil
(*temporary) = nil
(*temporary) = 2
(*temporary) = 2770
(*temporary) = "attempt to compare nil with number"
Search = <table> {
 IsUnusable = <function> defined @BagBrother/libs/ItemSearch-1.3/API.lua:46
 Filters = <table> {
 }
 BelongsToSet = <function> defined @BagBrother/libs/ItemSearch-1.3/API.lua:103
 IsQuestItem = <function> defined @BagBrother/libs/ItemSearch-1.3/API.lua:63
 Matches = <fu

**Comment by Faulkal** [comment]
Does it try to put regent in the regent bag repeatedly? Thats what happens to me, randomly it seems. Until I reload
