### ISSUE TITLE
Sorting Error

### ISSUE THREAD

**Issue by marulol** [Jaliborc/Bagnon#1816]
**Which software were you running?**
 - Addon version name:
 - Client used: [e.g. Vanilla 1.14.4, Retail PTR x.x.x, etc]

**Have you read the changelog?**
 Mark if read.

**Please describe the bug.**

Clicking sort brings up LUA error

**Please describe how to reproduce it.**

**Any Screenshots?**
If applicable, please add screenshots to help explain your problem.

**Error Logs are Important!**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears when reproducing the bug, please write here the first message (labelled 1/Many) that appeared. **:warning: By default, the last error message is shown, not the first!** You need to navigate back to the first error.

13x BagBrother/core/api/sorting.lua:122: attempt to compare nil with number
[string "@BagBrother/core/api/sorting.lua"]:122: in function `GetSpaces'
[string "@BagBrother/core/api/sorting.lua"]:43: in function `Iterate'
[string "@BagBrother/core/api/sorting.lua"]:36: in function `Run'
[string "@BagBrother/core/api/sorting.lua"]:30: in function `Start'
[string "@BagBrother/core/classes/frameBase.lua"]:116: in function <BagBrother/core/classes/frameBase.lua:115>
[string "=(tail call)"]: ?
[string "@BagBrother/frames/containers/inventory.lua"]:105: in function `SortItems'
[string "@BagBrother/core/classes/sortButton.lua"]:39: in function <BagBrother/core/classes/sortButton.lua:30>

Locals:
self = <table> {
 SendSignal = <function> defined @BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:82
 CanRun = <function> defined @BagBrother/core/api/sorting.lua:171
 RegisterMessage = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 NewModule = <function> defined @BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:68
 GetOrder = <function> defined @BagBrother/core/api/sorting.lua:150
 Proprieties = <table> {
 }
 GetFamilies = <function> defined @BagBrother/core/api/sorting.lua:135
 target = BagnonInventory1 {
 }
 SendMessage = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:49
 Delaying = <function> defined @BagBrother/libs/MutexDelay-1.0/MutexDelay-1.0.lua:46
 Rule = <function> defined @BagBrother/core/api/sorting.lua:183
 UnregisterSignal = <function> defined @BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:78
 FitsIn = <function> defined @BagBrother/core/api/sorting.lua:175
 Move = <function> defined @BagBrother/core/api/sorting.lua:196
 GetSpaces = <function> defined @BagBrother/core/api/sorting.lua:110
 RegisterSignal = <function> defined @BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:74
 UnregisterAllMessages = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 Run = <function> defined @BagBrother/core/api/sorting.lua:33
 UnregisterAllEvents = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 Iterate = <function> defined @BagBrother/core/api/sorting.lua:42
 UnregisterMessage = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 Stop = <function> defined @BagBrother/core/api/sorting.lua:103
 RegisterEvent = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 Start = <function> defined @BagBrother/core/api/sorting.lua:23
 Delay = <function> defined @BagBrother/libs/MutexDelay-1.0/MutexDelay-1.0.lua:27
 UnregisterEvent = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 Tag = "BAGNON_"
}
spaces = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 28 = <table> {
 }
 29 = <table> {
 }
 30 = <table> {
 }
 31 = <table> {
 }
 32 = <table> {
 }
 33 = <table> {
 }
 34 = <table> {
 }
 35 = <table> {
 }
 36 = <table> {
 }
 37 = <table> {
 }
 38 = <table> {
 }
 39 = <table> {
 }
 40 = <table> {
 }
 41 = <table> {
 }
 42 = <table> {
 }
 43 = <table> {
 }
 44 = <table> {
 }
 45 = <table> {
 }
 46 = <table> {
 }
 47 = <table> {
 }
 48 = <table> {
 }
 49 = <table> {
 }
 50 = <table> {
 }
 51 = <table> {
 }
 52 = <table> {
 }
 53 = <table> {
 }
 54 = <table> {
 }
 55 = <table> {
 }
 56 = <table> {
 }
 57 = <table> {
 }
 58 = <table> {
 }
 59 = <table> {
 }
 60 = <table> {
 }
 61 = <table> {
 }
 62 = <table> {
 }
 63 = <table> {
 }
 64 = <table> {
 }
 65 = <table> {
 }
 66 = <table> {
 }
 67 = <table> {
 }
 68 = <table> {
 }
 69 = <table> {
 }
 70 = <table> {
 }
 71 = <table> {
 }
 72 = <table> {
 }
 73 = <table> {
 }
 74 = <table> {
 }
 75 = <table> {
 }
 76 = <table> {
 }
 77 = <table> {
 }
 78 = <table> {
 }
 79 = <table> {
 }
 80 = <table> {
 }
 81 = <table> {
 }
 82 = <table> {
 }
 83 = <table> {
 }
 84 = <table> {
 }
 85 = <table> {
 }
 86 = <table> {
 }
 87 = <table> {
 }
 88 = <table> {
 }
 89 = <table> {
 }
 90

**Comment by Jaliborc** [comment]
Cool, GetItemInfo can fail to return info. Good to know (yeah, the client fibbed there).
