### ISSUE TITLE
General search causing multiple Lua errors

### ISSUE THREAD

**Issue by kinghq1** [Jaliborc/Bagnon#1823]
**Which software were you running?**
 - Addon version name:  Latest version
 - Client used: WoW 10.2.0 (52188)

**Have you read the changelog?**
Yes

**Please describe the bug.**
Hit B to open bags.  Click on Search feature, type in ANY letter and it immediately generates Lua errors

**Please describe how to reproduce it.**
See above

**Any Screenshots?**

<img width="423" alt="Bagnon Lua issue" src="https://github.com/Jaliborc/Bagnon/assets/116727797/60808e38-7992-4d95-838c-f5778fce53a9">

**Error Logs are Important!**
As noted in the Screenshot, it says multiple.  Lua viewer shows 2 additional Addons with errors.  I disabled both those.  Now when I attempt search, I do not get the popup window, BUT still getting Lua errors.  I'll included a Before and After output just to make sure I cover all the bases.
ALL of the errors are linking items in inventory.  IF I move that item to my Bank, the next Lua error has another item linked.  After a couple moves, realized it was most likely going to point to ANYTHING in my inventory.  I can type a character and the count jumps hundreds

Before:

Message: ...ce/AddOns/BagBrother/libs/ItemSearch-1.3/Filters.lua:44: attempt to index field 'args' (a nil value)
Time: Wed Nov 29 10:24:39 2023
Count: 671
Stack: ...ce/AddOns/BagBrother/libs/ItemSearch-1.3/Filters.lua:44: attempt to index field 'args' (a nil value)
[string "@Interface/AddOns/BagBrother/libs/ItemSearch-1.3/Filters.lua"]:44: in function <...ce/AddOns/BagBrother/libs/ItemSearch-1.3/Filters.lua:37>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/BagBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua"]:115: in function `Filter'
[string "@Interface/AddOns/BagBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua"]:87: in function `Match'
[string "@Interface/AddOns/BagBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua"]:49: in function `MatchAny'
[string "@Interface/AddOns/BagBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua"]:39: in function <...agBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua:37>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/BagBrother/addons/core/classes/item.lua"]:297: in function `?'
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua"]:83: in function `SendSignal'
[string "@Interface/AddOns/Bagnon/src/searchFrame.lua"]:78: in function <Interface/AddOns/Bagnon/src/searchFrame.lua:74>

Locals: self = <table> {
 match = <function> defined @Interface/AddOns/BagBrother/libs/ItemSearch-1.3/Filters.lua:37
 canSearch = <function> defined @Interface/AddOns/BagBrother/libs/ItemSearch-1.3/Filters.lua:33
 onlyTags = false
 tags = <table> {
 }
}
item = <table> {
 location = <table> {
 }
 link = "[Bow of the Dragon Hunters |A:Professions-ChatIcon-Quality-Tier4:17:17::1|a]"
}
_ = nil
search = "leftc"
where = <table> {
 slotIndex = 15
 bagID = 3
}
data = <table> {
 dataInstanceID = 5599
 type = 0
 isAzeriteItem = false
 guid = "Item-53-0-4000000B130AC0E4"
 id = 193449
 isAzeriteEmpoweredItem = false
 isCorruptedItem = false
 lines = <table> {
 }
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
}
(for control) = 1
i = 1
line = <table> {
 leftColor = <table> {
 }
 type = 29
 leftText = "Bow of the Dragon Hunters"
}
(*temporary) = <function> defined @Interface/AddOns/BagBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua:132
(*temporary) = <table> {
 object = <table> {
 }
 filters = <table> {
 }
 OR = "or"
 NOT_MATCH = "not"
 NOT = "Not"
 Find = <function> defined @Interface/AddOns/BagBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua:132
 Match = <function> defined @Interface/AddOns/BagBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua:55
 MatchAny = <function> defined @Interface/AddOns/BagBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua:47
 ACCENTS = <table> {
 }
 MatchAll = <function> defined @Interface/AddOns/BagBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua:37
 UseFilter = <function> defined @Interface/AddOns/BagBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua:122
 Compare = <function> defined @Interface/AddOns/BagBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua:152
 Matches = <function> defined @Interface/AddOns/BagBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua:28
 Filter = <function> defined @Interface/AddOns/BagBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua:100
 Clean = <func

After:

Message: ...ce/AddOns/BagBrother/libs/ItemSearch-1.3/Filters.lua:44: attempt to index field 'args' (a nil value)
Time: Wed Nov 29 10:46:14 2023
Count: 329
Stack: ...ce/AddOns/BagBrother/libs/ItemSearch-1.3/Filters.lua:44: attempt to index field 'args' (a nil value)
[string "@Interface/AddOns/BagBrother/libs/ItemSearch-1.3/Filters.lua"]:44: in function <...ce/AddOns/BagBrother/libs/ItemSearch-1.3/Filters.lua:37>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/BagBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua"]:115: in function `Filter'
[string "@Interface/AddOns/BagBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua"]:87: in function `Match'
[string "@Interface/AddOns/BagBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua"]:49: in function `MatchAny'
[string "@Interface/AddOns/BagBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua"]:39: in function <...agBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua:37>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/BagBrother/addons/core/classes/item.lua"]:297: in function `?'
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua"]:83: in function `SendSignal'
[string "@Interface/AddOns/Bagnon/src/searchFrame.lua"]:78: in function <Interface/AddOns/Bagnon/src/searchFrame.lua:74>

Locals: self = <table> {
 match = <function> defined @Interface/AddOns/BagBrother/libs/ItemSearch-1.3/Filters.lua:37
 canSearch = <function> defined @Interface/AddOns/BagBrother/libs/ItemSearch-1.3/Filters.lua:33
 onlyTags = false
 tags = <table> {
 }
}
item = <table> {
 location = <table> {
 }
 link = "[Ward of Igira]"
}
_ = nil
search = "lef"
where = <table> {
 slotIndex = 29
 bagID = 2
}
data = <table> {
 dataInstanceID = 4117
 type = 0
 isAzeriteItem = false
 guid = "Item-53-0-4000000B9199E6D2"
 id = 203430
 isAzeriteEmpoweredItem = false
 isCorruptedItem = false
 lines = <table> {
 }
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
}
(for control) = 1
i = 1
line = <table> {
 leftColor = <table> {
 }
 type = 29
 leftText = "Ward of Igira"
}
(*temporary) = <function> defined @Interface/AddOns/BagBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua:132
(*temporary) = <table> {
 object = <table> {
 }
 filters = <table> {
 }
 OR = "or"
 NOT_MATCH = "not"
 NOT = "Not"
 Find = <function> defined @Interface/AddOns/BagBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua:132
 Match = <function> defined @Interface/AddOns/BagBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua:55
 MatchAny = <function> defined @Interface/AddOns/BagBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua:47
 ACCENTS = <table> {
 }
 MatchAll = <function> defined @Interface/AddOns/BagBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua:37
 UseFilter = <function> defined @Interface/AddOns/BagBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua:122
 Compare = <function> defined @Interface/AddOns/BagBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua:152
 Matches = <function> defined @Interface/AddOns/BagBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua:28
 Filter = <function> defined @Interface/AddOns/BagBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua:100
 Clean = <function> defined @Interface/AddOns/BagBrother/libs/CustomSearch-1.0/CustomSearch-1.0.lua:141
}
(*temporary) = "lef"
(*temporary) = nil
(*temporary) = "attempt to index field 'args' (a nil value)"
C = <table> {
 TooltipInfo = <table> {
 }
 IsItemCache = <table> {
 }
 CurrencyInfo = <table> {
 }
 Container = <t

**Comment by Jaliborc** [comment]
Out of date
