### ISSUE TITLE
BagBrother Popup.lua:133 Error

### ISSUE THREAD

**Issue by evilgodly** [Jaliborc/Bagnon#1827]
**Which software were you running?**
 - Addon version name: 10.2.4
 - Client used: Retail

**Have you read the changelog?**
Read

**Please describe the bug.**

**Please describe how to reproduce it.**
Got this error when trying to purchase bank storage slots, specifically the reagents parts.

**Any Screenshots?**
If applicable, please add screenshots to help explain your problem.

**Error Logs are Important!**
6x ...s/BagBrother/libs/Sushi-3.2-1/classes/groups/Popup.lua:133: attempt to concatenate field 'text' (a nil value)
[string "@BagBrother/libs/Sushi-3.2-1/classes/groups/Popup.lua"]:133: in function <...s/BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:109>
[string "=(tail call)"]: ?
[string "@BagBrother/core/classes/bag.lua"]:206: in function `Purchase'
[string "@BagBrother/core/classes/bag.lua"]:151: in function <BagBrother/core/classes/bag.lua:139>

Locals:
self = <table> {
 Cancel = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:63
 __super = <table> {
 }
 GetActive = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:79
 __base = <table> {
 }
 __version = 3
 IterateActive = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:87
 Toggle = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:59
 __index = <table> {
 }
 Size = 420
 Accept = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:183
 Max = 6
 OnKeyDown = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:209
 External = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:55
 __frames = <table> {
 }
 Populate = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:152
 __count = 1
 New = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:109
 Release = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:190
 Active = <table> {
 }
 Construct = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:94
 Organize = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:68
}
input = <table> {
 button2 = "No"
 OnAccept = <function> defined =[C]:-1
 button1 = "Yes"
 money = 1000000
}
info = <table> {
 button2 = "No"
 OnAccept = <function> defined =[C]:-1
 button1 = "Yes"
 money = 1000000
}
id = <table> {
 button2 = "No"
 OnAccept = <function> defined =[C]:-1
 button1 = "Yes"
 money = 1000000
}
f = Frame {
 button2 = "No"
 MoneyInput = table: 0000021DF3BA3210MoneyInput {
 }
 button1 = "Yes"
 calls = <table> {
 }
 money = 1000000
 0 = <userdata>
 Children = <table> {
 }
 Icon = Texture {
 }
}
(*temporary) = nil
(*temporary) = "|n100|TInterface\MoneyFrame\UI-GoldIcon:14:14:2:0|t"
(*temporary) = "100|TInterface\MoneyFrame\UI-GoldIcon:14:14:2:0|t"
(*temporary) = 1000000
(*temporary) = "100|TInterface\MoneyFrame\UI-GoldIcon:14:14:2:0|t"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate field 'text' (a nil value)"
Popup = <table> {
 Cancel = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:63
 __super = <table> {
 }
 GetActive = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:79
 __base = <table> {
 }
 __version = 3
 IterateActive = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:87
 Toggle = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:59
 __index = <table> {
 }
 Size = 420
 Accept = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:183
 Max = 6
 OnKeyDown = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:209
 External = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:55
 __frames = <table> {
 }
 Populate = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:152
 __count = 1
 New = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:109
 Release = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:190
 Active = <table> {
 }
 Construct = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:94
 Organize = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:68
}

**Comment by thefowles1** [comment]
Also receiving the same error.

`4x ...s/BagBrother/libs/Sushi-3.2-1/classes/groups/Popup.lua:133: attempt to concatenate field 'text' (a nil value)
[string "@BagBrother/libs/Sushi-3.2-1/classes/groups/Popup.lua"]:133: in function <...s/BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:109>
[string "=(tail call)"]: ?
[string "@BagBrother/core/classes/bag.lua"]:206: in function `Purchase'
[string "@BagBrother/core/classes/bag.lua"]:151: in function <BagBrother/core/classes/bag.lua:139>

Locals:
self = <table> {
 Cancel = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:63
 __super = <table> {
 }
 GetActive = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:79
 __base = <table> {
 }
 __version = 5
 IterateActive = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:87
 Toggle = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:59
 __index = <table> {
 }
 Size = 420
 Accept = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:183
 Max = 6
 OnKeyDown = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:209
 External = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:55
 __frames = <table> {
 }
 Populate = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:152
 __count = 1
 New = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:109
 Release = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:190
 Active = <table> {
 }
 Construct = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:94
 Organize = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:68
}
input = <table> {
 button2 = "No"
 OnAccept = <function> defined =[C]:-1
 button1 = "Yes"
 money = 1000000
}
info = <table> {
 button2 = "No"
 OnAccept = <function> defined =[C]:-1
 button1 = "Yes"
 money = 1000000
}
id = <table> {
 button2 = "No"
 OnAccept = <function> defined =[C]:-1
 button1 = "Yes"
 money = 1000000
}
f = Frame {
 button2 = "No"
 MoneyInput = table: 0000024264CEA340MoneyInput {
 }
 button1 = "Yes"
 calls = <table> {
 }
 money = 1000000
 0 = <userdata>
 Children = <table> {
 }
 Icon = Texture {
 }
}
(*temporary) = nil
(*temporary) = "|n100|TInterface\MoneyFrame\UI-GoldIcon:14:14:2:0|t"
(*temporary) = "100|TInterface\MoneyFrame\UI-GoldIcon:14:14:2:0|t"
(*temporary) = 1000000
(*temporary) = "100|TInterface\MoneyFrame\UI-GoldIcon:14:14:2:0|t"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate field 'text' (a nil value)"
Popup = <table> {
 Cancel = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:63
 __super = <table> {
 }
 GetActive = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:79
 __base = <table> {
 }
 __version = 5
 IterateActive = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:87
 Toggle = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:59
 __index = <table> {
 }
 Size = 420
 Accept = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:183
 Max = 6
 OnKeyDown = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:209
 External = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:55
 __frames = <table> {
 }
 Populate = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:152
 __count = 1
 New = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:109
 Release = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:190
 Active = <table> {
 }
 Construct = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:94
 Organize = <function> defined @BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:68
}
`

**Comment by AemoSucks** [comment]
same issue, same after-effects with ESC key.

Date: 2023-12-24 13:46:22
ID: 1
Error occured in: Global
Count: 1
Message: ...s/BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua line 133:
   attempt to concatenate field 'text' (a nil value)
Debug:
   [string "=[C]"]: ?
   [string "@Interface/AddOns/BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua"]:133:
      ...s/BagBrother/libs/Sushi-3.2/classes/groups/Popup.lua:109
   [string "=(tail call)"]: ?
   [string "@Interface/AddOns/BagBrother/core/classes/bag.lua"]:206: Purchase()
   [string "@Interface/AddOns/BagBrother/core/classes/bag.lua"]:151:
      Interface/AddOns/BagBrother/core/classes/bag.lua:139
Locals:
(*temporary) = <function> defined =[C]:-1

AddOns:
  Swatter, v9.1.BETA.5.13 (OneMawTime)
  AllTheThings, vDF-3.8.9a
  AskMrRobot, v131
  Auctioneer, v9.1.BETA.5.13 (OneMawTime)
  AuctioneerStatsOverTime, v9.1.BETA.5.13 (OneMawTime)
  AuctioneerUtilDealFinder, v9.1.BETA.5.13 (OneMawTime)
  AuctioneerUtilValuer, v9.1.BETA.5.13 (OneMawTime)
  BagBrother, v
  Bagnon, v10.2.7
  DBMCore, v5751d56
  DBMStatusBarTimers, v5751d56
  DBMVPVEM, v4a6af0c
  Decursive, v2.7.14
  Details, v#Details.20231219.12111.155
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Dominos, v10.2.1
  DominosCast, v
  DominosProgress, v
  DominosRoll, v
  Enchantrix, v9.1.BETA.5.13 (OneMawTime)
  GatherMate2, v1.48.8
  Glider, v0.2.5
  GTFO, v5.6.1
  HandyNotes, vv1.6.17
  HandyNotesArgus, vv0.39
  HandyNotesBattleForAzeroth, v18
  HandyNotesBattleForAzerothTreasures, vv31
  HandyNotesBrokenShore, vv1.52
  HandyNotesBurningCrusade, vv5
  HandyNotesDraenor, v3.6
  HandyNotesDragonflight, v45
  HandyNotesDragonflightTreasures, vv53
  HandyNotesDragonGlyphs, v0.1.0
  HandyNotesDungeonLocations, v2.2
  HandyNotesLegionTreasures, vv34
  HandyNotesMistsOfPandariaTreasures, vv26
  HandyNotesNetherwingEggs, v2.05
  HandyNotesOribos, vv28
  HandynotesPandaria, v1.5.11
  HandyNotesShadowlands, v58
  HandyNotesShadowlandsTreasures, vv74
  HandyNotesSuramarShalAranTelemancy, vv1.44
  HandyNotesTreasureHunter, vv34
  HandyNotesValdrakken, vv10
  HandyNotesWrathOfTheLichKing, vv13
  Informant, v9.1.BETA.5.13 (OneMawTime)
  LeatrixMaps, v10.2.06
  Pawn, v2.8.7
  Prat30, v3.9.43
  Prat30Libraries, v
  PremadeGroupsFilter, v5.2.1
  QEDungeonTips, v6
  RaiderIO, v10.2.0 (v202312240945)
  RaiderIODBUSF, v
  RaiderIODBUSM, v
  RaiderIODBUSR, v
  RareScanner, v10.2.0.12
  Routes, vv1.7.4
  ShadowedUnitFrames, vv4.4.6
  SlideBar, v9.1.BETA.5.13 (OneMawTime)
  Stubby, v9.1.BETA.5.13 (OneMawTime)
  TomTom, vv3.5.4-release
  WeakAuras, v5.8.7
  WorldQuestTracker, vv10.2.0.489-Retail
  ZygorGuidesViewer, v9.0
  BlizRuntimeLib v10.2.0.52649(US) <enUS>
  (ck=813)

**Comment by Jaliborc** [comment]
Fixed internally
