### ISSUE TITLE
Can not send link of cached items

### ISSUE THREAD

**Issue by znuaile** [Jaliborc/Bagnon#1829]
**Which software were you running?**
 - Addon version name:
 - Client used: [Vanilla 1.15]

**Have you read the changelog?**
 Mark if read. --Yes

**Please describe the bug.**
Can not send cached item's link . While shift+left button on a cached item , only a part of item link was inserted to chat edit box.

**Please describe how to reproduce it.**
1. open send chat msg box 
2. Click on cached items (cached bank)with shift
3. See error

**Any Screenshots?**
no

**Error Logs are Important!**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears when reproducing the bug, please write here the first message (labelled 1/Many) that appeared. **:warning: By default, the last error message is shown, not the first!** You need to navigate back to the first error.

**Comment by Jaliborc** [comment]
Fixed internally
