### ISSUE TITLE
Hide bagnon key bags: wrath classic

### ISSUE THREAD

**Issue by mk4reiko** [Jaliborc/Bagnon#1835]
**Is your feature request related to a problem? If so, please describe.**
the key bags are displayed together with all the inventory and this takes up space and is annoying in the interface, ver wrath classic.

**Describe the solution you'd like.**
it would be nice if the bagnon would only show the item bags and show the key bags only when it decides to, something like it was in wotlk 3.3.5a.

**Describe other alternatives you've considered.**
in any case include in addon options a button to hide/show key bags.

**Any additional context?**
I have screenshots.

this is how it should work...
![llaves-bagnon](https://github.com/Jaliborc/Bagnon/assets/154925452/3b80ffba-5ead-47d3-a1df-52a84bcab34d)
![bagnon-sin_llaves](https://github.com/Jaliborc/Bagnon/assets/154925452/b10e938b-d640-4bc3-a4f5-f84d7de26abb)

and this is what should be avoided:
![bagnon-con_llaves](https://github.com/Jaliborc/Bagnon/assets/154925452/f3f65c9f-24ca-43a5-a2aa-b0716594b941)

**Comment by Jaliborc** [comment]
Click on the key bag.

**Comment by mk4reiko** [comment]
I saw it, thank you
