### ISSUE TITLE
Bagbrother error after installing latest Bagnon update

### ISSUE THREAD

**Issue by astothialo** [Jaliborc/Bagnon#1842]
Bagnon was working fine prior to latest update.

**Which software were you running?**
10.2.10
Classic SoD

**Have you read the changelog?**
yes

**Please describe the bug.**
Error message on startup.

**Please describe how to reproduce it.**
see above

**Error Logs are Important!**
Message: .../AddOns/BagBrother/core/features/updateDetection.lua:66: bad argument #3 to 'format' (string expected, got nil)
Time: Fri Jan  5 13:29:19 2024
Count: 1
Stack: .../AddOns/BagBrother/core/features/updateDetection.lua:66: bad argument #3 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@Interface/AddOns/BagBrother/core/features/updateDetection.lua"]:66: in function `Popup'
[string "@Interface/AddOns/BagBrother/core/features/updateDetection.lua"]:35: in function `?'
[string "@Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua"]:20: in function <...dOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua"]:56: in function <...dOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <Interface/AddOns/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:391: in function `UIParentLoadAddOn'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:418: in function `CombatLog_LoadUI'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:722: in function <Interface_Vanilla/FrameXML/UIParent.lua:689>
[string "=[C]"]: ?

Locals: (*temporary) = "You might be running an outdated %s version! Someone in your party or guild reported having %s, please update if true."
(*temporary) = "Bagnon"
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by evilgodly** [comment]
im getting this same error as well in Retail WoW running Bagnon v10.2.10

1x BagBrother/core/features/updateDetection.lua:66: bad argument #3 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@BagBrother/core/features/updateDetection.lua"]:66: in function `Popup'
[string "@BagBrother/core/features/updateDetection.lua"]:35: in function `?'
[string "@BagBrother/libs/WildAddon-1.0-2/WildAddon-1.0.lua"]:20: in function <...dOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@BagBrother/libs/WildAddon-1.0-2/WildAddon-1.0.lua"]:56: in function <...dOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:542: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:681: in function `TimeManager_LoadUI'
[string "@FrameXML/UIParent.lua"]:1527: in function <FrameXML/UIParent.lua:1407>
[string "=[C]"]: ?

Locals:
(*temporary) = "|cffff0000You might be running an outdated |cffffffff%s|r version! Someone in your party or guild reported having |cffffffff%s|r, please update if true.|r"
(*temporary) = "Bagnon"
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by Jaliborc** [comment]
Fixed internally
