### ISSUE TITLE
ESC key no longer working (classic ERA)

### ISSUE THREAD

**Issue by Spotnick2** [Jaliborc/Bagnon#1863]
I don't think I have to fill the full report, but I noticed in  10.2.14  it was said shortcuts have changed, well since 10.2.15 I can't close my bags using the ESC key like always and it's annoying the hell out of me, going back to  10.2.13 fixed it.

Is it a bug or is there a place to set that back?

**Comment by jakkapil** [comment]
yeah have same issue, reverting to 10.2.14 fixed it for me, but would also like to know if bug or setting, etc.

**Comment by Rennerie** [comment]
+1

**Comment by opakaa** [comment]
also having this issue with 10.2.15.  Reinstalling 10.2.14 fixed this issue.

**Comment by DigitalHype** [comment]
This isn't only affecting classic. Same problem in retail.

**Comment by PiniponSelvagem** [comment]
Same issue in retail

**Comment by Coytis** [comment]
This is effecting all versions of the game with the update. Looking in the options yields no check box to enable/disable esc to close bags, feels like a bug.

**Comment by tomwng** [comment]
What's happening to me is:

- If the bag is open, esc won't close the bag but will open the menu;
- If both the bank and the bag are open, esc will close the bag but not the bank;
- If both the vendor and the bag are open, esc will close both.

Addon version 10.2.15 with WOW retail 10.2.5 (53007).

**Comment by mtpbzz** [comment]
+1 ESC no longer closes my bag/bank frame

**Comment by Masumia** [comment]
Retail here with same issue.

**Comment by Treacherouz** [comment]
Same issue here! Retail. Thanks in advance for a fix!

**Comment by LarryThiessen** [comment]
Same Issue > Love the Addon!

**Comment by MSalive** [comment]
Add another, Same Issue!!!  Started yesterday and it's damn annoying.  Especially because I've spent several hours trying to figure it out.  So happy to see it's not just me  :)

**Comment by Starbuck-OS** [comment]
Same issue on SOD classic, and wrath classic, reverted to previous version to fix.

**Comment by RuthlessWorm** [comment]
I want to add here, discussed this ESC bug with guildmates (since i was on previous version we noticed the same).

Guildmate enjoyed the feature of not closing bags with ESC, would be nice to make it a checkbox for him.

**Comment by Robersillo** [comment]
Same issue for me

**Comment by EJames1965** [comment]
Same. v.13 is the last version that works properly for me with <esc> closing the bag UI.

**Comment by voidzone** [comment]
Appears resolved as of 10.2.16
