### ISSUE TITLE
Bank Reagent Bank using Inventory Reagent Bag functionaility

### ISSUE THREAD

**Issue by pashionmods** [Jaliborc/Bagnon#1865]
**Which software were you running?**
 - Addon version name: 10.2.10 and later
 - Client used: [e.g. Vanilla 1.14.4, Retail PTR x.x.x, etc]: Retail 10.2.5

**Have you read the changelog?** Yes

**Please describe the bug.**
With the release of 10.2.10, the Reagent Bank is using the same functionality of the inventory reagent bag, where it is displayed not as a separate tab but as an additional bag. 

**Please describe how to reproduce it.**
1. Go to Bank.
2. Click on Reagent Bank Icon
3. See bug

**Any Screenshots?**
If applicable, please add screenshots to help explain your problem.

**Comment by Jaliborc** [comment]
It has always been an additional bag in Bagnon, and always will be.
