### ISSUE TITLE
WoW Classic Era V1.15.0 - Bags no longer close with "ESC" button

### ISSUE THREAD

**Issue by maximus210793** [Jaliborc/Bagnon#1866]
Hi,
since the latest update 1.15.0 (1/20/2024 (latest)), I can no longer close my open bags with "ESC" button.
The last time it worked propperly was version 1.15.0 (1/20/2024 (2nd last release.))
Thank you for fixing it.

**Comment by GitMestra** [comment]
Already reported:

https://github.com/Jaliborc/Bagnon/issues/1863
