### ISSUE TITLE
Bagnon preventing from using vendors, banks, mailbox, AH, etc. while in combat

### ISSUE THREAD

**Issue by Speaker1264** [Jaliborc/Bagnon#1873]
**Which software were you running?**
 - Addon version name: Bagnon-10.2.18
 - Client used: WotLK Classic and Classic Era/SoD

**Have you read the changelog?**
Yes

**Please describe the bug.**
Cannot interact with vendors, banks, mailboxes, auction house, etc. while in combat. No Lua errors, but the chat window simply says the following, "Interface action failed because of an AddOn"

**Please describe how to reproduce it.**
1. Get in combat through any various method, such as popping bloodrage on a warrior.
2. Try opening the mailbox, or a vendor, etc.

**Error Logs are Important!**
No Lua errors pop up when this happens

**Comment by Jaliborc** [comment]
Yeah, addons aren't allowed to operate in combat. That's just how WoW works.
