### ISSUE TITLE
Bagnon messing with Weakauras since latest updates.

### ISSUE THREAD

**Issue by dnlpz** [Jaliborc/Bagnon#1874]
until now

not able to change color in the palette
certain weakauras straight up not working
blizzard warning in the middle of the screen about addons experiencing a large number of problems

**Comment by Master0fEvil** [comment]
same thing here, reverting to previous version fixes it

error message:
Date: 2024-01-30 07:04:53
ID: 2
Error occured in: Global
Count: 1
Message: ...Libs/AceGUI-3.0/widgets/AceGUIWidget-ColorPicker.lua line 71:
   attempt to call method 'GetColorAlpha' (a nil value)
Debug:
   [string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/widgets/AceGUIWidget-ColorPicker.lua"]:71: opacityFunc()
   [string "*ColorPickerFrame.xml:133_OnValueChanged"]:2:
      [string "*ColorPickerFrame.xml:133_OnValueChanged"]:1
Locals:
r = 1
g = 1
b = 1
(*temporary) = nil
(*temporary) = ColorPickerFrame {
 0 = <userdata>
 isCTHooked = true
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 RightEdge = Texture {
 }
 SetupColorPickerAndShow = <function> defined @Interface/AddOns/BagBrother/libs/Sushi-3.2/classes/checks/Color.lua:23
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 hasOpacity = true
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 opacity = 1
 func = <function> defined @Interface/AddOns/Masque/Libs/AceGUI-3.0/widgets/AceGUIWidget-ColorPicker.lua:62
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 cancelFunc = <function> defined @Interface/AddOns/Masque/Libs/AceGUI-3.0/widgets/AceGUIWidget-ColorPicker.lua:76
 previousValues = <table> {
 }
 TopEdge = Texture {
 }
 BottomLeftCorner = Texture {
 }
 TopRightCorner = Texture {
 }
 Center = Texture {
 }
 backdropInfo = <table> {
 }
 TopLeftCorner = Texture {
 }
 BottomEdge = Texture {
 }
 BottomRightCorner = Texture {
 }
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 opacityFunc = <function> defined @Interface/AddOns/Masque/Libs/AceGUI-3.0/widgets/AceGUIWidget-ColorPicker.lua:69
}
(*temporary) = "attempt to call method 'GetColorAlpha' (a nil value)"
ColorCallback = <function> defined @Interface/AddOns/Masque/Libs/AceGUI-3.0/widgets/AceGUIWidget-ColorPicker.lua:17
self = <table> {
 a = 1
 b = 1
 parent = <table> {
 }
 g = 1
 OnAcquire = <function> defined @Interface/AddOns/Masque/Libs/AceGUI-3.0/widgets/AceGUIWidget-ColorPicker.lua:120
 SetDisabled = <function> defined @Interface/AddOns/Masque/Libs/AceGUI-3.0/widgets/AceGUIWidget-ColorPicker.lua:147
 userdata = <table> {
 }
 base = <table> {
 }
 HasAlpha = true
 type = "ColorPicker"
 SetHasAlpha = <function> defined @Interface/AddOns/Masque/Libs/AceGUI-3.0/widgets/AceGUIWidget-ColorPicker.lua:143
 r = 1
 text = FontString {
 }
 colorSwatch = Texture {
 }
 events = <table> {
 }
 AceGUIWidgetVersion = 27
 frame = Button {
 }
 SetLabel = <function> defined @Interface/AddOns/Masque/Libs/AceGUI-3.0/widgets/AceGUIWidget-ColorPicker.lua:131
 SetColor = <function> defined @Interface/AddOns/Masque/Libs/AceGUI-3.0/widgets/AceGUIWidget-ColorPicker.lua:135
}

AddOns:
  ClassColors, v8.0.0.1
  mMTMediaPack, v1.10
  Swatter, v3.4.6817 (SwimmingSeadragon)
  ACP, v3.5.9
  AddOnSkins, v4.68
  AdvancedInterfaceOptions, v1.8.14
  AIVoiceOver, v1.4.3
  AIVoiceOverDataVanilla, v0.1
  Atlas, vv1.52.08
  AtlasBattlegrounds, vv1.52.03
  AtlasClassicWoW, vv1.52.05
  AtlasDungeonLocs, vv1.52.04
  AtlasOutdoorRaids, vv1.52.04
  AtlasTransportation, vv1.52.04
  AtlasLootClassic, vv1.1.1
  AtlasLootClassicData, vv1.1.1
  AtlasLootClassicDungeonsAndRaids, vv1.1.1
  AtlasLootClassicMaps, vv1.0.0
  AtlasQuest, v4.13.05
  Attune, v255
  Auctionator, v10.2.16
  BagBrother, v
  Bagnon, v10.2.18
  BagnonGarbage, v2.0.62-Release
  BagnonItemLevel, v2.0.87-Release
  BagnonMasque, v10
  BagnonScrap, v10.1.2
  BigDebuffs, vv11.38
  BigWigs, vv317.1
  BigWigsCountdownOverwatch, v1.2.24
  BlizzMove, vv3.5.21
  BuffOverlay, vv12.6.20
  BuffTimers, vv1.11.9
  CharacterStatsClassic, v3.8.7
  ClamPulp, v1.0
  ClassicAuraDurations, v3.4.0
  ClassicBestiary, v1.0.4
  ClassicHealPrediction, vv1.8.5
  ColorPickerPlus, v
  Dejunk, v1.7.2
  Details, v#Details.20240122.12237.155
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Diminish, vv2.6.8
  DiminishOptions, vv2.6.8
  DisableAutoAddSpells, v8.0.0.1
  DynamicCam, v2.6.2
  ElvUI, v13.55
  ElvUILibraries, v13.55
  ElvUILuckyoneUI, v2.50
  ElvUImMediaTag, v3.27
  ElvUINoBorders, v1.2.2
  ErrorMonster, vv10.2.2
  FishingBuddy, v0.9.4
  GatherMate2, v1.47.2-classic
  GTFO, v5.6.1
  HandyNotes, vv1.6.17
  HandyNotesFlightMastersClassic, v1.12b
  HandyNotesSummerFestival, v1.1
  HandyNotesWorldMapButton, v100205.02-Release
  HHTD, v2.4.16
  HidingBar, vv1.15.4
  InFlightLoad, v1.13.005
  ItemRack, v3.77
  ItemTooltipProfessionIcons, vv1.3.2-Classic
  LeatrixMaps, v1.15.13
  LeatrixPlus, v1.15.13
  LFGBulletinBoard, v3.12
  LibClassicSwingTimerAPI, v2.0.4
  LibSharedMedia30, v3.0-145
  LoseControl, v1.20
  MacroToolkit, vv2.2.5
  MacroToolkitIcons, vv2.2.5
  Masque, v10.2.5
  MasqueApathy, v10.2.5
  MasqueCaith, v10.2.5
  MasqueCirque, v10.2.5
  MasqueEntropy, v10.2.5
  MasqueNewsom, v10.2.0
  MasqueOnyx, v10.2.5
  MasqueQhil, v1.3.1
  MasqueRaeli, v27.2
  MasqueSimplicity, v3.6.5
  MasqueSquat, v1.12.1
  MikScrollingBattleText, v5.9.1
  Molinari, v100200.110-Release
  Myslot, vv5.11.0-v1.15.0
  NameplateSCT, v1.33
  NovaWorldBuffs, v2.66
  OmniBar, vv14.27
  OmniCC, v10.2.2
  Peggle, v2.3.6
  Plater, vPlater-v574a-Classic
  Postal, vv4.1.1
  ProjectAzilroka, v1.88
  Quartz, v3.7.7
  QuestFrameFixer, v1.2
  QuestIconDesaturation, v3.4.1
  Questie, v9.2.17
  RangeDisplay, vv6.0.2
  RangeDisplayOptions, vv6.0.2
  RareScanner, v1.15.0.7
  RuneReminder, v0.7.7.2
  RXPGuides, vv4.5.43
  SafeQueue, vv8.10
  Scrap, v10.2.7
  SharedMedia, v3.1.1-199
  SharedMediaMyMedia, v
  SilverDragon, vv2024.1.1
  SilverDragonOverlay, vv2024.1.1
  SilverDragonRangeExtender, vv2024.1.1
  SimpleItemLevel, vv33.2
  SimpleRaidTargetIcons, v2.1.8-Classic
  SLoTe, v
  SoundManager, v1.31
  SpellActivationOverlay, v1.1.3
  Stubby, v3.4.6816 (SwimmingSeadragon)
  TipTac, v24.01.22
  TipTacItemRef, v24.01.22
  TipTacTalents, v24.01.22
  TomTom, vv3.5.5-release
  TotemTimers, v3.2.7
  TownsfolkTracker, v1.0.12
  WeakAuras, v5.9.2
  WeakAurasOptions, v5.9.2
  WeaponSwingTimer, v7.2.3
  WhatsTraining, v5.0.3
  WIM, v3.10.19
  BlizRuntimeLib_enUS v1.15.0.11500 <none>
  (ck=d64)

**Comment by BernCarney** [comment]
Same issue that I posted in #1875

**Comment by philesc** [comment]
Got the same problem with bagnon / weakaura.

**Comment by Jaliborc** [comment]
Fixed
