### ISSUE TITLE
What is the point of "Focus Trade"?

### ISSUE THREAD

**Issue by BreakBB** [Jaliborc/Bagnon#1879]
I am playing Classic WoW (WotLK and SoD) and a few versions back the icons for "Open Bank" was moved and the original position got replaced by "Focus Trade". Now I fall for this change quire regularly and this new option hides the entire bag.

Can someone shine a light on me why the position changing was done in the first place and why in gods name an option which hides the bag was introduced at the same place?

**Comment by Jaliborc** [comment]
Focus Trade/Normal is a shortcut to toggle between normal/reagent bags.

**Comment by BreakBB** [comment]
How is that relevant for Classic though @Jaliborc ? In reality it simply hides the bag for these WoW flavors.

I suggest to show the bank for these flavors, like it was before, instead of having some sort of "dead button".
