### ISSUE TITLE
Tracked Currencies

### ISSUE THREAD

**Issue by AMaribo** [Jaliborc/Bagnon#1883]
**Which software were you running?**
 - Addon version name: Bagnon-10.2.19
 - Client used: Retail 10.2.5

**Have you read the changelog?**
 No. I just installed Bagnon to test something out to compare to another bag addon.
I was not able to find a similar issue in open or closed issues.

**Please describe the bug.**
When adding many currencies to be shown on the backpack, the backpack starts to have blank space on the right-hand side, and the currency list starts to draw off the left-hand side of the backpack.
![image](https://github.com/Jaliborc/Bagnon/assets/7267373/4ef0915b-d773-4f8b-981a-4b803d03baaa)
Since arbitrarily many currencies can be added to be shown on the backpack with Bagnon, you can have the bag take up the majority of the screen with blank space.
![image](https://github.com/Jaliborc/Bagnon/assets/7267373/00973422-9697-4004-8ba7-f5e7f48de355)

**Please describe how to reproduce it.**
1. Open the character panel, go to the currency tab.
2. Click on a currency, then click on "Show on Backpack"
3. Continue adding more currencies to be shown on the backpack.

**Any Screenshots?**
Screenshots attached above.

**Error Logs are Important!**
No errors occur.

**Comment by Jaliborc** [comment]
Addressed
