### ISSUE TITLE
Leftover reference to removed testing file throws lua error in vanilla classic

### ISSUE THREAD

**Issue by KieranMoynihan** [Jaliborc/Bagnon#1894]
**Which software were you running?**
 - Addon version name: 10.2.26
 - Client used: Classic 1.15.2

**Have you read the changelog?**
Yes.

**Please describe the bug.**
Bagnon-Vanilla.toc references test.lua at the bottom, causing a lua error onload of the addon when it fails to load the test.lua file, presumably because it was removed after testing.

**Please describe how to reproduce it.**
1. Load the ui.

**Any Screenshots?**
![image](https://github.com/Jaliborc/Bagnon/assets/28952680/802c9937-b77d-404d-9b99-5110e3c6034e)

**Error Logs are Important!**
![image](https://github.com/Jaliborc/Bagnon/assets/28952680/33f36ddd-db1f-459f-83c9-49de256a7bf7)
![image](https://github.com/Jaliborc/Bagnon/assets/28952680/71202c46-0126-4bab-b5eb-1546fadb67c8)

**Comment by kalsto** [comment]
Signed in to add this bug - thank you for already posting it!
