### ISSUE TITLE
lua:24 attempt to call method 'IsReagents' (a nil value)

### ISSUE THREAD

**Issue by Fleymour** [Jaliborc/Bagnon#1941]
38x BagBrother/frames/containers/item.lua:24: attempt to call method 'IsReagents' (a nil value)
[string "@BagBrother/frames/containers/item.lua"]:24: in function <BagBrother/frames/containers/item.lua:21>

Locals:
self = BagnonContainerItem283 {
 IconOverlay = Texture {
 }
 AugmentBorderAnim = AnimationGroup {
 }
 showMatchHighlight = true
 flashAnim = AnimationGroup {
 }
 __count = 283
 NewItemTexture = Texture {
 }
 IgnoredOverlay = Texture {
 }
 Dummy = Button {
 }
 IconQuestTexture = BagnonContainerItem283IconQuestTexture {
 }
 emptyBackgroundAtlas = "bags-item-slot64"
 Count = BagnonContainerItem283Count {
 }
 searchOverlay = BagnonContainerItem283SearchOverlay {
 }
 NormalTexture = BagnonContainerItem283NormalTexture {
 }
 bag = 4
 __template = "ContainerFrameItemButtonTemplate"
 isCraftedItem = false
 isProfessionItem = false
 Cooldown = BagnonContainerItem283Cooldown {
 }
 Tag = "BAGNON_"
 FlashFind = AnimationGroup {
 }
 __index = <table> {
 }
 BagIndicator = Texture {
 }
 Stock = BagnonContainerItem283Stock {
 }
 __super = <table> {
 }
 __base = <table> {
 }
 icon = BagnonContainerItem283IconTexture {
 }
 Backgrounds = <table> {
 }
 __type = "ItemButton"
 IconGlow = Texture {
 }
 hasItem = true
 HighlightTexture = Texture {
 }
 itemContextMatchResult = 3
 flash = Texture {
 }
 CanIMogItOverlay = CIMIOverlayFrame_BagnonContainerItem283 {
 }
 count = 1
 __name = "BagnonContainerItem"
 info = <table> {
 }
 PushedTexture = Texture {
 }
 PixelSnapDisabled = true
 QuestBang = BagnonContainerItem283IconQuestTexture {
 }
 AugmentBorderAnimTexture = Texture {
 }
 frame = BagnonInventory1 {
 }
 BagFamilies = <table> {
 }
 IconOverlay2 = Texture {
 }
 newitemglowAnim = AnimationGroup {
 }
 ProfessionQualityOverlay = Texture {
 }
 __frames = <table> {
 }
 UpgradeIcon = Texture {
 }
 timeSinceUpgradeCheck = 0
 IconBorder = Texture {
 }
 ItemContextOverlay = Texture {
 }
 ExtendedSlot = Texture {
 }
 JunkIcon = Texture {
 }
 BattlepayItemTexture = Texture {
 }
 readable = false
}
button = "RightButton"
(*temporary) = nil
(*temporary) = <table> {
 IsRetail = true
 SearchFrame = <table> {
 }
 Frames = <table> {
 }
 Currency = <table> {
 }
 Skins = <table> {
 }
 ItemGroup = <table> {
 }
 AccountMoney = <table> {
 }
 ContainerItemGroup = <table> {
 }
 CurrencyTracker = <table> {
 }
 BankTab = <table> {
 }
 Frame = <table> {
 }
 OptionsToggle = <table> {
 }
 Bag = <table> {
 }
 LastBankBag = 12
 CurrencyTooltipCounts = <table> {
 }
 Base = <table> {
 }
 sets = <table> {
 }
 Name = "Bagnon"
 None = <table> {
 }
 Parented = <table> {
 }
 Cacher = <table> {
 }
 NumBags = 5
 ReagentButton = <table> {
 }
 Item = <table> {
 }
 IsClassic = false
 BankBags = <table> {
 }
 OwnerSelector = <table> {
 }
 Commands = <table> {
 }
 SortButton = <table> {
 }
 LastBankTab = 17
 BagGroup = <table> {
 }
 LDB = <table> {
 }
 TooltipCounts = <table> {
 }
 search = "leath"
 canSearch = false
 Tag = "BAGNON_"
 Inventory = <table> {
 }
 Rules = <table> {
 }
 guild = <table> {
 }
 player = <table> {
 }
 ItemSlot = <table> {
 }
 SearchToggle = <table> {
 }
 Title = <table> {
 }
 Slash = "bgn"
 SideFilters = <table> {
 }
 Owners = <table> {
 }
 InventoryBags = <table> {
 }
 BagToggle = <table> {
 }
 Bank = <table> {
 }
 Settings = <table> {
 }
 BrokerCarrousel = <table> {
 }
 MoneyFrame = <table> {
 }
 Tipped = <table> {
 }
 ContainerItem = <table> {
 }
 AutoDisplay = <table> {
 }
 Events = <table> {
 }
 DropButton = <table> {
 }
 CurrencyLimit = 30
 Sorting = <table> {
 }
 Version = "11.0.9"
}
(*temporary) = 4
(*temporary) = "attempt to call method 'IsReagents' (a nil value)"
Addon = <table> {
 IsRetail = true
 SearchFrame = <table> {
 }
 Frames = <table> {
 }
 Currency = <table> {
 }
 Skins = <table> {
 }
 ItemGroup = <table> {
 }
 AccountMoney = <table> {
 }
 ContainerItemGroup = <table> {
 }
 CurrencyTracker = <table> {
 }
 BankTab = <table> {
 }
 Frame = <table> {
 }
 OptionsToggle = <table> {
 }
 Bag = <table> {
 }
 LastBankBag = 12
 CurrencyTooltipCounts = <table> {
 }
 Base = <table> {
 }
 sets = <table> {
 }
 Name = "Bagnon"
 None = <table> {
 }
 Parented = <table> {
 }
 Cacher = <table> {
 }
 NumBags = 5
 ReagentButton = <table> {
 }
 Item = <table> {
 }
 IsClassic = false
 BankBags = <table> {
 }
 OwnerSelector = <table> {
 }
 Commands = <table> {
 }
 S

**Comment by Peregran** [comment]
Also happened to me when trying to transfer items from bag to bank.

**Comment by Jaliborc** [comment]
Nice catch, fixed internally
