### ISSUE TITLE
Bag frame not opening when toggled on

### ISSUE THREAD

**Issue by Lotoqt** [Jaliborc/Bagnon#1945]
1x BagBrother/core/classes/itemGroup.lua:112: attempt to compare number with boolean
[string "@BagBrother/core/classes/itemGroup.lua"]:112: in function `Layout'
[string "@BagBrother/core/classes/itemGroup.lua"]:32: in function `Update'
[string "@BagBrother/core/classes/itemGroup.lua"]:26: in function <BagBrother/core/classes/itemGroup.lua:12>
[string "=(tail call)"]: ?
[string "@Bagnon/src/frame.lua"]:24: in function `New'
[string "@BagBrother/core/api/frames.lua"]:83: in function `New'
[string "@BagBrother/core/api/frames.lua"]:28: in function `Show'
[string "@BagBrother/core/api/frames.lua"]:24: in function <BagBrother/core/api/frames.lua:23>
[string "=(tail call)"]: ?
[string "@BagBrother/core/features/autoDisplay.lua"]:83: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals:
self = Frame {
 buttons = <table> {
 }
 order = <table> {
 }
 frame = BagnonInventory5 {
 }
 bags = <table> {
 }
}
profile = <table> {
 rules = <table> {
 }
 point = "TOPRIGHT"
 hiddenBags = <table> {
 }
 scale = 1
 borderColor = <table> {
 }
 bagToggle = true
 enabled = true
 reverseBags = true
 itemScale = 1
 alpha = 1
 hiddenRules = <table> {
 }
 bagBreak = false
 y = -190.313782
 x = -165.296997
 bagFrame = false
 showBags = true
 reverseSlots = false
 color = <table> {
 }
 actPanel = false
 lockedSlots = <table> {
 }
}
columns = 10
scale = 1
size = 39
space = 1.300000
revBags = true
revSlots = false
x = 6
y = 2
group = 0
(for index) = 5
(for limit) = 1
(for step) = -1
k = 5
frame = Frame {
 id = 4
}
bag = 4
numSlots = 32
family = 0
slots = <table> {
}
(*temporary) = false
(*temporary) = 0
(*temporary) = 2
(*temporary) = 7
(*temporary) = 0
(*temporary) = 0
(*temporary) = 7
(*temporary) = 0
(*temporary) = "owner"
(*temporary) = nil
(*temporary) = nil
(*temporary) = <table> {
 __super = <table> {
 }
 __base = <table> {
 }
 BagGroup = <table> {
 }
 OpenSound = 862
 __frames = <table> {
 }
 __type = "Frame"
 __count = 0
 FontH = GameFontHighlightLeft {
 }
 BrokerSpacing = 2
 __name = "BagnonFrame"
 MoneyFrame = <table> {
 }
 MoneySpacing = 8
 CloseSound = 863
 Font = GameFontNormalLeft {
 }
 __index = <table> {
 }
}
(*temporary) = "owner"
(*temporary) = "attempt to compare number with boolean"

**Comment by jkn22** [comment]
Message: ...terface/AddOns/BagBrother/core/classes/itemGroup.lua:112: attempt to compare number with boolean
Time: Fri Aug 30 17:37:14 2024
Count: 1
Stack: ...terface/AddOns/BagBrother/core/classes/itemGroup.lua:112: attempt to compare number with boolean
[string "@Interface/AddOns/BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...her/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/BagBrother/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...AddOns/BagBrother/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: handlers = <table> {
}
index = <table> {
 IsRetail = true
 SearchFrame = <table> {
 }
 Frames = <table> {
 }
 Currency = <table> {
 }
 Skins = <table> {
 }
 ItemGroup = <table> {
 }
 AccountMoney = <table> {
 }
 ContainerItemGroup = <table> {
 }
 CurrencyTracker = <table> {
 }
 BankTab = <table> {
 }
 Frame = <table> {
 }
 OptionsToggle = <table> {
 }
 Bag = <table> {
 }
 LastBankBag = 12
 CurrencyTooltipCounts = <table> {
 }
 Base = <table> {
 }
 sets = <table> {
 }
 Name = "Bagnon"
 None = <table> {
 }
 Parented = <table> {
 }
 player = <table> {
 }
 Cacher = <table> {
 }
 NumBags = 5
 ReagentButton = <table> {
 }
 Item = <table> {
 }
 IsClassic = false
 BankBags = <table> {
 }
 OwnerSelector = <table> {
 }
 Commands = <table> {
 }
 SortButton = <table> {
 }
 LastBankTab = 17
 AutoDisplay = <table> {
 }
 BagGroup = <table> {
 }
 LDB = <table> {
 }
 TooltipCounts = <table> {
 }
 SideFilters = <table> {
 }
 Tag = "BAGNON_"
 Inventory = <table> {
 }
 Rules = <table> {
 }
 ItemSlot = <table> {
 }
 SearchToggle = <table> {
 }
 Title = <table> {
 }
 Slash = "bgn"
 Owners = <table> {
 }
 InventoryBags = <table> {
 }
 BagToggle = <table> {
 }
 Bank = <table> {
 }
 Settings = <table> {
 }
 BrokerCarrousel = <table> {
 }
 MoneyFrame = <table> {
 }
 Tipped = <table> {
 }
 ContainerItem = <table> {
 }
 Events = <table> {
 }
 DropButton = <table> {
 }
 CurrencyLimit = 30
 Sorting = <table> {
 }
 Version = "11.0.12"
}


and

Message: ...terface/AddOns/BagBrother/core/classes/itemGroup.lua:112: attempt to compare number with boolean
Time: Fri Aug 30 17:37:19 2024
Count: 3
Stack: ...terface/AddOns/BagBrother/core/classes/itemGroup.lua:112: attempt to compare number with boolean
[string "@Interface/AddOns/BagBrother/core/classes/itemGroup.lua"]:112: in function `Layout'
[string "@Interface/AddOns/BagBrother/core/classes/itemGroup.lua"]:32: in function `Update'
[string "@Interface/AddOns/BagBrother/core/classes/itemGroup.lua"]:26: in function <...terface/AddOns/BagBrother/core/classes/itemGroup.lua:12>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/src/frame.lua"]:24: in function `New'
[string "@Interface/AddOns/BagBrother/core/api/frames.lua"]:83: in function `New'
[string "@Interface/AddOns/BagBrother/core/api/frames.lua"]:28: in function `Show'
[string "@Interface/AddOns/BagBrother/core/api/frames.lua"]:24: in function <Interface/AddOns/BagBrother/core/api/frames.lua:23>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/BagBrother/core/features/autoDisplay.lua"]:83: in function <...face/AddOns/BagBrother/core/features/autoDisplay.lua:82>
[string "=[C]"]: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals: self = Frame {
 buttons = <table> {
 }
 order = <table> {
 }
 frame = BagnonInventory4 {
 }
 bags = <table> {
 }
}
profile = <table> {
 rules = <table> {
 }
 point = "BOTTOMRIGHT"
 hiddenBags = <table> {
 }
 color = <table> {
 }
 sort = true
 borderColor = <table> {
 }
 bagToggle = true
 enabled = true
 reverseBags = false
 columns = 12
 money = true
 hiddenRules = <table> {
 }
 y = 212.047653
 x = -81.999634
 search = true
 showBags = true
 reverseSlots = false
 lockedSlots = <table> {
 }
 options = true
 bagBreak = false
}
columns = 12
scale = 1
size = 39
space = 1.300000
revBags = false
revSlots = false
x = 8
y = 1
group = 0
(for index) = 2
(for limit) = 6
(for step) = 1
k = 2
frame = Frame {
 id = 1
}
bag = 1
numSlots = 32
family = 0
slots = <table> {
}
(*temporary) = false
(*temporary) = 0
(*temporary) = 2
(*temporary) = 0
(*temporary) = 0
(*temporary) = 0
(*temporary) = 0
(*temporary) = 0
(*temporary) = "owner"
(*temporary) = nil
(*temporary) = nil
(*temporary) = <table> {
 __super = <table> {
 }
 __base = <table> {
 }
 BagGroup = <table> {
 }
 OpenSound = 862
 __frames = <table> {
 }
 __type = "Frame"
 __count = 0
 FontH = GameFontHighlightLeft {
 }
 BrokerSpacing = 2
 __name = "BagnonFrame"
 MoneyFrame = <table> {
 }
 MoneySpacing = 8
 CloseSound = 863
 Font = GameFontNormalLeft {
 }
 __index = <table> {
 }
}
(*temporary) = "owner"
(*temporary) = "attempt to compare number with boolean"

**Comment by Jaliborc** [comment]
Fixed internally hopefully
