### ISSUE TITLE
11.0.17 - Ignore Cleanup

### ISSUE THREAD

**Issue by voidzone** [Jaliborc/Bagnon#1955]
**Which software were you running?**
 - Addon version name: 11.0.17
 - Client used: Retail 11.0.2.56421

**Have you read the changelog?**
Yep

**Please describe the bug.**
The Ignore this bag: cleanup option no longer causes the bag to be ignored for cleanup operations.

**Please describe how to reproduce it.**
1. Mark a bag to be ignored for cleanup, 
2. Put things in it.
3. left click the cleanup button
4. All items are cleaned up including the ones in the ignored bag

**Any Screenshots?**
![image](https://github.com/user-attachments/assets/940ec020-da86-48ee-bc0d-f1e70d1a9292)

**Error Logs are Important!**
No errors are triggered. Issue was not present in 11.0.15 (not sure about 11.0.16)

**Comment by mjb7569** [comment]
Same issue here... my bags marked as Ignore Cleanup are now being cleaned up.

**Comment by Jartholdy** [comment]
Try this: right click "cleanup"-button and make sure the checkbox for server side is enabled.

**Comment by voidzone** [comment]
That fixed it.  Looks like the box is unchecked by default in 11.0.17
