### ISSUE TITLE
guild item count setting incorrect

### ISSUE THREAD

**Issue by blockberd** [Jaliborc/Bagnon#586]
The option for the guild bank item count says "Include Guild Banks" but enabling it actually EXcludes the counts.

Also, it only disables the guild bank counts for one character. For example:
I have two chars in the same guild. I enabled said option on one and it hides the guild bank item counts only for that char in the tooltip. The other char still appears with the guild bank item count.

I just want to get rid of the guild bank item count completely. :-/

**Comment by bahahamut** [comment]
bump for completely removing guild bank inquiries, or at the very least, properly separating those item counts so they ONLY get queried/counted/displayed ONCE. 

T_T
