### ISSUE TITLE
"Added option to disable tooltip counts just for guild banks" <--- not quite there yet...

### ISSUE THREAD

**Issue by bahahamut** [Jaliborc/Bagnon#593]
"Added option to disable tooltip counts just for guild banks"

this was a much requested change, and i was excited - unfortunately the "total" displayed in tooltip counts STILL includes the guild bank items per individual character - at least - _IF_ that character doesn't have any of that specific item in their personal bags. so. augment runes. the total accurately counts up ONLY the ones in the bags on toons that actually have some, but it's also incorrectly adding the guild bank total for EACH toon that doesn't have any of their own. will post also on the github. 

please fix!

ALSO: toggling the item tooltip counts in options isn't even functional, and this may be part of the issue. see, until this is resolved i decided to just disable the addons tooltip counts altogether, but it won't let me. uncheck it, click ok, look at my bags, tooltip counts still present, so i go back to options, and it's checked itself back on. sad.

see also issue:
https://github.com/tullamods/Bagnon/issues/586
for _similar_ guild bank bug

**Comment by sidelsky18** [comment]
Agreed, still having the same issue even when "include guild bank counts" is UNchecked.
