### ISSUE TITLE
Small display bug in bag

### ISSUE THREAD

**Issue by ghost** [Jaliborc/Bagnon#595]
# Image
![30](https://user-images.githubusercontent.com/664126/29945166-19f87088-8e6e-11e7-8ec9-f692e3d21488.PNG)

# Expected result
![30](https://user-images.githubusercontent.com/664126/29945417-10537f18-8e6f-11e7-9b7d-2509224d5f77.PNG)

# Description 
As you can see, one of my character has "000" gold, but it actualy has 1000, I tried giving her/taking some money out of her pocket, it did fix the problem, Relogging did not fix the error.  Having 1000 gold displays "000" on other characters too !

# Addon list
World Quest tracker, Skada, SexyMap, Quartz, Easy Obliterate, DBM, **Bagnon**, AskMr Robot, **Accountant**, **Auctionator**, AtlasLoot Enhanced

# My thought
Having 1000 gold displays 000 on mouse over, so maybe something to do with the "1" symbol?

**Comment by Valmere** [comment]
I'm getting this same issue.
