### ISSUE TITLE
.Bagnon\external\Wildpants\features\tooltipCounts.lua:73: attempt to index field '?' (a nil value)

### ISSUE THREAD

**Issue by Thrumbar** [Jaliborc/Bagnon#677]
682x ...Bagnon\external\Wildpants\features\tooltipCounts.lua:73: attempt to index field '?' (a nil value)
...Bagnon\external\Wildpants\features\tooltipCounts.lua:73: in function <...Bagnon\external\Wildpants\features\tooltipCounts.lua:57>
...Bagnon\external\Wildpants\features\tooltipCounts.lua:135: in function <...Bagnon\external\Wildpants\features\tooltipCounts.lua:132>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: in function `SetGuildBankItem'
Bagnon_GuildBank\components\item.lua:94: in function `UpdateTooltip'
Bagnon_GuildBank\components\item.lua:80: in function <Bagnon_GuildBank\components\item.lua:77>

Locals:
tooltip = GameTooltip {
 0 = <userdata>
 GetBackdropColor = <function> defined @TinyTooltip\core.lua:759
 SetCurrencyToken = <function> defined @Altoholic\Tooltip.lua:680
 SetGuildBankItem = <function> defined =[C]:-1
 SetVoidItem = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined =[C]:-1
 Hide = <function> defined =[C]:-1
 SetArtifactPowerByID = <function> defined =[C]:-1
 SetHyperlink = <function> defined =[C]:-1
 comparing = false
 SetSocketGem = <function> defined =[C]:-1
 GetBackdropBorderColor = <function> defined @TinyTooltip\core.lua:760
 GetBackdrop = <function> defined @TinyTooltip\core.lua:758
 model = <unnamed> {
 }
 SetItemByID = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetExistingSocketGem = <function> defined =[C]:-1
 SetTrainerService = <function> defined =[C]:-1
 numMoneyFrames = 1
 hasMoney = 1
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 style = <unnamed> {
 }
 SetMerchantItem = <function> defined =[C]:-1
 SetMerchantCostItem = <function> defined =[C]:-1
 SetBackpackToken = <function> defined =[C]:-1
 SetTradeTargetItem = <function> defined =[C]:-1
 SetUnitDebuff = <function> defined =[C]:-1
 SetTradePlayerItem = <function> defined =[C]:-1
 SetHeirloomByItemID = <function> defined =[C]:-1
 SetSendMailItem = <function> defined =[C]:-1
 SetInboxItem = <function> defined =[C]:-1
 updateTooltip = 0.16099999826401
 SetInventoryItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 SetUnitBuff = <function> defined =[C]:-1
 __tamedCounts = false
 SetUnitAura = <function> defined =[C]:-1
 SetLootRollItem = <function> defined =[C]:-1
 CIMI_tooltipWritten = false
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 SetAction = <function> defined =[C]:-1
 SetAuctionSellItem = <function> defined =[C]:-1
 SetRecipeResultItem = <function> defined =[C]:-1
 SetAuctionItem = <function> defined =[C]:-1
}
link = "|cffffffff|Hitem:17709::::::::110:105::11::::|h[Recipe: Elixir of Frost Power]|h|r"
itemID = 17709
players = 1
total = 1
(for generator) = <function> defined @Bagnon\external\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:162
(for state) = nil
(for control) = "® Tan Thousand Fists"
owner = "® Tan Thousand Fists"
info = <table> {
 isguild = true
 name = "Tan Thousand Fists"
 faction = "Alliance"
 cached = false
 realm = "Hellscream"
}
color = "|cfffad000%s|r"
(*temporary) = nil
(*temporary) = <table> {
 isguild = true
 name = "Tan Thousand Fists"
 faction = "Alliance"
 cached = false
 realm = "Hellscream"
}
(*temporary) = <table> {
 GetRGB = <function> defined @SharedXML\Util.lua:594
 OnLoad = <function> defined @SharedXML\Util.lua:583
 b = 0
 WrapTextInColorCode = <function> defined @SharedXML\Util.lua:625
 GenerateHexColor = <function> defined @SharedXML\Util.lua:621
 GetRGBA = <function> defined @SharedXML\Util.lua:602
 IsEqualTo = <function> defined @SharedXML\Util.lua:587
 g = 0.64
 r = 0.77
 SetRGBA = <function> defined @SharedXML\Util.lua:610
 GetRGBAsBytes = <function> defined @SharedXML\Util.lua:598
 SetRGB = <function> defined @SharedXML\Util.lua:617
 GetRGBAAsBytes = <function> defined @SharedXML\Util.lua:606
}
(*temporary) = 1.41
(*temporary) = 325.53191489362
(*temporary) = "|cfffad000%s|r"
(*temporary) = "%s|r"
(*temporary) = 250.65957446809
(*temporary) = 208.34042553191
(*temporary) = 0
(*temporary) = "|cfffad000"
(*temporary) = 255
(*temporary) = 0
(*temporary) = 0
(*temporary) = nil
(*temporary) = "Interface/CharacterFrame/TEMPORARYPORTRAIT-Male-Pandaren"
(*temporary) = "attempt to index field '?' (a nil value)"
Addon = <table> {
 GetOwnerColorString = <function> defined @Bagnon\external\Wildpants\core\owners.lua:47
 SearchFrame =

**Comment by cogar328** [comment]
any help for this?


98x ...Bagnon\external\Wildpants\features\tooltipCounts.lua:73: attempt to index field '?' (a nil value)
...Bagnon\external\Wildpants\features\tooltipCounts.lua:73: in function <...Bagnon\external\Wildpants\features\tooltipCounts.lua:57>
...Bagnon\external\Wildpants\features\tooltipCounts.lua:135: in function <...Bagnon\external\Wildpants\features\tooltipCounts.lua:132>
[C]: ?
[C]: ?
[C]: ?
...TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:482: in function <...TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:476>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
...TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:408: in function `SetGuildBankItem'
Blizzard_GuildBankUI\Blizzard_GuildBankUI.lua:675: in function <Blizzard_GuildBankUI\Blizzard_GuildBankUI.lua:673>

etc
