### ISSUE TITLE
Guild logs are not displaying properly

### ISSUE THREAD

**Issue by Zaralissa** [Jaliborc/Bagnon#683]
Guild bank logs aren't showing the most recent transactions and the font is huge.  I've played with all of the settings in game to no avail.  I disabled Bagnon and guild logs display perfectly.  Re-downloaded Bagnon, enabled the addon and it's back to displaying incorrectly.

**Comment by pink2amos** [comment]
Same issue here.  I've had to stop using Bagnon for the time being.  Please fix.

**Comment by jdtemple** [comment]
The latest update appears to have fixed it.
