### ISSUE TITLE
BagBrother reporting item count incorrectly.

### ISSUE THREAD

**Issue by aeromaxx** [Jaliborc/Bagnon#685]
I have numerous items in my guild bank, but for some of the items the count is reported higher than it actually should be.

For example I have put one "Lesser Moonstone" into my guild bank, but the addon is reporting that I have 9 of them in my guild bank when I only have the 1.

Could you possibly look into what is causing this issue?

**Comment by Snipy2k4** [comment]
This is a guild error. I have the same problem with characters who are not in the same guild. The counter only counts the items of the character that are in the same guild. Whether that's on the bank, in the inventory or on the guild bank does not matter. The counters are wrong if you have characters in several guilds.

I play with German client and the translations are also faulty here.
