### ISSUE TITLE
Guild bank not showing tabs

### ISSUE THREAD

**Issue by nucksfan** [Jaliborc/Bagnon#719]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Error Logs**
If applicable, add the first error message (labeled 1/Many) that appeared.

**Screenshots**

**Running Software (please complete the following information):**
 - Game patch [e.g. Patch 8.0.1]
 - Addon version [e.g. 8.0.0]

**Additional context**

**Comment by Meeanda** [comment]
Opened the guild bank. Guild bank was empty. no tabs, no inventory
just open the guild bank to reproduce the problem
I expected the guild bank to be there with tabs
No error reported by swatter or bug grabber
running patch 8.0.1 addon 8.0.0 updated one day ago

**Comment by RTWbandit** [comment]
Im having the same problem.

**Comment by Ayrlaine** [comment]
I have the same issue - but it may be more complicated than it appears at first.  I turned off the Guild Bank Module - that lets my characters who saw the issue use the Guild Bank - just in the standard Blizz format.  However - even with it turned off I have some characters who are seeing the Guild Bank in the format I normally use - Bagnon.  So - if you don't duplicate the issue when you try to look at it, try again  :)

**Comment by AcuteSyphilis** [comment]
Can confirm as well.

2/3 accounts are working fine. My WoW2 account however only loads 4/7 tabs. No errors, nothing. Switching to default wow ui works, but it blows. Deleting the saved variables did not resolve the issue. Reloading doesnt resolve the issue. Issue appears in both mobile gbank and physical gbank inside of a major city. Tried reverting to the previous version (7.3.11) and issue still persists.

All in all, its a pain to deal with right now. I'd prefer my bagnon work for all toons.

**Comment by rustygp2u** [comment]
Can also confirm this issue.

**Comment by Riggbiggly** [comment]
I have been tangling with this predicament for several days, ever since the Wow 8.0 patch. Unless I have missed something, in the comments above, I am facing some unique oddities. I play on several realms and on two different accounts. On Area52, and Khaz'goroth, the 'no guild bank tabs displaying' error occurs, regardless of which account I'm playing. However--again, regardless of account logged in--on Darkspear and Kul Tiras, Bagnon Guild Bank works flawlessly. I have mimicked the settings from a known good configuration (thinking maybe I bumped something, unwittingly), with no effect. I also performed a game scan and repair, and I deleted Cache, WTF and Interface folders. Lastly, I reinstalled Bagnon as my ONLY add-on, and the error persists. 
I can only imagine how much work and coding goes into your add-on suite, but I really do hope these game-changer hiccups (for us) seem a lot less perplexing to those of you providing this service, because your nearest competition, for lack of any better phrasing, just plain sucks. 

Godspeed on any bug-fixes 

Thanks

**Comment by elmorulz681** [comment]
I am having the same issue now since the patch.

**Comment by jdtemple** [comment]
I just turned the guild bank piece of Bagnon back on after today's update, and the guild bank appears to be functioning correctly. Thanks!

**Comment by Ayrlaine** [comment]
Checked it this morning - after I d/l the latest - it all looks good to me now!  Thanks for the fix :)

**Comment by reef88** [comment]
Broken again. Only 4/6 tabs showing in guildbank.

**Comment by jdtemple** [comment]
It's working fine for me still.

Are you sure you aren't having some kind of addon conflict? I run very few addons, and Bagnon is the only UI related one I have.

**Comment by elmorulz681** [comment]
@reef88 it is not broken, if your rank does not allow you access to those tabs then you will not see them. If it is on an alt that would be why.

**Comment by reef88** [comment]
@elmorulz681 
I'm GM and its my personal bank. 7 tabs in total, but only see 4 unless I disable the addon.

**Comment by DasAoD** [comment]
Same problem as reef88 told.
Only 4 slots are visible.
If i disable the guildbank part of bagnon, all slots are shown in the blizzard frame.
Even after a new installation of the addon.

Game version 8.0.1 (27404)
Bagnon version 8.0.2

**Comment by FelixFTW** [comment]
Same issue for me.  

Game version 8.0.1
Bagnon version 8.0.2

**Comment by reef88** [comment]
Can confirm, issue not resolved.

**Comment by JimGiordano2** [comment]
I went so far as to remove the old version and install a new clean version of Warcraft.  Added only Bagnon.  Still problem with only showing 4 tabs on guild bank.

**Comment by jdtemple** [comment]
Mine started throwing errors in the UI related to the Guild Bank and Void Storage bits. It also suffers from the inability to view the most recent log entry on any given guild tab.

I have also resorted to shutting off those two parts of the addon. All I really use is the inventory counts in the tooltip anyway (from Bag Brother), and those continue to work even if the UI part is disabled.

**Comment by d3w4yn3** [comment]
BAGNON still breaking gbanks today!  Current version won't let the initial gbank config dialogue (where you buy the first tab) show up!  Disable bagnon, fixes the problem, then reenable and the gbank works right.

**Comment by Ayrlaine** [comment]
Thank you - you’re the best!


Sent from the all new AOL app for iOS


On Monday, September 11, 2023, 6:33 PM, João Cardoso ***@***.***> wrote:




Closed #719 as completed.
