### ISSUE TITLE
Item count tooltip broken

### ISSUE THREAD

**Issue by Pharozz** [Jaliborc/Bagnon#726]
**Describe the bug**
Item count tooltip: Not working

**Error Logs**
N/A

**Screenshots**
![sem titulo](https://user-images.githubusercontent.com/41822650/43355376-1d45ceea-9253-11e8-83b3-8765e5748a39.jpg)

**Running Software:**
 - Game patch [Patch 8.0.1.27178]
 - Addon version [8.0.0]

**Additional context**
This tool worked correctly in the previous version but after upgrading to version 8.0.1 it stopped working. What I've Done:

1) Installed the previous version: It does not work;

2) Deleted the WTF, Interface and Cache folders, I installed the addon again: It does not work;

3) Reinstalled the game: It does not work.

Thanks, 
PG

**Comment by Askania** [comment]
I also have this problem and It's a little annoying that I cant just hover over the gold section to see who has how much gold. Having to rely on altoholic for this would rather just open my bags and hover.

**Comment by Jaliborc** [comment]
What server you on

**Comment by Pharozz** [comment]
Hi. I'm on Aggra. Last addon update (v8.0.1) fixed the issue. 

Thank you for support
PG

**Comment by Askania** [comment]
My issue is also fixed thanks

**Comment by oscargarcia0101** [comment]
Hello. I have update (v8.0.1) and its still not working for me. Not sure what else to do.

![image](https://user-images.githubusercontent.com/6424785/43664712-b083e15a-9722-11e8-8eef-6ef9d6c92735.png)

**Comment by Askania** [comment]
Hi Oscar, I don't know whats happened for you, but my problem was that I had to reset the interface by deleting the folder and twitch to get the patch to work. I discovered that after I had logged in to everyone of my characters bagnon was working as intended again. I don't know if that will work for you or not but it's worth a try :)

**Comment by adelaide1111** [comment]
It works in Windrunner server(KR) but does not work in Burning Legion server(KR) from pre-patch.

![wowscrnshot_080618_155732](https://user-images.githubusercontent.com/42133560/43701762-62eb4c9a-9992-11e8-8b4f-46b6f9ee98a2.jpg)

![wowscrnshot_080618_155630](https://user-images.githubusercontent.com/42133560/43701765-6465d1f8-9992-11e8-95a5-591bb5d6904d.jpg)

Setting is completely same in both servers and characters belong to the same account.
Hope it works again!

**Comment by Malaclypsety** [comment]
same here. it doesn't work on Kult der Verdammten (EU) but works fine on Blackhand (EU)

On Kult der Verdammten, i don't even see the character icon. and the gold count just shows "0"

**Comment by Mythalar** [comment]
Hey,

Same issue here, the item count tooltip works fine on Hyjal (EU), but not on Confrérie du Thorium (EU), be it on the same account or my second one.

Quite problematic :/

**Comment by Krakken77** [comment]
Hello,
Same problem for me on the same server: Confrérie du Thorium (EU).
But with the same config, everything is ok on another server: Kirin Tor (EU).
Still a problem on the 3rd september 2018 after the latest bagnon version 8.0.3.
Thank you in advance for any help.
Best regards.

**Comment by Joccob** [comment]
Same problem here. Glad to know this is somehow related to servers. Hope this can be fixed soon~

**Comment by Dodgexander** [comment]
I also have this problem, I thought it happened after the recent server merges.
