### ISSUE TITLE
Item count tooltip not working

### ISSUE THREAD

**Issue by Professor-OG** [Jaliborc/Bagnon#741]
**Running Software (please complete the following information):**
 - Game patch build 8.0.1.27219
 - Addon version 8.0.2

**Describe the bug**
Before BfA pre patch, I was able to hover over an item and see how many of that item i have on my person and across all my toons. The addon doesn't do that anymore.

**To Reproduce**
1. Install Bagnon 8.0.2
2. open bags
3. hover mouse over item

**Expected behavior**
Expected to be able to see how many of an item I have on myself and across other toons.

**Screenshots**
![untitled](https://user-images.githubusercontent.com/6424785/43680299-78b512ce-97ec-11e8-96fe-82f1c036fa26.png)

**Error Logs**
N/A

**Additional context**
What I have tried:
Uninstalling / reinstalling addon
Deleting WTF, Interface, Cache folders then reinstalling
Deleting WTF, Interface, Cache and uninstalling Twitch, rebooting the computer then reinstalling it all
Only having Bagnon addon turned on by itself:
![1212121ed](https://user-images.githubusercontent.com/6424785/43680319-eb072204-97ec-11e8-83c9-a1c8855c98eb.png)

None of this has worked.

**Comment by Vokrmmo** [comment]
Same issue here

**Comment by oscargarcia0101** [comment]
Well its been almost a week and nothing.

Downloading Altoholic fixed this -_-
