### ISSUE TITLE
Guild Bank Enable Frame grayed out

### ISSUE THREAD

**Issue by JimGiordano2** [Jaliborc/Bagnon#744]
**Running Software (please complete the following information):**
 - Game patch [e.g. Build 8.0.1.27219]
 - Addon version 8.0.1 and 8.0.2

**Describe the bug**
Option to enable/disable frame for guild bank no longer working.
Enable frame has a grayed out checkmark that can't be changed.
Also, only first 4 bags show in guildbank, no way to look at the others.

**Comment by JimGiordano2** [comment]
Am I the only one than can only see the first four slots of the guildbank?  Is there some know fix I havn't found yet.  This is really frustrating when I can't even toggle it on and off to see the other slots.

**Comment by Erichssf** [comment]
This is happening for me as all. have not been able to find any type of fix for it, and there is no error, it just does not display all the guild bank tabs.

**Comment by JimGiordano2** [comment]
I'm sorry for you, but glad it isn't just me :)   I tried everything I could think of.  Even wiped WTF, Cache, and Logs folders.  Ran once to let wow recreate the folders, then installed Bagnon as the only addon.  Still didn't work.  Wiped it, and tried previous version.  Still same problem, only four guildbank tabs.

**Comment by Erichssf** [comment]
Anybody find a solution to this yet?

**Comment by VicMackeypwn** [comment]
Same thing happened to me.

1. Guild master needs to buy the first guild tab, which can only be done AT the guild bank.  This is 100g as of 9/6/21 classic tbc.  I wasn't able to see this at all, until I turned off Bagnon addon.  Bagnon blocks the prompt to buy a guild tab.  You can turn it off, purchase the tab, and turn it back on.  You can turn off all to be safe, depends what else you're running perhaps.
2. Guild master needs to set permissions
