### ISSUE TITLE
Shift right click to select amount not working in Guild bank

### ISSUE THREAD

**Issue by JimGiordano2** [Jaliborc/Bagnon#757]
**Running Software (please complete the following information):**
 - Game patch Build 8.0.1.27326
 - Addon version 8.0.2

**Describe the bug**

**To Reproduce**
1. Open guild bank
2. Hold down shift
3. Right click on a stack of items
4. The option to select how many does not appear

**Expected behavior**
The standard option to select some amount of items from the stack should appear.

**Comment by Romsh** [comment]
I'm following this problem because it seems that i have the same problem.
I tried to do the same manipulation above without bagnon activated, and split item works.

**Comment by MatKnappe** [comment]
In Bagnon_GuildBank\components\Item.lua line 40.

Change
 	**if IsModifiedClick('SPLITSTACK') then
		if not self:GetInfo().locked then
			self.SplitStack = ItemSlot.SplitStack -- have no idea why is necessary
			OpenStackSplitFrame(select(2, self:GetInfo()), self, 'BOTTOMLEFT', 'TOPLEFT')**

to
	**if IsModifiedClick('SPLITSTACK') then
		if not self.IsLocked then
			self.SplitStack = ItemSlot.SplitStack -- have no idea why is necessary
			OpenStackSplitFrame(self.count, self, 'BOTTOMLEFT', 'TOPLEFT',1)**

This seems to work for me.

**Comment by Sinswrath** [comment]
In Bagnon_GuildBank\components\Item.lua line 40.

Change
**if IsModifiedClick('SPLITSTACK') then
if not self:GetInfo().locked then
self.SplitStack = ItemSlot.SplitStack -- have no idea why is necessary
OpenStackSplitFrame(select(2, self:GetInfo()), self, 'BOTTOMLEFT', 'TOPLEFT')**

to
**if IsModifiedClick('SPLITSTACK') then
if not self.IsLocked then
self.SplitStack = ItemSlot.SplitStack -- have no idea why is necessary
OpenStackSplitFrame(self.count, self, 'BOTTOMLEFT', 'TOPLEFT',1)**

This seems to work for me.

**Comment by semecan** [comment]
This has to be modified now aswell. OpenStackSplitFrame has to be called on the StackSplitFrame Object:
StackSplitFrame:OpenStackSplitFrame...

**Comment by Elaytrix** [comment]
@semecan where do you change it and exactly what do I put

**Comment by semecan** [comment]
@Elaytrix apply what Sinswrath posted but change the last line from
`OpenStackSplitFrame(self.count, self, 'BOTTOMLEFT', 'TOPLEFT',1)`
to
`StackSplitFrame:OpenStackSplitFrame(self.count, self, 'BOTTOMLEFT', 'TOPLEFT',1)`
