### ISSUE TITLE
Bagnon Fails  Everytime Daily

### ISSUE THREAD

**Issue by rasputina** [Jaliborc/Bagnon#771]
Major problems with this addon lately. I am saddened because I love this addon and really can't play without it. I am not technically inclined, I tried to submit a bug report at github, but I couldn't. I just don't know what to look for. I hope this is seen by the developer . I choose the option to turn off the guild bank viewer, because I prefer the classic Guild bank and Void Storage. I am using WoW version 8.0.1.27377. Bagnon version 8.0.2.

 

745x ...Bagnon\external\Wildpants\features\tooltipCounts.lua:74: attempt to index field '?' (a nil value)
...Bagnon\external\Wildpants\features\tooltipCounts.lua:74: in function <...Bagnon\external\Wildpants\features\tooltipCounts.lua:58>
...Bagnon\external\Wildpants\features\tooltipCounts.lua:136: in function <...Bagnon\external\Wildpants\features\tooltipCounts.lua:133>
[C]: ?
[C]: ?
[C]: ?
Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:408: in function <Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:402>
[C]: ?
[C]: ?
[C]: in function `SetHyperlink'
Bagnon\external\Wildpants\components\bag.lua:234: in function `UpdateTooltip'
Bagnon\external\Wildpants\components\bag.lua:116: in function <Bagnon\external\Wildpants\components\bag.lua:109>

Locals:
tooltip = GameTooltip {
0 = <userdata>
SetQuestLogRewardSpell = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:402
canAddRestStateLine = 1
SetExistingSocketGem = <function> defined =[C]:-1
SetCurrencyToken = <function> defined @Altoholic\Tooltip.lua:700
SetShapeshift = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:402
SetVoidItem = <function> defined =[C]:-1
SetVoidDepositItem = <function> defined =[C]:-1
Hide = <function> defined =[C]:-1
SetVoidWithdrawalItem = <function> defined =[C]:-1
SetQuestRewardSpell = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:402
comparing = false
SetSocketGem = <function> defined =[C]:-1
SetHyperlink = <function> defined =[C]:-1
Show = <function> defined =[C]:-1
SetGuildBankItem = <function> defined =[C]:-1
SetPetAction = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:402
SetUnitDebuff = <function> defined =[C]:-1
SetItemByID = <function> defined =[C]:-1
SetLootItem = <function> defined =[C]:-1
SetQuestItem = <function> defined =[C]:-1
LibExtraTipRight = <table> {
}
FadeOut = <function> defined @TipTac\ttCore.lua:856
LibExtraTipLeft = <table> {
}
__tamedCounts = false
BottomOverlay = <unnamed> {
}
SetRecipeReagentItem = <function> defined =[C]:-1
SetBuybackItem = <function> defined =[C]:-1
shoppingTooltips = <table> {
}
TopOverlay = <unnamed> {
}
SetMerchantItem = <function> defined =[C]:-1
SetQuestLogItem = <function> defined =[C]:-1
SetHeirloomByItemID = <function> defined =[C]:-1
SetTradeTargetItem = <function> defined =[C]:-1
SetTalent = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:402
SetTradePlayerItem = <function> defined =[C]:-1
SetIconTextureAndText = <function> defined @TipTacItemRef\ttItemRef.lua:62
ttIcon = <unnamed> {
}
SetTrainerService = <function> defined =[C]:-1
updateTooltip = 0.093999995663762
SetInventoryItem = <function> defined =[C]:-1
SetInboxItem = <function> defined =[C]:-1
ttCount = <unnamed> {
}
SetLootRollItem = <function> defined =[C]:-1
SetUnitAura = <function> defined =[C]:-1
SetUnitBuff = <function> defined =[C]:-1
SetAuctionSellItem = <function> defined =[C]:-1
SetBagItem = <function> defined =[C]:-1
needsReset = true
SetAction = <function> defined =[C]:-1
SetSendMailItem = <function> defined =[C]:-1
SetRecipeResultItem = <function> defined =[C]:-1
SetAuctionItem = <function> defined =[C]:-1
}
link = "|cffa335ee|Hitem:114821::::::::110:265::::::|h[Hexweave Bag]|h|r"
itemID = 114821
players = 1
total = 5
(for generator) = <function> defined @Bagnon\external\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:101
(for state) = nil
(for control) = "® Molten Core Bikini Shop"
owner = "® Molten Core Bikini Shop"
info = <table> {
isguild = true
name = "Molten Core Bikini Shop"
faction = "Alliance"
cached = false
realm = "Stormrage"
}
color = "|cfffad000%s|r"
(*temporary) = nil
(*temporary) = <table> {
isguild = true
name = "Molten Core Bikini Shop"
faction = "Alliance"
cached = false
realm = "Stormrage"
}

 

Major problems with this addon lately. I am saddened because I love this addon and really can't play without it. I am not technically inclined, I tried to submit a bug report at github, but I couldn't. I just don't know what to look for. I hope this is seen by the developer . I am using WoW version 8.0.1.27377. Bagnon version 8.0.2.

 

745x ...Bagnon\external\Wildpants\features\tooltipCounts.lua:74: attempt to index field '?' (a nil value)
...Bagnon\external\Wildpants\features\tooltipCounts.lua:74: in function <...Bagnon\external\Wildpants\features\tooltipCounts.lua:58>
...Bagnon\external\Wildpants\features\tooltipCounts.lua:136: in function <...Bagnon\external\Wildpants\features\tooltipCounts.lua:133>
[C]: ?
[C]: ?
[C]: ?
Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:408: in function <Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:402>
[C]: ?
[C]: ?
[C]: in function `SetHyperlink'
Bagnon\external\Wildpants\components\bag.lua:234: in function `UpdateTooltip'
Bagnon\external\Wildpants\components\bag.lua:116: in function <Bagnon\external\Wildpants\components\bag.lua:109>

Locals:
tooltip = GameTooltip {
0 = <userdata>
SetQuestLogRewardSpell = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:402
canAddRestStateLine = 1
SetExistingSocketGem = <function> defined =[C]:-1
SetCurrencyToken = <function> defined @Altoholic\Tooltip.lua:700
SetShapeshift = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:402
SetVoidItem = <function> defined =[C]:-1
SetVoidDepositItem = <function> defined =[C]:-1
Hide = <function> defined =[C]:-1
SetVoidWithdrawalItem = <function> defined =[C]:-1
SetQuestRewardSpell = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:402
comparing = false
SetSocketGem = <function> defined =[C]:-1
SetHyperlink = <function> defined =[C]:-1
Show = <function> defined =[C]:-1
SetGuildBankItem = <function> defined =[C]:-1
SetPetAction = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:402
SetUnitDebuff = <function> defined =[C]:-1
SetItemByID = <function> defined =[C]:-1
SetLootItem = <function> defined =[C]:-1
SetQuestItem = <function> defined =[C]:-1
LibExtraTipRight = <table> {
}
FadeOut = <function> defined @TipTac\ttCore.lua:856
LibExtraTipLeft = <table> {
}
__tamedCounts = false
BottomOverlay = <unnamed> {
}
SetRecipeReagentItem = <function> defined =[C]:-1
SetBuybackItem = <function> defined =[C]:-1
shoppingTooltips = <table> {
}
TopOverlay = <unnamed> {
}
SetMerchantItem = <function> defined =[C]:-1
SetQuestLogItem = <function> defined =[C]:-1
SetHeirloomByItemID = <function> defined =[C]:-1
SetTradeTargetItem = <function> defined =[C]:-1
SetTalent = <function> defined @Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:402
SetTradePlayerItem = <function> defined =[C]:-1
SetIconTextureAndText = <function> defined @TipTacItemRef\ttItemRef.lua:62
ttIcon = <unnamed> {
}
SetTrainerService = <function> defined =[C]:-1
updateTooltip = 0.093999995663762
SetInventoryItem = <function> defined =[C]:-1
SetInboxItem = <function> defined =[C]:-1
ttCount = <unnamed> {
}
SetLootRollItem = <function> defined =[C]:-1
SetUnitAura = <function> defined =[C]:-1
SetUnitBuff = <function> defined =[C]:-1
SetAuctionSellItem = <function> defined =[C]:-1
SetBagItem = <function> defined =[C]:-1
needsReset = true
SetAction = <function> defined =[C]:-1
SetSendMailItem = <function> defined =[C]:-1
SetRecipeResultItem = <function> defined =[C]:-1
SetAuctionItem = <function> defined =[C]:-1
}
link = "|cffa335ee|Hitem:114821::::::::110:265::::::|h[Hexweave Bag]|h|r"
itemID = 114821
players = 1
total = 5
(for generator) = <function> defined @Bagnon\external\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:101
(for state) = nil
(for control) = "® Molten Core Bikini Shop"
owner = "® Molten Core Bikini Shop"
info = <table> {
isguild = true
name = "Molten Core Bikini Shop"
faction = "Alliance"
cached = false
realm = "Stormrage"
}
color = "|cfffad000%s|r"
(*temporary) = nil
(*temporary) = <table> {
isguild = true
name = "Molten Core Bikini Shop"
faction = "Alliance"
cached = false
realm = "Stormrage"
}

 

 
![wowscrnshot_082118_074935](https://user-images.githubusercontent.com/42580146/44410518-6c078e00-a519-11e8-999c-2c3a7749405d.jpg)

**Comment by coffeecat-arianell** [comment]
Hey I was having a similar issue - I disabled the "Bagnon LegionPower" addon which seemed to help. Good luck!
