### ISSUE TITLE
guild bank only displays 4 of 7 guild bank bags

### ISSUE THREAD

**Issue by dizzy8578** [Jaliborc/Bagnon#773]
**Running Software (please complete the following information):**
 - Game patch  Build 8.0.1
 - Addon version 8.0.2

**Describe the bug**
guild bank only displays 4 of 7 guild bank bags. disable bagnon guild bank and the bliz version displays all bags correctly. I have unloaded all add ons and uninstalled and reinstalled from twitch 
**To Reproduce**
it may be some config file cached that is not getting nuked on reinstall but I don't know where to look for it. 
**Expected behavior**
expect previous behavior where 

all guild bank bags were displayed.
**Screenshots**
![guild-bank1](https://user-images.githubusercontent.com/42660812/44559286-c5301700-a6fd-11e8-8669-136f5f6a87f2.jpg)
**Error Logs**
If applicable, add the first error message (labeled 1/Many) that appeared.

**Additional context**

**Comment by JimGiordano2** [comment]
Just tried version 8.0.6 and it still has this problem.  Clearly the author doesn't have this problem or it would be higher on his to do list.  Wonder why some would have it and others not?

**Comment by leifashley** [comment]
9/10/2018 - I'm still having this same issue. It's been here for a long while....

**Comment by Blissybabe** [comment]
Still having this issue...There is a guildie that has this addon and is also having this issue.   Please let us know if this is a setting or a bug.  Thank you so much for creating an awesome addon!!!

**Comment by Jaliborc** [comment]
https://www.patreon.com/posts/looking-for-for-21771493
