### ISSUE TITLE
Bagnon search not highlighting all valid items

### ISSUE THREAD

**Issue by greecemonkey** [Jaliborc/Bagnon#779]
bagnon 8.0.2

searching for soulbound items does not highlight all soulbound items in bag

![bagnon](https://user-images.githubusercontent.com/42788129/44755090-3f8bdd00-aaea-11e8-817d-8fc90adbea3d.png)

**Comment by Jaliborc** [comment]
I see you are running addons that make minor modifications to bagnon. Please:
- Post here all the addons that interface with Bagnon and all addons that modify tooltips you are running
- Test if the issue persists with those addons disabled

**Comment by xeropresence** [comment]
Disabled all addons except for bagnon issue still occurs.

**Comment by xeropresence** [comment]
Still occurs with the latest version

**Comment by xeropresence** [comment]
This going to get looked at?

**Comment by xeropresence** [comment]
Well I figured this issue out as well.

https://github.com/Jaliborc/LibItemSearch-1.2/blob/master/LibItemSearch-1.2.lua#L305

searching for "soulbound" will only yield BOP items.
