### ISSUE TITLE
GuildBank Permissions are not clearly displayed

### ISSUE THREAD

**Issue by numismatika** [Jaliborc/Bagnon#837]
**Is your feature request related to a problem? Please describe.**
Access to guild bank contents is restricted per day & per tab for different ranks.
I am always wondering what goods to retrieve

**Describe the solution you'd like**

The current withdrawal numbers on top of each tab should automatically refreshed when the limit changes because a new period started or you fetched an item.

Draw items with a red background that you cannot withdraw, highlight bank slots in green which you can fill.

**Comment by NitroxydeX** [comment]
This problem seems to still persist. Is there any information on the current status of this?
