### ISSUE TITLE
LUA error, unsure of cause

### ISSUE THREAD

**Issue by raysmith59** [Jaliborc/Bagnon#913]
Game 8.1.5, Bagon 8.1.8.

I have no idea what I did to cause it but I had my bags open, did something (hovered over an item in my bags?), then got this:

4x FrameXML\FloatingPetBattleTooltip.lua:107: attempt to index field '?' (a nil value)
FrameXML\FloatingPetBattleTooltip.lua:107: in function `BattlePetTooltipTemplate_SetBattlePet'
FrameXML\BattlePetTooltip.lua:20: in function `BattlePetToolTip_Show'
Bagnon\external\Wildpants\components\item.lua:495: in function <Bagnon\external\Wildpants\components\item.lua:484>
[C]: in function `Show'
Bagnon\external\Wildpants\components\item.lua:204: in function <Bagnon\external\Wildpants\components\item.lua:199>

Locals:
tooltipFrame = BattlePetTooltip {
 0 = <userdata>
 BorderBottomLeft = <unnamed> {
 }
 Owned = <unnamed> {
 }
 SpeedTexture = <unnamed> {
 }
 Background = <unnamed> {
 }
 HealthTexture = <unnamed> {
 }
 speciesID = 158923
 Speed = <unnamed> {
 }
 BorderTop = <unnamed> {
 }
 PetType = <unnamed> {
 }
 BorderTopLeft = <unnamed> {
 }
 BorderTopRight = <unnamed> {
 }
 BorderLeft = <unnamed> {
 }
 Power = <unnamed> {
 }
 PowerTexture = <unnamed> {
 }
 PetTypeTexture = <unnamed> {
 }
 BattlePet = <unnamed> {
 }
 Name = <unnamed> {
 }
 Health = <unnamed> {
 }
 Level = <unnamed> {
 }
 BorderBottom = <unnamed> {
 }
 BorderBottomRight = <unnamed> {
 }
 BorderRight = <unnamed> {
 }
}
data = <table> {
 speed = "2"
 customName = "158923"
 name = 158923
 power = "11"
 speciesID = 158923
 level = "353"
 breedQuality = 10
 maxHealth = "9"
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = 10
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"

**Comment by Hedel1** [comment]
if you are using twitch to install it, make sure youre not installing it on the beta folder
